### ISSUE TITLE
Jenkins collector not retrieving new build data for pipeline jobs 

### ISSUE THREAD

**Issue by canary6** [Hygieia/Hygieia#1371]
The Hygieia Jenkins collector retrieves build data successfully upon initial configuration for pipeline jobs, but subsequently fails to retrieve new build information for those pipeline jobs previously configured. Non-pipeline jobs seem to retrieve new build information successfully. Seems similar to issue #1332

To reproduce:

1) Configure pipeline and non-pipeline jobs in Jenkins.
2) Configure Hygieia to retrieve Jenkins build data for jobs.
3) Execute Jenkins jobs.
4) Observe updates for non-pipeline jobs, but not for pipeline jobs.

**Comment by canary6** [comment]
This problem continues to manifest itself. Has anyone experienced this? Can you reproduce it.

**Comment by mandeepmehra** [comment]
I also faced same issue with below exception in Hygieia Jenkins collector logs
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getString(DefaultHudsonClient.java:370) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.addChangeSets(DefaultHudsonClient.java:235) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getBuildDetails(DefaultHudsonClient.java:188) ~[jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.addNewBuilds(HudsonCollectorTask.java:193) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:95) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:32) [jenkins-build-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by rvema** [comment]
@canary6 Can you try using hygieia-jenkins-plugin in place of the Jenkins Collector?

**Comment by Sbrenthughes** [comment]
@canary6 can you give more detail? I have just followed your steps and both jobs are being pulled.
