### ISSUE TITLE
Jenkins collector not working

### ISSUE THREAD

**Issue by sushmaharish** [Hygieia/Hygieia#2202]
Jenkins collector not working 

2018-05-14 10:40:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-05-14 10:40:00,024 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:48}] to localhost:27017
2018-05-14 10:40:00,081 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-14 10:40:00,082 INFO  c.c.d.collector.CollectorTask - http://10.32.66.161/jenkins
2018-05-14 10:40:00,082 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-05-14 10:40:00,115 ERROR c.c.d.collector.DefaultHudsonClient - Parsing jobs on instance: http://10.32.66.161/jenkins
org.json.simple.parser.ParseException: null

   at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:203) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:113) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:101) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:39) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-05-14 10:55:00,036 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2018-05-14 10:55:00,036 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2018-05-14 10:55:00,038 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2018-05-14 10:55:00,041 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2018-05-14 10:55:00,041 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-05-14 10:56:48,584 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:9, serverValue:51}] to localhost:27017 because it is past its maximum allowed idle time.

**Comment by anayyadav** [comment]
share your application.properties file for jenkins collector

**Comment by sushmaharish** [comment]
Hi,

Please find here applictaion.properties file for jenkins collector.

properties file location    :   /var/hygieia/Hygieia/application.properties
and jenkins collector jar file is located at :    /var/hygieia/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-2.0.5-SNAPSHOT.jar

[application.properties-jenkins.txt](https://github.com/capitalone/Hygieia/files/2003936/application.properties-jenkins.txt)


Please help..

**Comment by anayyadav** [comment]
dont save the file as .txt ext. 
the name of the file should be application.properties
for the content of application.properties file please follow the link as see the jenkins.properties file 
https://github.com/anayyadav/Hygieia_Installation_steps.git

**Comment by sushmaharish** [comment]
It is not txt file , when I copied to notepad it saved as txt.

**Comment by nireeshT** [comment]
@sushmaharish  check if you can access http://10.32.66.161/jenkins/api/json?tree=jobs, response should be null and caused parse exception.

**Comment by anayyadav** [comment]
sushmaharish 
open in a new tab in notepad ++ and the try to save it as .properties file. The ext. of the file must be .properties not .properties.txt

**Comment by sushmaharish** [comment]
I have installed hygieia on Linux system. and  properties file name and type is proper.

**Comment by sushmaharish** [comment]
Hi Nireesh  

I can access the link  http://10.32.66.161/jenkins/api/json?tree=jobs ----->
curl http://10.32.66.161/jenkins/api/json?tree=jobs
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://wipro-codereviewserver-devops.bos.infocrossing.com/jenkins/api/json?tree=jobs">here</a>.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at 10.32.66.161 Port 80</address>
</body></html>

pls help to resolve parser error as I mentioned in the issue

**Comment by rvema** [comment]
@sushmaharish Are you still having issues?

**Comment by yuhong02** [comment]
I have similar issue as:
2018-05-14 10:40:00,115 ERROR c.c.d.collector.DefaultHudsonClient - Parsing jobs on instance: http://10.32.66.161/jenkins
org.json.simple.parser.ParseException: null.
In the browser, I can open the job details info page. But, collector cannot get job details info.
Could you help me out of this?

**Comment by babujii** [comment]
Hi, Jenkins build collector logs is not showing hygieia dashboard and list is not found. How do i list it. Can you help me.

**Comment by rvema** [comment]
Closing the issue due to inactivity
