### ISSUE TITLE
Hygieia - JIRA - Collector

### ISSUE THREAD

**Issue by venkiradkris** [Hygieia/Hygieia#2229]
Hi - I am getting following two issues in Hygieia - JIRA - Collector. Please help. Thanks.

ISSUE # 1 - WHILE GETTING PROJECT LEVEL DATA FROM JIRA
c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
c.c.d.collector.FeatureCollectorTask - Failed to collect projectData information
java.lang.RuntimeException: org.apache.http.ConnectionClosedException: Connection closed
        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-14.0.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203) ~[guava-14.0.jar!/:na]
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-14.0.jar!/:na]

ISSUE # 2 - WHILE GETTING STORY LEVEL DATA FROM JIRA
c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...
c.c.d.client.DefaultJiraClient - Parser exception when parsing statuses
org.json.simple.parser.ParseException: null
        at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:453) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:750) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:154) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:137) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

**Comment by venkiradkris** [comment]
Also ISSUE # 3
I have updated Active Sprint Data in JIRA (Example -Moved one Story from "In Progress" to "To Do" AND updated Story points, Estimated Hours etc). Even after 30 mins, Dashboard is not reflecting the change.
Any change is needed in following properties? OR Anything is missing?
feature.deltaStartDate=2018-05-22T00:00:00.000000
feature.masterStartDate=2018-05-22T00:00:00.000000
feature.deltaCollectorItemStartDate=2018-05-22T00:00:00.000000
My collector is continuously running. In one of my earlier setup of Hygieia with JIRA, i have experienced that the next moment of JIRA change gets reflected in collector and dashboard. However here today, this is not happening. Please suggest.

**Comment by rvema** [comment]
@venkiradkris Is this issue still happening?

**Comment by Sbrenthughes** [comment]
@venkiradkris  Please refer to #2667. As this is the collector rewrite in progress

**Comment by Navya-V** [comment]
my jira dashboard displays only 3 open issues which were recently added in jira ,it doesnt display any WIP and Done Count both are 0 0 .we have around 90 issues that are not displayed.
can anybody help by posting  the required properties which works perfectly.
i have seen all properties and tried all properties from all issues which is available online.
Any help would be great .working on Hygieia from long time.
Thanks in advance
