### ISSUE TITLE
Jenkins Build Collector Fails :: org.springframework.web.client.HttpClientErrorException: 414 URI Too Long

### ISSUE THREAD

**Issue by AshokChengaSGAS** [Hygieia/Hygieia#2403]
2018-08-12 16:03:01,060 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://coffee-jenkins-elb.xyz.com/  0s
2018-08-12 16:04:01,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2018-08-12 16:04:01,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-08-12 16:04:01,009 INFO  c.c.d.collector.CollectorTask - http://coffee-jenkins-elb.xyz.com/ 0s
2018-08-12 16:04:01,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-08-12 16:04:01,057 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/6 pageSize 1000...
2018-08-12 16:04:01,061 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs details
org.springframework.web.client.HttpClientErrorException: 414 URI Too Long
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:650) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:126) ~[jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:127) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:42) [jenkins-build-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2018-08-12 16:04:01,061 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://coffee-jenkins-elb.xyz.com/ 0s

**Comment by AshokChengaSGAS** [comment]
Hi , Can any one comment on this issue .  why this error and why rest call is not able to handle the response . ( RestTemplate.java:641)

 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs details
org.springframework.web.client.HttpClientErrorException: 414 URI Too Long
at 

Thanks

**Comment by matthewbeasley** [comment]
@AshokChengaSGAS - can you provide some background about your jenkins server? Specifically how many jobs do you have in total?

**Comment by AshokChengaSGAS** [comment]
Fetching jobs 0/6 

2018-08-12 16:04:01,057 INFO c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/6 pageSize 1000...
2018-08-12 16:04:01,061 ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs details
org.springframework.web.client.HttpClientErrorException: 414 URI Too Long

**Comment by AshokChengaSGAS** [comment]
jenkins.folderDepth = 10  fixed  the error 

client exception loading jobs details
org.springframework.web.client.HttpClientErrorException: 414 URI Too Long

**Comment by AshokChengaSGAS** [comment]
Thanks @matthewbeasley
