### ISSUE TITLE
jira-feature-collector -- Connection Refused Error

### ISSUE THREAD

**Issue by Prasanna2104** [Hygieia/Hygieia#2404]
I have Installed Hygieia latest code from GitHub (https://github.com/capitalone/Hygieia.git). I'm trying to enable jira using jira-feature-collector.

application.properties : 
```
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
#dbusername=dashboarduser

# Database Password - default is blank
#dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=25

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2018-01-01T00:00:00.000000
feature.masterStartDate=2018-08-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2018-08-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=xx.xx.xx.xx
feature.jiraProxyPort=8080
feature.jiraBaseUrl=https://jira-ex.xxx.com
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=TlExMDAwMDpKdWxAMTIzIQ==

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
		feature.jiraOauthRedirecturi=
		feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10005

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10006

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true
```
When I Execute the the collector using below java command, got an error message
```
C:\Prasanna\Hygieia-master\Hygieia-master\collectors\feature\jira\target>java -Dhttp.proxyHost=xx.xx.xx -Dhttp.proxyPort=8080 -Dhttp.auth.preference=Basic -jar jira-feature-collector.jar --spring.config.name=feature --spring.config.location=C:\Hygieia-master\Hygieia-master
\collectors\feature\jira\application.properties
```

Error Message : 

> 2018-08-14 12:28:24,149 INFO  o.s.cloud.commons.util.InetUtils - Cannot determine local hostname
> 2018-08-14 12:28:24,286 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
> 2018-08-14 12:28:24,376 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
> 2018-08-14 12:28:24,377 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
> 2018-08-14 12:28:24,381 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
> 2018-08-14 12:28:24,397 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
> 2018-08-14 12:28:24,494 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
> 2018-08-14 12:28:24,559 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=40f6fdb0,type=ConfigurationPropertiesRebinder]
> 2018-08-14 12:28:24,897 INFO  com.capitalone.dashboard.Application - Started Application in 25.285 seconds (JVM running for 26.957)
> 2018-08-14 12:28:59,982 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
> 2018-08-14 12:29:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2018-08-14 12:29:00,043 INFO  c.c.d.collector.CollectorTask - https://jira-ex.xx.com
> 2018-08-14 12:29:00,049 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2018-08-14 12:29:00,073 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
> 2018-08-14 12:29:01,253 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
> java.lang.RuntimeException: java.net.ConnectException: Connection refused: no further information
>         at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-14.0.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
>         at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
>         at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
>         at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-14.0.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$2.run(SettableFuturePromiseHttpPromiseAsyncClient.java:59) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
>         at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
> Caused by: java.net.ConnectException: Connection refused: no further information
>         at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_161]
>         at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[na:1.8.0_161]
>         at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:374) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.conn.PoolingClientAsyncConnectionManager.execute(PoolingClientAsyncConnectionManager.java:108) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
>         at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.doExecute(AbstractHttpAsyncClient.java:464) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
>         at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.access$000(AbstractHttpAsyncClient.java:101) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
>         at org.apache.http.impl.nio.client.AbstractHttpAsyncClient$1.run(AbstractHttpAsyncClient.java:485) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
> 2018-08-14 12:29:03,817 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@40f6fdb0: startup date [Tue Aug 14 12:28:06 CEST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@f6605

**Comment by matthewbeasley** [comment]
@Prasanna2104 - it looks like your jira server is unreachable from the host where you are running the jira collector. Could you run some diagnostic commands to test this connectivity?

**Comment by Prasanna2104** [comment]
@matthewbeasley  - I have installed Hygieia in Windows 8 machine. I can able to connect to the JIRA instance from my Browser and I can able to ping the server. But now I'm getting connection Timed out Error

```
C:\Prasanna\Hygieia-master\Hygieia-master\collectors\feature\jira\target>ping jira-ex.xxx.com

Pinging jira-ex.telefonica.de [82.113.113.177] with 32 bytes of data:
Reply from xx.xxx.xxx.xxx: bytes=32 time=3ms TTL=249
Reply from xx.xxx.xxx.xxx: bytes=32 time=1ms TTL=249
Reply from xx.xxx.xxx.xxx: bytes=32 time=1ms TTL=249

Ping statistics for xx.xxx.xxx.xxx:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 3ms, Average = 1ms
```

I have started the jira collector by passing the proxy also.

`java -Dhttp.proxyHost=xx.xx.xx.com -Dhttp.proxyPort=8080 -Dhttp.auth.preference=Basic -jar jira-feature-collector.jar --spring.config.name=feature --spring.config.location=C:\Prasanna\Hygieia-master\Hygieia-master\collectors\feature\jira\application.properties`

> 2018-08-16 10:59:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
> 2018-08-16 10:59:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2018-08-16 10:59:00,015 INFO  c.c.d.collector.CollectorTask - https://jira-ex.xxx.com
> 2018-08-16 10:59:00,017 INFO  c.c.d.collector.CollectorTask - -----------------------------------
> 2018-08-16 10:59:00,036 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
> 2018-08-16 10:59:05,231 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
> java.lang.RuntimeException: java.net.SocketTimeoutException
>         at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-14.0.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:256) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient$3.apply(DefaultHttpClient.java:249) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:276) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
>         at com.atlassian.util.concurrent.Promises$Of$2.apply(Promises.java:272) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
>         at com.atlassian.util.concurrent.Promises$2.onFailure(Promises.java:167) ~[atlassian-util-concurrent-2.4.0-M9.jar!/:na]
>         at com.google.common.util.concurrent.Futures$4.run(Futures.java:1145) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:150) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:135) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:203) ~[guava-14.0.jar!/:na]
>         at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68) ~[guava-14.0.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$2.run(SettableFuturePromiseHttpPromiseAsyncClient.java:59) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192) ~[atlassian-httpclient-apache-httpcomponents-0.13.2.jar!/:na]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
>         at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
> Caused by: java.net.SocketTimeoutException: null
>         at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:170) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:403) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:593) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:180) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:214) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:157) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:374) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
>         at org.apache.http.impl.nio.conn.PoolingClientAsyncConnectionManager.execute(PoolingClientAsyncConnectionManager.java:108) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
>         at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.doExecute(AbstractHttpAsyncClient.java:464) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
>         at org.apache.http.impl.nio.client.AbstractHttpAsyncClient.access$000(AbstractHttpAsyncClient.java:101) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
>         at org.apache.http.impl.nio.client.AbstractHttpAsyncClient$1.run(AbstractHttpAsyncClient.java:485) ~[httpasyncclient-4.0-beta3-atlassian-1.jar!/:4.0-beta3-atlassian-1]
> 2018-08-16 10:59:07,629 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@40f6fdb0: startup date [Thu Aug 16 10:58:32 CEST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@f660
> c7

**Comment by matthewbeasley** [comment]
@Prasanna2104 - since you use https then `-Dhttps.ProxyHost` would be more appropriate. I typically just include both `-Dhttp` and `-Dhttps` for safety ;) . Testing from the browser may not be complete enough of a test. I'm not a windows guy but there must be some cli utility similar to `curl` that you can use to test connectivity?

**Comment by matthewbeasley** [comment]
I'm closing this due to inactivity. @Prasanna2104 please reopen if you have followed the above advice and are still experiencing this issue.
