### ISSUE TITLE
Hygiria-API: Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException

### ISSUE THREAD

**Issue by ndared01** [Hygieia/Hygieia#2414]
Hi,

As part of Hygieia-API connection, I am facing below error after running the command "java -jar api.jar --spring.config.location=C:\Users\IBM_ADMIN\Documents\Noor\Hygieia\api\dashboard.properties". Before this step, my Mongo server is already up and running. Please help me to resolve this issue. Thanks in advance!

Error:
Caused by: com.mongodb.MongoCommandException: Command failed with error 59: 'no such cmd: saslStart' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "no such cmd: saslStart", "code" : 59, "bad cmd" : { "saslStart" : 1, "mechanism" : "SCRAM-SHA-1", "payload" : { "$binary" : "biwsbj1kYXNoYm9hcmR1c2VyLHI9N3lBXEdNaXtcZjZBZFguZTczQC5LT3xD", "$type" : "0" } } }
	at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar!/:na]
	... 5 common frames omitted
2018-08-22 22:37:04,900 INFO  org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboarddb', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 59: 'no such cmd: saslStart' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "no such cmd: saslStart", "code" : 59, "bad cmd" : { "saslStart" : 1, "mechanism" : "SCRAM-SHA-1", "payload" : { "$binary" : "biwsbj1kYXNoYm9hcmR1c2VyLHI9N3lBXEdNaXtcZjZBZFguZTczQC5LT3xD", "$type" : "0" } } }}}]}. Waiting for 30000 ms before timing out
2018-08-22 22:37:34,907 ERROR o.s.b.c.e.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException

**Comment by ndared01** [comment]
Please help me with above error

**Comment by ndared01** [comment]
Thanks Matthewbeasley! 
I had some typo mistake in api.properties file. As of now, I am all set. Thanks!
