### ISSUE TITLE
Failed build of Hygieia jenkins-codequality :  CodeQualityMetricsConverterTest.coverageStatsFromJacocoXml:232

### ISSUE THREAD

**Issue by Antoine1838** [Hygieia/Hygieia#2425]
Hi,

I am following the standard procedure (with -e on second run to get more info) with a clean .m2 repository:
`mvn -e clean install package`

I get the following error:
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ jenkins-codequality ---
[INFO] Surefire report directory: ...\Hygieia\collectors\build\jenkins-codequality\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.capitalone.dashboard.collector.HttpJenkinsClientTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.604 sec - in com.capitalone.dashboard.collector.HttpJenkinsClientTest
Running com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTaskTest
11:27:42,189 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:27:42,189 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:27:42,190 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/.../Hygieia/collectors/build/jenkins-codequality/target/classes/logback.xml]
11:27:42,191 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
11:27:42,191 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/.../Hygieia/core/target/core-2.0.5-SNAPSHOT.jar!/logback.xml]
11:27:42,191 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/.../Hygieia/collectors/build/jenkins-codequality/target/classes/logback.xml]
11:27:42,294 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:27:42,297 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:27:42,313 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:27:42,333 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:27:42,422 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:27:42,426 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
11:27:42,460 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
11:27:42,462 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/codequalitycollector-%d{yyyy-MM-dd}.%i.log for the active file
11:27:42,466 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@74a820bf - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/codequalitycollector-%d{yyyy-MM-dd}.%i.log'.
11:27:42,466 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@74a820bf - Roll-over at midnight.
11:27:42,468 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@74a820bf - Setting initial period to Wed Sep 05 11:27:42 EDT 2018
11:27:42,472 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:27:42,472 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/codequalitycollector-2018-09-05.0.log
11:27:42,472 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
11:27:42,474 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:27:42,475 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
11:27:42,476 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:27:42,476 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:27:42,477 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5a30722c - Registering current configuration as safe fallback point

2018-09-05 11:27:42,814 INFO  c.c.d.collector.CollectorTask - examined jobs           1        0s
2018-09-05 11:27:42,834 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,834 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,839 INFO  c.c.d.collector.CollectorTask - examined jobs           3        0s
2018-09-05 11:27:42,839 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,839 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - examined jobs           1        0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - examined jobs           4        0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - examined jobs           1        0s
2018-09-05 11:27:42,844 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,860 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,860 INFO  c.c.d.collector.CollectorTask - examined jobs           1        0s
2018-09-05 11:27:42,860 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,860 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,881 INFO  c.c.d.collector.CollectorTask - examined jobs           1        0s
2018-09-05 11:27:42,881 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,881 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,882 INFO  c.c.d.collector.CollectorTask - examined jobs           3        0s
2018-09-05 11:27:42,882 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,882 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-05 11:27:42,882 INFO  c.c.d.collector.CollectorTask - examined jobs           0        0s
2018-09-05 11:27:42,882 INFO  c.c.d.collector.CollectorTask - new data                0        0s
2018-09-05 11:27:42,882 INFO  c.c.d.collector.CollectorTask - Finished                         0s
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.775 sec - in com.capitalone.dashboard.collector.JenkinsCodeQualityCollectorTaskTest
Running com.capitalone.dashboard.collector.ResponseConversionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.618 sec - in com.capitalone.dashboard.collector.ResponseConversionTest
Running com.capitalone.dashboard.jenkins.JenkinsJobTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in com.capitalone.dashboard.jenkins.JenkinsJobTest
Running com.capitalone.dashboard.jenkins.JenkinsPredicateTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.capitalone.dashboard.jenkins.JenkinsPredicateTest
Running com.capitalone.dashboard.utils.CodeMetricsCodeQualitConverterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.utils.CodeMetricsCodeQualitConverterTest
Running com.capitalone.dashboard.utils.CodeQualityDataServiceTest
2018-09-05 11:27:43,603 INFO  c.c.d.utils.CodeQualityDataService - storing new job at timestamp
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec - in com.capitalone.dashboard.utils.CodeQualityDataServiceTest
Running com.capitalone.dashboard.utils.CodeQualityMetricsConverterTest

**Tests run: 13, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.06 sec <<< FAILURE! - in com.capitalone.dashboard.utils.CodeQualityMetricsConverterTest
coverageStatsFromJacocoXml(com.capitalone.dashboard.utils.CodeQualityMetricsConverterTest)  Time elapsed: 0.03 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"90[.]909"> but was:<"90[,]909">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.capitalone.dashboard.utils.CodeQualityMetricsConverterTest.coverageStatsFromJacocoXml(CodeQualityMetricsConverterTest.java:232)**

sumsCoverageStatsFromJacocoXml(com.capitalone.dashboard.utils.CodeQualityMetricsConverterTest)  Time elapsed: 0.002 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"90[.]909"> but was:<"90[,]909">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.capitalone.dashboard.utils.CodeQualityMetricsConverterTest.sumsCoverageStatsFromJacocoXml(CodeQualityMetricsConverterTest.java:260)

Results :

Failed tests:
  CodeQualityMetricsConverterTest.coverageStatsFromJacocoXml:232 expected:<"90[.]909"> but was:<"90[,]909">
  CodeQualityMetricsConverterTest.sumsCoverageStatsFromJacocoXml:260 expected:<"90[.]909"> but was:<"90[,]909">

Tests run: 46, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia 2.0.5-SNAPSHOT .... SUCCESS [  2.651 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 51.682 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 32.601 s]
[INFO] com.capitalone.dashboard:api-audit ................. SUCCESS [ 13.789 s]
[INFO] com.capitalone.dashboard:rally-collector ........... SUCCESS [  5.469 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  4.409 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  4.765 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  5.217 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  4.405 s]
[INFO] com.capitalone.dashboard:jenkins-codequality ....... FAILURE [  5.129 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:score-collector ........... SKIPPED
[INFO] Hygieia Publisher Plugin ........................... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests 2.0.5-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:19 min
[INFO] Finished at: 2018-09-05T11:27:43-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project jenkins-codequality: There are test failures.
[ERROR]
[ERROR] Please refer to ...\Hygieia\collectors\build\jenkins-codequality\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project jenkins-codequality: There are test failures.

Please refer to ...\Hygieia\collectors\build\jenkins-codequality\target\surefire-reports for the individual test results.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to ...\Hygieia\collectors\build\jenkins-codequality\target\surefire-reports for the individual test results.
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:82)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:254)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:854)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:722)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jenkins-codequality

Any idea on what is causing the error?

**Comment by stevegal** [comment]
Looks to be a localisation issue. Is your local one with `,` instead of `.` for decimal points?

**Comment by Sbrenthughes** [comment]
Please reopen if the above PR didn’t solve this issue.
