### ISSUE TITLE
Setting up encryption with docker-compose

### ISSUE THREAD

**Issue by marchenm** [Hygieia/Hygieia#2429]
I'm trying to configure Hygieia Github collector.  Here's my docker-compose.override.yml
```
version: '3'
services:
  api:
    environment: # for a full list check the corresponding properties-builder file
      - SPRING_DATA_MONGODB_DATABASE=dashboarddb
      - SPRING_DATA_MONGODB_HOST=db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=dashboarduser
      - SPRING_DATA_MONGODB_PASSWORD=dbpassword
      - JASYPT_ENCRYPTOR_KEY=supersecretencryptionkey
      - AUTH_SECRET=supersecretauthkey
      - KEY=tVT3AXZwufLmN/3+FfLNTLbmyMFK3+zW
    volumes:
      - ./logs:/hygieia/logs

  api-audit:
    # environment:

  db-setup:
    environment:
      - WAIT_HOSTS=db:27017

  ui:
    # environment:

  github-collector:
    environment:
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=dashboarduser
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpassword
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboarddb
      - MONGO_PORT=tcp://db:27017
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - GITHUB_ERROR_THRESHOLD=250
      - GITHUB_HOST=https://github.com
      - GITHUB_CRON=0 * * * * *
      - GITHUB_COMMIT_THRESHOLD_DAYS=30
      - KEY=tVT3AXZwufLmN/3+FfLNTLbmyMFK3+zW
      - PERSONAL_ACCESS_TOKEN= </github token/>
```
To get the `key=tVT3AXZwufLmN/3+FfLNTLbmyMFK3+zW` environment variable i started the containers without it and in the ui went to generate apitokens and generated that key. I then added it to the  override file and did `docker-compose down && docker-compose up`

When i configure a private repo I'm seeing decrypt errors in the log

```
2018-09-06 23:44:00,016 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Empty key
2018-09-06 23:44:00,016 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/private/repo/commits?sha=master&since=2018-08-23T23:44Z
2018-09-06 23:44:00,016 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Empty key
2018-09-06 23:44:00,041 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/private/repo
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:596) ~[github-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:177) ~[github-scm-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
I'm not sure what I'm missing here.

**Comment by subodhbattina** [comment]
@marchenm : From the logs you shared it looks like the Key value may not set properly with in your container. Please make sure the key value is available for decryption. ```2018-09-06 23:44:00,016 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Empty key```

**Comment by subodhbattina** [comment]
@marchenm : I am sorry I didn't get a chance to follow up on this last couple days. Is this issue resolved at your end? Please confirm so I can close this issue if it is resolved. Thanks !

**Comment by marchenm** [comment]
I'm still having the issue. Is there any documentation on how to set up encryption with the docker containers?

**Comment by subodhbattina** [comment]
@marchenm: I think the question is, within your Dockerfile for the collector, how are you setting the properties that the collector expects. Ensure you are setting the KEY value on the properties file that the collector expects.

**Comment by subodhbattina** [comment]
This is an example for the github collector properties file below:

```
dbname=<dbname>
dbreplicaset=false
dbhostport=<dbhost>:<port>
dbusername=<dbusername>
dbpassword=<dbpassword>
github.cron=0 0/1 * * * *
github.host=github.com

# Maximum number of previous days from current date, when fetching commits
github.commitThresholdDays=15

# Optional: Error threshold count after which collector stops collecting for a collector item. Default is 2.
github.errorThreshold=1

github.key=<key used for encryption/decryption>

# Personal access token generated from github and used for making authenticated calls
github.personalAccessToken=<personal Access Token>```

**Comment by marchenm** [comment]
After regenerating the apikey in the ui and adding it to the `docker-compose.override.yml` I was able to get encryption working by re-entering my github personal access token in the configuration ui. Why isn't it picking up the tocken from the properties file? 
https://github.com/Hygieia/Hygieia/blob/b9fd1dfc5bd823a14c925073ee5f38037b5e6d74/collectors/scm/github/docker/properties-builder.sh#L33

**Comment by subodhbattina** [comment]
@marchenm Firstly, just so i understand what you are saying: The "apiKey" and "personalAccessToken" are two different things:
1. "apiKey" is used purely for encryption and decryption
2. "personalAccessToken" is used for accessing the github api's.

That said: The docker compose file that you posted shows this below:
```- KEY=tVT3AXZwufLmN/3+FfLNTLbmyMFK3+zW
      - PERSONAL_ACCESS_TOKEN= </github token/>```

Where as "properties-builder.sh" shows this below:

```#This is the key generated using the Encryption class in core
github.key=${GITHUB_KEY}
#personal access token generated from github and used for making authentiated calls
github.personalAccessToken=${PERSONAL_ACCESS_TOKEN}```

I hope you are reading the "apiKey" as "github.key=${KEY}".
Just wanted to point this out incase this is causing any failures as it is right above where you set the "github.personalAccessToken" in the "properties-builder.sh"

That said:
Are you able to cat and share the properties file?
Also, could you please share your Dockerfile? Thanks.

**Comment by marchenm** [comment]
Right, I understand the difference. I set GITHUB_KEY is set to the apiKey that was generated in the ui.

After deploying the containers and generating the key in the ui I set it  in the `docker-compose.override.yml` as environment variables for the api container and the github collector. 
```
version: '3'
services:
  api:
    environment: # for a full list check the corresponding properties-builder file
      - SPRING_DATA_MONGODB_DATABASE={{ db_name }}
      - SPRING_DATA_MONGODB_HOST=db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME={{ db_user }}
      - SPRING_DATA_MONGODB_PASSWORD={{ db_pass }}
      - KEY={{ github_apiKey }}
      - AUTH_SECRET={{ hygieia_auth_key }}
    volumes:
      - ./logs:/hygieia/logs

  github-collector:
    environment:
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME={{ db_user }}
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD={{ db_pass }}
      - HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE={{ db_name }}
      - MONGO_PORT=tcp://db:27017
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - GITHUB_ERROR_THRESHOLD=25
      - GITHUB_KEY={{ hygieia_encrypt_key }}
      - GITHUB_HOST=https://github.com
      - GITHUB_CRON=0 * * * * *
      - GITHUB_COMMIT_THRESHOLD_DAYS=300
      - PERSONAL_ACCESS_TOKEN={{ github_access_token }}
      - GITHUB_KEY={{ github_apiKey }}
```

Encryption now works; however, the github personal access token doesn't work when specified in the properties file. When I specify the github personal access token in the UI the collector pulls the github data.

**Comment by subodhbattina** [comment]
@marchenm 
When you specify the github personal access token in the UI, it gets stored in the database with the repo details, and collector is able to pull that out from the database.

Again, are you able to cat and see your properties file for the collector that the Dockerfile makes, can you please share that.
Just to debug, make the properties file at a location you are able to access it, before copying it into your image context folder, and then share the file please.
We want to make sure the property "github.personalAccessToken" is having the token value on the properties file. Thanks !

**Comment by subodhbattina** [comment]
@marchenm: If you dont have any updates on this, will go ahead and close the issue, thanks

**Comment by subodhbattina** [comment]
@marchenm: Since I didn't see any updates, assuming this is resolved at your end. Closing the issue, thanks

**Comment by ysnoussi** [comment]
@subodhbattina I don't thing that you understood @marchenm  issue/finding.

puting PERSONAL_ACCESS_TOKEN in the properties files doesn't change anything, you have to do it fron the UI to get it to work. in this is due to : (DefaultGithubClient.java) 
`        String personalAccessToken = (String) repo.getOptions().get("personalAccessToken");
        String decryptedPersonalAccessToken = decryptString(personalAccessToken, settings.getKey());`
where repo is fetched from db pushed by API/UI, so the documentation is misleading and need to be updated.
