### ISSUE TITLE
Tests failing during installation 

### ISSUE THREAD

**Issue by vmattos** [Hygieia/Hygieia#2474]
I receive an error message when running  `mvn clean install package` after cloning the repo
Do I need to point the head to a specific tag? 

(Running on MacOS) 

```
Tests in error:
  ApplicationScoreServiceTest.calculateScore:120 » NoSuchMethod org.hamcrest.Mat...
  ApplicationScoreServiceTest.calculateScorePropagateNoScore:197 » NoSuchMethod ...
  ApplicationScoreServiceTest.calculateScorePropagateScore:227 » NoSuchMethod or...
  ApplicationScoreServiceTest.calculateScorePropagateZeroScore:258 » NoSuchMethod
  ApplicationScoreServiceTest.calculateScoreWithCriteriaFail:158 » NoSuchMethod ...
  BuildWidgetScoreTest.calculateScoreNoThresholds:72 » NoSuchMethod org.hamcrest...
  BuildWidgetScoreTest.calculateScoreWithPassThresholds:139 » NoSuchMethod org.h...
  GithubScmWidgetScoreTest.calculateScoreNoThresholds:69 » NoSuchMethod org.hamc...
  GithubScmWidgetScoreTest.calculateScoreWithPassThresholds:123 » NoSuchMethod o...
  QualityWidgetScoreTest.calculateScoreNoThresholds:74 » NoSuchMethod org.hamcre...
  QualityWidgetScoreTest.calculateScoreWithPassThresholds:108 » NoSuchMethod org...

Tests run: 17, Failures: 0, Errors: 11, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia 2.0.5-SNAPSHOT .... SUCCESS [ 10.191 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [01:16 min]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [01:39 min]
[INFO] com.capitalone.dashboard:api-audit ................. SUCCESS [ 27.265 s]
[INFO] com.capitalone.dashboard:rally-collector ........... SUCCESS [  6.998 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  6.026 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  7.337 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  8.539 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  6.557 s]
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SUCCESS [  9.418 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  5.934 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  7.820 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  4.450 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  4.320 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 16.266 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  9.720 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [  6.314 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  1.391 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SUCCESS [  4.465 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [  4.437 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  4.495 s]
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SUCCESS [  5.988 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  2.921 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SUCCESS [  4.647 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SUCCESS [  4.933 s]
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SUCCESS [  4.403 s]
[INFO] com.capitalone.dashboard:score-collector ........... FAILURE [  6.245 s]
[INFO] Hygieia Publisher Plugin 2.1.3-SNAPSHOT ............ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests 2.0.5-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:19 min
[INFO] Finished at: 2018-10-03T19:26:09-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project score-collector: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/vitor.cavalcanti/Projects/Hygieia/collectors/misc/score/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :score-collector
```

**Comment by rvema** [comment]
@vmattos what version of java and mvn are you using?

**Comment by vmattos** [comment]
All my dependencies: 

java 
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

mvn
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T15:33:14-03:00)
```

npm 
```
6.4.1
```

gulp
```
3.9.1
```

mongo
```
MongoDB shell version v4.0.2
```

We also built Hygieia on an ec2 running amazon linux, and it worked without any issues. It seems to be happening only on MacOs

**Comment by bergeronjulien** [comment]
I have the same issue on Windows. Did you find a solution?

**Comment by vmattos** [comment]
@bergeronjulien  No solutions found yet 😢 
I have been using an ec2 running amazon linux to test hygieia

But now I need to automate the deploy and bootstrap of the app on our infra, and it would make my life easier if I could run it on my machine

**Comment by shardulsrivastava** [comment]
@vmattos  a temporary solution would be to skip the tests by modifying your command from `mvn clean install package` to `mvn clean install package -Dmaven.test.skip=true`

btw only `mvn clean install -Dmaven.test.skip=true` should also work, package and install both are not required, install should suffice

**Comment by johndifoolpi** [comment]
```
Tests run: 14, Failures: 0, Errors: 14, Skipped: 0, Time elapsed: 2.636 sec <<< FAILURE! - in com.capitalone.dashboard.collector.DefaultAWSCloudClientTest
getCloudInstances(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.106 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getCloudInstancesEmpty(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getCloudVolumes(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getCloudVolumesEmpty(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

get24HourInstanceEstimatedCharge(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getInstanceCPUSinceLastRun(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getLastHourInstanceNetworkIn(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getLastHourIntanceNetworkOut(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getLastHourInstanceDiskRead(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

getLastInstanceHourDiskWrite(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

canUseFiltersIfDefined(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

ignoresFiltersIfNull(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

regionCanBeSet(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

nullRegionIgnored(com.capitalone.dashboard.collector.DefaultAWSCloudClientTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.getMatcher()Lorg/mockito/ArgumentMatcher;
	at org.powermock.api.mockito.internal.expectation.DefaultLocalizedMatcherAdapter.<init>(DefaultLocalizedMatcherAdapter.java:11)
	at org.powermock.api.mockito.internal.expectation.DefaultConstructorExpectationSetup.getMatcherAdapters(DefaultConstructorExpectationSetup.java:37)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.expectSubstitutionLogic(AbstractConstructorExpectationSetup.java:70)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.createNewSubstituteMock(AbstractConstructorExpectationSetup.java:62)
	at org.powermock.api.mockito.internal.expectation.AbstractConstructorExpectationSetup.withAnyArguments(AbstractConstructorExpectationSetup.java:107)
	at com.capitalone.dashboard.collector.DefaultAWSCloudClientTest.setupTest(DefaultAWSCloudClientTest.java:110)

Running com.capitalone.dashboard.collector.AWSCloudSettingsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.collector.AWSCloudSettingsTest

Results :

Tests in error: 
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...
  DefaultAWSCloudClientTest.setupTest:110 » NoSuchMethod org.mockito.internal.ma...

Tests run: 15, Failures: 0, Errors: 14, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:aws-cloud-collector 3.0.1 . FAILURE [  9.316 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:score-collector ........... SKIPPED
[INFO] Hygieia Publisher Plugin 2.1.5-SNAPSHOT ............ SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests 3.0.1 ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.338 s
[INFO] Finished at: 2018-12-15T10:12:28+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project aws-cloud-collector: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/lorenzo/Develop/capitalone/Hygieia/collectors/cloud/aws/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by Sbrenthughes** [comment]
Is this command line or IDE?

**Comment by john-difool** [comment]
Cli built from HEAD.
