### ISSUE TITLE
Jira Collector for Projects FAILING java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by ndamania** [Hygieia/Hygieia#2476]
We're having an issue where our teams collector works fine but the projects/stories collector throws the following exception:

2018-10-04 15:09:01,557 ERROR o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-3 [ACTIVE(16)] HTTP protocol exception: Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[na:1.8.0_181]
	at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:193) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:171) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:171) ~[httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onInputReady(DefaultHttpClientIODispatch.java:125) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.DefaultHttpClientIODispatch.onInputReady(DefaultHttpClientIODispatch.java:50) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:160) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:320) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) [httpcore-nio-4.2.2.jar!/:4.2.2]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.2.2.jar!/:4.2.2]

When we turn TRACE on, we DO see the response for the projects come back but then right after that there is an exception. 

Now one strange thing we noticed was that the response (JSON), in the trace gets cut off at roughly 7,294 characters. Not sure if that is a trace limitation or some type of limit on how much data can be retrieved. (I would imagine the former).

So this is what we see

(Omitting sensitive information)..
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "Cache-Control: no-cache, no-store, no-transform[\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "X-Content-Type-Options: nosniff[\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "X-Content-Type-Options: nosniff[\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "Referrer-Policy: strict-origin-when-cross-origin[\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "Cache-Control: [0xffffffe2][0xffffff80][0xffffff9c]no-store[0xffffffe2][0xffffff80][0xffffff9d][\r][\n]"
2018-10-04 15:09:01,554 DEBUG org.apache.http.wire - http-outgoing-3 << "Pragma: [0xffffffe2][0xffffff80][0xffffff9c]no-cache[0xffffffe2][0xffffff80][0xffffff9d][\r][\n]"
2018-10-04 15:09:01,555 DEBUG org.apache.http.wire - http-outgoing-3 << "[\r][\n]"
2018-10-04 15:09:01,555 DEBUG org.apache.http.wire - http-outgoing-3 << "1d82[\r][\n]"
2018-10-04 15:09:01,555 DEBUG org.apache.http.wire - http-outgoing-3 << "[{"expand":"description,lead,url,projectKeys","self":"https://jira...............(7,294 characters worth of data).

**Comment by ndamania** [comment]
Is no one else having this issue with newer versions of JIRA?

**Comment by shishirchaturvedi** [comment]
@ndamania Which JIRA version are you using?

**Comment by Sbrenthughes** [comment]
@ndamania @shishirchaturvedi - Please refer to #2667. As this is the collector rewrite in progress
