### ISSUE TITLE
SVN Collector unable to select Repo type while configuring Repo widget

### ISSUE THREAD

**Issue by MilindDivre** [Hygieia/Hygieia#2533]
I am able to get below logs  when i run svn collector 
2018-10-26 10:50:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Subversion
2018-10-26 10:50:00,051 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:451}] to localhost:27017
2018-10-26 10:50:00,066 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-10-26 10:50:00,066 INFO  c.c.d.collector.CollectorTask - Starting...
2018-10-26 10:50:00,066 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-10-26 10:50:00,161 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2018-10-26 10:50:00,162 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-10-26 10:50:00,162 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-10-26 10:51:28,709 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:6, serverValue:451}] to localhost:27017 because it is past its maximum allowed idle time.

But  when i try to configure it on UI  i even cannot select the repo type
![image](https://user-images.githubusercontent.com/11345065/47546319-55f9bd80-d90e-11e8-8d92-5f61bd42c363.png)

below are my dbs in mongo:
> show dbs
admin        0.000GB
config       0.000GB
dashboarddb  0.001GB
local        0.000GB

i can see some data in collectors 
> use dashboarddb
switched to db dashboarddb
> db.collectors.find()
{ "_id" : ObjectId("5bbeeb909c627c0d3829d217"), "_class" : "com.capitalone.dashboard.model.HudsonCollector", "buildServers" : [ "http://135.123.148.138:8080" ], "niceNames" : [ ], "environments" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "jobName" : "", "jobUrl" : "" }, "allFields" : { "jobName" : "", "jobUrl" : "", "instanceUrl" : "" }, "lastExecuted" : NumberLong("1540527529326"), "searchFields" : [ "options.jobName", "niceName" ] }
{ "_id" : ObjectId("5bc6ddf09c627c0a09587441"), "_class" : "com.capitalone.dashboard.collector.AWSCloudCollector", "name" : "AWSCloud", "collectorType" : "Cloud", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : {  }, "allFields" : {  }, "lastExecuted" : NumberLong("1539759600044"), "searchFields" : [ "description" ] }
{ "_id" : ObjectId("5bc710549c627c177919ea29"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Subversion", "collectorType" : "SCM", "enabled" : true, "online" : true, "errors" : [ ], "uniqueFields" : { "url" : "" }, "allFields" : { "rev" : "", "url" : "" }, "lastExecuted" : NumberLong("1540529100046"), "searchFields" : [ "description" ] }
{ "_id" : ObjectId("5bc71a099c627c1c3acc50f9"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Product", "collectorType" : "Product", "enabled" : true, "online" : true, "errors" : [ ], "uniqueFields" : {  }, "allFields" : {  }, "lastExecuted" : NumberLong(0), "searchFields" : [ "description" ] }
{ "_id" : ObjectId("5bced0509c627c1c282ee090"), "_class" : "com.capitalone.dashboard.model.SonarCollector", "sonarServers" : [ "http://sonar.forge.avaya.com" ], "sonarVersions" : [ 6.31 ], "sonarMetrics" : [ "ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details" ], "name" : "Sonar", "collectorType" : "CodeQuality", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "projectName" : "", "instanceUrl" : "" }, "allFields" : { "projectName" : "", "projectId" : "", "instanceUrl" : "" }, "lastExecuted" : NumberLong("1540281358167"), "searchFields" : [ "description" ] }
{ "_id" : ObjectId("5bced3d49c627c1d31a69781"), "_class" : "com.capitalone.dashboard.model.FeatureCollector", "name" : "GitlabFeature", "collectorType" : "AgileTool", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : {  }, "allFields" : {  }, "lastExecuted" : NumberLong("1540281360038"), "searchFields" : [ "description" ] }
{ "_id" : ObjectId("5bcefbac9c627c24c6ae5507"), "_class" : "com.capitalone.dashboard.model.BambooCollector", "buildServers" : [ "http://bamboo.forge.avaya.com/browse/CRMBREEZE" ], "niceNames" : [ ], "name" : "Bamboo", "collectorType" : "Build", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "jobName" : "", "jobUrl" : "", "instanceUrl" : "" }, "allFields" : { "jobName" : "", "jobUrl" : "", "instanceUrl" : "" }, "lastExecuted" : NumberLong("1540296300530"), "searchFields" : [ "description" ] }
 But not able to configure repo widget

**Comment by Sbrenthughes** [comment]
@MilindDivre any update ?

**Comment by MilindDivre** [comment]
Yeah its pointing to same db: below is the properties file which i am using
dbname=dashboarddb
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
dbhostport=127.0.0.1:27017
server.contextPath=/api
server.port=8080
# Database Username - default is blank
dbusername=dashboarduser
# Database Password - default is blank
dbpassword=dbpassword

**Comment by MilindDivre** [comment]
I did had look #2465 before raising :) .. but here i same db used here for API as well as for SVN collector

**Comment by Sbrenthughes** [comment]
Can you try doing http://localhost:8080api/collector/type/scm

**Comment by MilindDivre** [comment]
http://localhost:8080/api/collector/type/scm-- gives nothing

after changing the properties file , now i can see subversion in dropdown. but i get no data
![image](https://user-images.githubusercontent.com/11345065/47853632-58c04b00-de05-11e8-9d12-4b964d17488c.png)
i get this error on console
2018-11-01 18:40:00,048 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:1017}] to 127.0.0.1:27017
2018-11-01 18:40:00,061 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-11-01 18:40:00,061 INFO  c.c.d.collector.CollectorTask - Starting...
2018-11-01 18:40:00,061 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-11-01 18:40:01,950 ERROR c.c.d.c.DefaultSubversionClient - Subversion repo: https://****/****/****/
org.tmatesoft.svn.core.SVNAuthenticationException: svn: E170001: Authentication required for '<https://******:443> 
        at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:47) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:41) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.wc.DefaultSVNAuthenticationManager.getFirstAuthentication(DefaultSVNAuthenticationManager.java:186) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:693) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:375) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:363) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:710) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.exchangeCapabilities(DAVConnection.java:627) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.open(DAVConnection.java:102) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.openConnection(DAVRepository.java:1032) ~[svnkit-1.8.7.jar!/:na]
        at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.getDatedRevision(DAVRepository.java:191) ~[svnkit-1.8.7.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultSubversionClient.getRevisionClosestTo(DefaultSubversionClient.java:59) ~[subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SubversionCollectorTask.startRevision(SubversionCollectorTask.java:155) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.SubversionCollectorTask.collect(SubversionCollectorTask.java:130) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-11-01 18:40:02,865 INFO  c.c.d.collector.CollectorTask - Repo Count              1        2s
2018-11-01 18:40:02,866 INFO  c.c.d.collector.CollectorTask - New Commits             0        2s
2018-11-01 18:40:02,866 INFO  c.c.d.collector.CollectorTask - Finished                         2s
^C2018-11-01 18:40:23,475 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3dae8564: startup date [Thu Nov 01 18:36:49 IST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@5a7c80b9
i think this is authentication issue but, i have provided valid credentials in properties file. can you please tell me how can i provide credentials

#And i got the reason why dashboard in populating ..
whenever i run jira collector it creates dashboard db..can you please suggest why?

**Comment by Sbrenthughes** [comment]
I am not familiar enough with the jira collector to know. Can you paste your subversion collector properties?

**Comment by MilindDivre** [comment]
#Database Name
spring.data.mongodb.database=

#Database HostName - default is localhost
spring.data.mongodb.host=localhost

#Database Port - default is 27017
spring.data.mongodb.port=27017

#Database Username - default is blank
spring.data.mongodb.username=d

#Database Password - default is blank
spring.data.mongodb.password=

dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=dashboarduser
dbpassword=dbpassword

#Collector schedule (required)
subversion.cron=0 0/5 * * * *

#Shared subversion username and password
subversion.username=*****
subversion.password=*****

#Maximum number of days to go back in time when fetching commits
subversion.commitThresholdDays=15

**Comment by MilindDivre** [comment]
same error

**Comment by Sbrenthughes** [comment]
Try no auth
```
subversion.username=
subversion.password=
```

**Comment by MilindDivre** [comment]
same error
 at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:47) ~[svnkit-1.8.7.jar!/:na]

**Comment by Sbrenthughes** [comment]
At this point it is a credentials issue.

**Comment by Sbrenthughes** [comment]
Did you get this resolved?

**Comment by diwakarjhanwar** [comment]
No its not resolved

org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:47) ~[svnkit-1.8.7.jar!/:na]

**Comment by rvema** [comment]
@diwakarjhanwar please open an issue against subversion collector repo
