### ISSUE TITLE
 Client exception loading jobs

### ISSUE THREAD

**Issue by kjaeswar76** [Hygieia/Hygieia#2553]
I am trying to configure the Hygieia widget for Bamboo, the list of jobs is not getting shown. On the bamboo collector console following is the exception which is shown:

2018-11-02 18:27:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Bamboo
2018-11-02 18:27:00,094 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-11-02 18:27:00,112 INFO  c.c.d.collector.CollectorTask - https://username:APIKEY@mybamboo.company.com
2018-11-02 18:27:00,118 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-11-02 18:27:05,469 ERROR c.c.d.collector.DefaultBambooClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultBambooClient.makeRestCall(DefaultBambooClient.java:381) ~[bamboo-build-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.DefaultBambooClient.getInstanceJobs(DefaultBambooClient.java:67) ~[bamboo-build-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.BambooCollectorTask.collect(BambooCollectorTask.java:94) [bamboo-build-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.BambooCollectorTask.collect(BambooCollectorTask.java:34) [bamboo-build-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.1.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]

In the url https://username:APIKEY@mybamboo.company.com userName is the bamboo user name and APIKEY is the one which is set in api.properties. 

Following is the application.properties for the bamboo collector

                # Database Name
		dbname=dashboarddb

		# Database HostName - default is localhost
		dbhost=localhost

		# Database Port - default is 27017
		dbport=27017

		# MongoDB replicaset
		# [false if you are not using MongoDB replicaset]
		dbreplicaset= false

		# Database Username - default is blank
		dbusername=test

		# Database Password - default is blank
		dbpassword=test

		# Collector schedule (required)
		bamboo.cron=0 0/1 * * * *

		# Jenkins server (required) - Can provide multiple
		bamboo.servers[0]=https://username:APIKEY@mybamboo.company.com

		# If using username/token for API authentication
		# (required for Cloudbees Jenkins Ops Center) see sample
		#bamboo.servers[1]=https://username:APIKEY@mybamboo.company.com

		# Determines if build console log is collected - defaults to false
		# (Bamboo for some reason has not exposed it as an API)
		bamboo.saveLog=false

Can you please help out in identifying what is being done wrong here? If you need any additional information, do let me know

**Comment by kjaeswar76** [comment]
The APIKEY used is the one in the API.properties. Is that the right one to use?

**Comment by Sbrenthughes** [comment]
The APIKEY you are referring to is the one that you would get from Bamboo to Access it's APIs. The key in the API properties is for use in Hygieia.

**Comment by kjaeswar76** [comment]
Thanks @Sbrenthughes . In my case, it started working when I gave the password of the user instead of the API key from the API properties file.

Also I set the 
bamboo.username=<userName>
bamboo.apiKey=<Password>

and made this entry
# Jenkins server (required) - Can provide multiple
bamboo.servers[0]=https://username:APIKEY@mybamboo.company.com

as 

# Jenkins server (required) - Can provide multiple
bamboo.servers[0]=https://mybamboo.company.com

It started working like a charm after that..

**Comment by Sbrenthughes** [comment]
Awesome!
