### ISSUE TITLE
Jenkins DeployPublishStep throwing NPE

### ISSUE THREAD

**Issue by etsauer** [Hygieia/Hygieia#2619]
I have the following in a pipeline:

```
hygieiaDeployPublishStep buildStatus: 'Success'
```

I've tried several different permutations of passing different parameters to it, but it seems this is the most minimal required version. Each time, I get the following when I run the pipeline.

```
[Pipeline] hygieiaDeployPublishStep
Publishing data for API http://api-service.hygieia-esauer.svc.cluster.local:8080/api/
Hygieia: Published Build Data For Deployment Publishing. Response Code: 201. Response Value= 5c06e50cca26bf000108cfe2,5c06aafbb1f2b700018a2a23
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Prod)
Stage 'Promote to Prod' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at hygieia.builder.DeployBuilder.<init>(DeployBuilder.java:67)
	at jenkins.plugins.hygieia.workflow.HygieiaDeployPublishStep$HygieiaDeployPublishStepExecution.run(HygieiaDeployPublishStep.java:218)
	at jenkins.plugins.hygieia.workflow.HygieiaDeployPublishStep$HygieiaDeployPublishStepExecution.run(HygieiaDeployPublishStep.java:164)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

Just as a sanity check, there is a BuildPublishStep earlier in the pipeline that is working just fine.

**Comment by Sbrenthughes** [comment]
Looks like you are using an update version of the plugin. You should not need the hygieiaDeployPublishStep step.

**Comment by etsauer** [comment]
No, unless I have those steps in the plugin, I do not get any deploy data. Without specifying those steps, how would hygieia find my "application name"?

**Comment by etsauer** [comment]
I've been able to get the deployStep to work, but only by passing all parameters. Currently I have a single pipeline that deploys across 3 environments, Dev, Stage, Prod. I have a stage defined in my pipeline, each of which contains a `post` block which reports back to Hygieia

```
                post {
                  success {
                    hygieiaDeployPublishStep applicationName: "${APP_NAME}", artifactDirectory: 'dist/', artifactGroup: 'uncontained.io', artifactName: 'index.html', artifactVersion: "${BUILD_NUMBER}-${dev_namespace}", buildStatus: 'Success', environmentName: "${dev_namespace}"
                  }
                }
```

This works, but if you think that there is a better way, I would love to hear it,

**Comment by Sbrenthughes** [comment]
Actually, I had the steps confused. Yes for pushing the artifact information, all the params are required

**Comment by etsauer** [comment]
Yes, we can.
