### ISSUE TITLE
Bamboo Collector - Certificate Error

### ISSUE THREAD

**Issue by udiakasnuke** [Hygieia/Hygieia#2630]
This is my application.properties file -- 
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=dashboarduser
dbpassword=dashboarduser123
dbreplicaset=false
bamboo.savelog=false
bamboo.cron=0 0/5 * * * *
bamboo.servers[0]=https://bamboo.company.com // full URL to my company name
bamboo.username=my_bamboo_username
bamboo.apiKey=my_bamboo_password

I am getting the following error

2018-12-11 18:07:05,079 INFO  com.capitalone.dashboard.Application - Started Application in 7.409 seconds (JVM running for 8.341)
2018-12-11 18:09:01,355 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:189}] to localhost:27017 because it is past its maximum allowed idle time.
2018-12-11 18:10:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Bamboo
2018-12-11 18:10:00,031 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:197}] to localhost:27017
2018-12-11 18:10:00,064 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-12-11 18:10:00,064 INFO  c.c.d.collector.CollectorTask - https://bamboo.forge.company.com
2018-12-11 18:10:00,064 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-12-11 18:10:01,198 ERROR c.c.d.collector.DefaultBambooClient - client exception loading jobs
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://bamboo.forge.company.com/rest/api/latest/plan?expand=plans&max-result=2000": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBambooClient.makeRestCall(DefaultBambooClient.java:381) ~[bamboo-build-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.DefaultBambooClient.getInstanceJobs(DefaultBambooClient.java:67) ~[bamboo-build-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.BambooCollectorTask.collect(BambooCollectorTask.java:94) [bamboo-build-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.BambooCollectorTask.collect(BambooCollectorTask.java:34) [bamboo-build-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959) ~[na:1.8.0_161]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328) ~[na:1.8.0_161]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[na:1.8.0_161]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[na:1.8.0_161]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_161]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[na:1.8.0_161]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[na:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[na:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[na:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[na:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[na:1.8.0_161]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_161]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_161]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[na:1.8.0_161]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 16 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[na:1.8.0_161]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[na:1.8.0_161]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_161]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_161]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_161]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_161]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[na:1.8.0_161]
	... 30 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_161]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_161]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_161]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[na:1.8.0_161]
	... 36 common frames omitted

Looks like some certificate issue to me, but i am not able to make out.

Any help would be greatly appreciated!!

**Comment by rvema** [comment]
please ensure that the certificates for your bamboo collector are imported into cacerts part of your jdk off which you are launching the collector.

**Comment by udiakasnuke** [comment]
Yes... i added certificate in cacerts and it works fine now....This can be closed now... but @rvema can u tell me how to add widgets to UI... I can run my api module.. i can run the UI.. i can even run my bamboo collector.. but how to show that to Hygieia dashboard.. 

Thanks!! help is greatly appreciated!!
