### ISSUE TITLE
getting error "no such cmd: saslStart" while launching API

### ISSUE THREAD

**Issue by ansha1** [Hygieia/Hygieia#2638]
Caused by: com.mongodb.MongoCommandException: Command failed with error -1: 'no such cmd: saslStart' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "no such cmd: saslStart", "bad cmd" : { "saslStart" : 1, "mechanism" : "SCRAM-SHA-1", "payload" : { "$binary" : "biwsbj1tb25nbyxyPW5cKD1BbEByMDx5OyY2USQvdE0/e3hXSA==", "$type" : "0" } } }
	at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar!/:na]
	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar!/:na]
	... 5 common frames omitted
=--------------------------------------
api.properties file 
===============
#api.properties
dbname=admin
dbusername=anurag
dbpassword=anurag
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false

#dbhostport=localhost:27017,127.0.0.1,10.132.210.81:27017
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false

**Comment by Sbrenthughes** [comment]
You probably shouldn’t be connecting to the admin database. Did the documentation say that somewhere ?

**Comment by Sbrenthughes** [comment]
Also, what version of mongo are you using?

**Comment by Sbrenthughes** [comment]
You could also try looking at https://github.com/Hygieia/Hygieia/issues/478, https://github.com/Hygieia/Hygieia/issues/2336, or https://github.com/Hygieia/Hygieia/issues/2414

**Comment by Sbrenthughes** [comment]
If it’s not 3.0 or above, that’s the problem.

**Comment by dgrierso** [comment]
Suggest that this should be re-opened and appropriate content in the documentation updated to reflect the requirement for MongoDB >= 3.0

**Comment by Sbrenthughes** [comment]
@dgrierso Can you make a PR to the gh-pages branch with the doc change?
