### ISSUE TITLE
Jira data is not collected

### ISSUE THREAD

**Issue by ksrivalli41** [Hygieia/Hygieia#2642]
Below error ids displayed while running jira collector

2018-12-19 15:13:00,110 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-12-19 15:14:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-12-19 15:14:00,022 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-12-19 15:14:00,026 INFO  c.c.d.collector.CollectorTask - http://localhost:8090/
2018-12-19 15:14:00,027 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-12-19 15:14:00,027 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2018-12-19 15:14:00,077 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(403), errorCollections=[]}
2018-12-19 15:14:00,079 INFO  c.c.d.collector.CollectorTask - Project Data            0        0s
2018-12-19 15:14:00,101 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8090/rest/api/2/status/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_181]
        at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_181]
        at com.capitalone.dashboard.client.DefaultJiraClient.getStatusMapping(DefaultJiraClient.java:442) ~[jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStatuses(StoryDataClientImpl.java:779) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:156) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:1) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.1.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]

can someone resolve  it?

**Comment by rvema** [comment]
Can you share the properties file used to launch the jira collector?

**Comment by ksrivalli41** [comment]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=9.195.178.201

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=9.195.178.201:27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dashboarduser123

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=http://localhost:8090/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=a3BhbGFrbzE6UGFzc3dvcmQxIA0K

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10000

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10005

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=false

###############################################################################
#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=OPEN
feature.doingStatuses[0]=IN PROGRESS
feature.doingStatuses[1]=TEST
feature.doingStatuses[2]=TESTING
feature.doneStatuses[0]=DONE
feature.doneStatuses[1]=CLOSED

**Comment by Sbrenthughes** [comment]
We are working on a jira collector rewrite here https://github.com/Hygieia/Hygieia/issues/2667. Please use this and let us know if you any issues.
