### ISSUE TITLE
Mongo DB exception while configuring appdynamics collector

### ISSUE THREAD

**Issue by jaikumarmansukhani** [Hygieia/Hygieia#2643]
Hi,

I am working on setting the appdynamics collector for Hygieia and getting below error.

please note api was running successfully with same config.

Can someone please review and advise.

application.properties ::>> 
database=dashboarddb

#Database HostName - default is localhost
dbhost=127.0.0.1
#dbhost=localhost

#Database Port - default is 27017
dbport=27017
#dbreplicaset=false
#dbhostport=127.0.0.1:27017

#Database Username - default is blank
dbusername=dashboarduser

#Database Password - default is blank
dbpassword=dbpassword
auth.expirationTime=50000
auth.secret=XXXXXXXXXXXXXXXXXXXXXXXX
auth.authenticationProviders=STANDARD

#Logging File
logging.file=./logs/appd-collector.log

#Collector schedule (required)
appdynamics.cron=1 * * * * *

#AppDynamics server (required)
appdynamics.instanceUrl=https://XXX.saas.appdynamics.com

#AppDynamics Username (required)
appdynamics.username=XXX (if multi-tenancy, then APPD_USERNAME@TENANT)

#AppDynamics Password (required)
appdynamics.password=XXX

#AppDynamics Dashboard (required)
appdynamics.dashboardUrl=

Error ::>>
at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar!/:na]
        ... 5 common frames omitted
2018-12-20 01:31:22,488 INFO  org.mongodb.driver.cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]}. Waiting for 30000 ms before timing out
2018-12-20 01:31:52,489 WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appdynamicsCollectorTask': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='dashboarduser', source='dashboard', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]

**Comment by jaikumarmansukhani** [comment]
Can someone look into this please and help

**Comment by Sbrenthughes** [comment]
For local testing can you do the following and try again
```
#Database Username - default is blank
#dbusername=dashboarduser

#Database Password - default is blank
#dbpassword=dbpassword
```

**Comment by Sbrenthughes** [comment]
@jaikumarmansukhani any update here?

**Comment by rvema** [comment]
Closing the issue due to inactivirty
