### ISSUE TITLE
Jira Collector throwing error

### ISSUE THREAD

**Issue by udiakasnuke** [Hygieia/Hygieia#2664]
I am running my jira collector but getting the following exception

2019-01-09 16:24:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-01-09 16:24:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-09 16:24:00,006 INFO  c.c.d.collector.CollectorTask - https://jira.xxx.com/
2019-01-09 16:24:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-09 16:24:02,442 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.xxxcom/rest/tempo-teams/1/team
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[na:1.8.0_161]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_161]
	at java.net.URLConnection.getContent(URLConnection.java:739) ~[na:1.8.0_161]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:443) ~[na:1.8.0_161]
	at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:284) ~[jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:64) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0-SNAPSHOT.jar!/:3.0.1]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2019-01-09 16:24:02,442 INFO  c.c.d.collector.CollectorTask - Team Data               0        2s
2019-01-09 16:24:05,279 INFO  c.c.d.collector.CollectorTask - Project Data           48        2s
2019-01-09 16:24:08,806 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 0
2019-01-09 16:24:08,806 INFO  c.c.d.collector.CollectorTask - Story Data              0        3s
2019-01-09 16:24:08,806 INFO  c.c.d.collector.CollectorTask - Finished     

Any help is deeply appreciated!!

**Comment by udiakasnuke** [comment]
My properties file -

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
# dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dashboarduser123

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=50

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2018-05-01T00:00:00.000000
feature.masterStartDate=2018-05-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2018-05-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
# feature.jiraProxyUrl=http://proxy.com
# feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://jira.xxx.com/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=ZnR4OldpblN0YXJ0MjAxNw==

# OAuth is not fully implemented; please blank-out the OAuth values:

# feature.jiraOauthAuthtoken=
# feature.jiraOauthRefreshtoken=
#		feature.jiraOauthRedirecturi=
#		feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_11670

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_12973

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10010

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_15870

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=false

**Comment by udiakasnuke** [comment]
I think there is some problem with jiraTeamFieldName and jiraBoardAsTeam fields... but to my knowledge i have set them correctly... We don't use boardsas team so i set that to false...and I get the value of 15870 whrn i check the 'Team' ..

Please help @Sbrenthughes  .. Thanks!!

**Comment by Sbrenthughes** [comment]
@udiakasnuke We are in the testing phase of a rewrite for the Jira collector. Stay tuned.

**Comment by tabladrum** [comment]
Two options: 
immediately: set the last boolean property "feature.jiraBoardAsTeam=true"
coming up soon: a complete rewrite of the collector to account for data correctness, performance - you can take a look at my fork: https://github.com/tabladrum/Hygieia/tree/master/collectors/feature/jira 
You also need to locally clone and "mvn clean install" on hygieia-core from my fork - https://github.com/tabladrum/hygieia-core

**Comment by Sbrenthughes** [comment]
Please refer to the above comment and if you face issues follow up here #2667.

**Comment by nsaud01** [comment]
@tabladrum Upon running your forked Jira collector, I'm running into an error I was hoping you could clarify.

````
2019-01-28 20:59:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-01-28 20:59:00,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-28 20:59:00,024 INFO  c.c.d.collector.CollectorTask - https://acme.atlassian.net
2019-01-28 20:59:00,025 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-28 20:59:00,025 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-01-28 20:59:00,025 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 430196. Collector is about to refresh Team/Board information
2019-01-28 20:59:00,454 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
org.springframework.web.client.HttpClientErrorException: 404 null
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:777) ~[jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getTeams(DefaultJiraClient.java:220) ~[jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateTeamInformation(FeatureCollectorTask.java:158) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:130) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:41) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0-SNAPSHOT.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
````

Here is my application.properties file:
````
#Database Name
dbname=hygieia

#Database HostName - default is localhost
dbhost=mongodb

#Database Port - default is 27017
dbport=27017


#Database Username - default is blank
dbusername=hygieia

#Database Password - default is blank
dbpassword=bewnscot70

#Collector schedule (required)
feature.cron=0 * * * * *

#Page size for data calls (Jira maxes at 1000)
feature.pageSize=100

#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

#Jira Connection Details
feature.jiraProxyUrl=
feature.jiraProxyPort=

# Trending Query:  Number of days in a sprint (not-required)
feature.sprintDays=60

# Trending Query:  Length of sprint week (not-required)
feature.sprintEndPrior=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
feature.scheduledPriorMin=2

#Delta change date that modulates the collector item task - should be about as far back as possible, in ISO format (required)
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000

#Jira Connection Details
feature.jiraBaseUrl=https://sandcsw.atlassian.net
feature.jiraQueryEndpoint=rest/api/2/

#64-bit encoded credentials with the pattern username:password
#on a mac you con create them with : echo "username:password" | base64
#reference:  https://www.base64decode.org/
feature.jiraCredentials=TmFqZWViLlNhdWRAc2FuZGMuY29tOnpFaGRWSVU5T2VobGN1M1Vmclh5RjIxMA==

#OAuth2.0 token credentials (currently not supported in this version)
feature.jiraOauthAuthtoken=sdfghjkl==
feature.jiraOauthRefreshtoken=sdfagheh==
feature.jiraOauthRedirecturi=uri.this.is.test:uri
feature.jiraOauthExpiretime=234567890987

#Start dates from which to begin collector data, if no other data is present - usually, a month back is appropriate (required)
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000

# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a String Name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
feature.jiraIssueTypeNames=Story

# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10007

# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10201

# In Jira, your instance will have its own custom field created for "story points"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraStoryPointsFieldName=customfield_10004

# In Jira, your instance will have its own custom field created for "team"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraTeamFieldName=customfield_12100

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=false
````

**Comment by RameshMuthuraj** [comment]
me too having the same issue.. please help!!

2019-03-11 07:42:56,941 INFO  com.capitalone.dashboard.Application - Started Application in 6.989 seconds (JVM running for 7.743)
2019-03-11 07:43:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-03-11 07:43:00,023 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-11 07:43:00,024 INFO  c.c.d.collector.CollectorTask - https://jira.tools/
2019-03-11 07:43:00,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-11 07:43:00,241 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-03-11 07:43:00,241 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 431191. Collector is about to refresh Team/Board information
2019-03-11 07:43:00,604 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
org.springframework.web.client.HttpClientErrorException: 404 null
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:783) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getTeams(DefaultJiraClient.java:218) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateTeamInformation(FeatureCollectorTask.java:170) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:137) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:46) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java

**Comment by Sbrenthughes** [comment]
@RameshMuthuraj typically closed issues don't get looked at I would suggest looking at https://github.com/Hygieia/Hygieia/issues/2667

**Comment by shekharshamra** [comment]
HI All,

I am getting the same issue. anyone has any idea how to resolve it.
2019-10-11 04:37:00,184 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 401 null
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
