### ISSUE TITLE
Urgent:  Appdynamics

### ISSUE THREAD

**Issue by anayyadav** [Hygieia/Hygieia#2666]
Hi friends,

I am trying to configure performance widget fro AppD in Hygieia.

Properties file:

#Database Name
database=dashboard

#Database HostName - default is localhost
dbhost=localhost

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=

#Database Password - default is blank
dbpassword=

#Logging File
logging.file=./logs/appd-collector.log

#Collector schedule (required)
appdynamics.cron=0 0/1 * * * *

#AppDynamics server (required)
appdynamics.instanceUrls=https://xyz-test.saas.appdynamics.com

#AppDynamics Username (required)
appdynamics.username=abc@xyz-test

#AppDynamics Password (required)
appdynamics.password=abc

#AppDynamics Dashboard (required)
appdynamics.dashboardUrl=https://xyz-test.saas.appdynamics.com/controller/#/location=APPS_ALL_DASHBOARD&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60

Error: 
2019-01-10 10:33:00,005 INFO  c.c.d.collector.CollectorTask - Running Collector: Appdynamics
2019-01-10 10:33:00,039 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-10 10:33:00,039 INFO  c.c.d.collector.CollectorTask - Instance 0: https://xyz-test.saas.appdynamics.com
2019-01-10 10:33:00,039 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-10 10:33:00,586 WARN  o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: visid_incap_968114=p4nd2+0IQPqMZzGtq8KYIiIfN1wAAAAAQUIPAAAAAABgMhQtT7H1wFRDUxqm2sat; expires=Fri, 10 Jan 2020 07:23:48 GMT; path=/; Domain=.saas.appdynamics.com". Invalid 'expires' attribute: Fri, 10 Jan 2020 07:23:48 GMT
2019-01-10 10:33:00,588 INFO  c.c.d.collector.CollectorTask - Fetched applications   1         0s
2019-01-10 10:33:00,589 INFO  c.c.d.collector.CollectorTask - New appplications:      0        0s
2019-01-10 10:33:00,818 WARN  o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: visid_incap_968114=p4nd2+0IQPqMZzGtq8KYIiIfN1wAAAAAQUIPAAAAAABgMhQtT7H1wFRDUxqm2sat; expires=Fri, 10 Jan 2020 07:23:48 GMT; path=/; Domain=.saas.appdynamics.com". Invalid 'expires' attribute: Fri, 10 Jan 2020 07:23:48 GMT
2019-01-10 10:33:00,861 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 400 Invalid application id 309 is specified
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:418) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getOverallMetrics(DefaultAppdynamicsClient.java:154) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.getPerformanceMetrics(DefaultAppdynamicsClient.java:135) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.refreshData(AppdynamicsCollectorTask.java:101) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:86) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.AppdynamicsCollectorTask.collect(AppdynamicsCollectorTask.java:20) ~[appdynamics-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]

Please share your ideas to resolve this issue.

**Comment by Sbrenthughes** [comment]
` Invalid 'expires' `. Can you do some research and see if the header requirements have changed and try making that update? If that works can you provide a PR back?

**Comment by anayyadav** [comment]
The same collector is working for on-premise Appdynamics server but now I am configuring for saas Appdynamics.

**Comment by Sbrenthughes** [comment]
So the only difference is one is on prem and one is in the cloud?

**Comment by anayyadav** [comment]
yes, and one more thing the application whose id is 309 does not exist in my server. So how is this error coming.

**Comment by anayyadav** [comment]
@tabladrum , Can you please tell me our the root cause of above error which I am getting in AppD (Saas).
