### ISSUE TITLE
hygieia jenkins plugin cannot match the latest SonarQube domain

### ISSUE THREAD

**Issue by lyndomiao** [Hygieia/Hygieia#2680]
the latest sonarqube api of project url is "http://127.0.0.1:9000/dashboard?id=app",while the hygieia jenkins plugin cannot match the sonarqube domian,and throws an exception.
`INFO: ANALYSIS SUCCESSFUL, you can browse http://127.0.0.1:9000/dashboard?id=app`
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at hygieia.builder.SonarBuilder.setSonarDetails(SonarBuilder.java:116)
	at hygieia.builder.SonarBuilder.getSonarMetrics(SonarBuilder.java:215)
	at jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution.run(HygieiaSonarPublishStep.java:129)
	at jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution.run(HygieiaSonarPublishStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lyndomiao** [comment]
in the source code ,the match domain method is 
` this.sonarServer = sonarBuildLink.substring(0, sonarBuildLink.indexOf("/dashboard/index/" + this.sonarProjectName));`

**Comment by rvema** [comment]
What version of the plugin are you seeing this issue?

**Comment by lyndomiao** [comment]
@rvema Hygieia 3.0.1 Release

**Comment by rvema** [comment]
On the Jenkins job console output, can you search for the hygieia Jenkins plugin version and update the issue?

**Comment by rvema** [comment]
@lyndomiao Can you provide the above information?

**Comment by rvema** [comment]
@lyndomiao Can you get the latest code from Hygieia and retry? Please reopen this issue in case you run into issues.

**Comment by rvema** [comment]
@lyndomiao I think you are using sonar version 7. This plugin currently supports up to v 6.7.x
