### ISSUE TITLE
Parse exception while running sonar collector

### ISSUE THREAD

**Issue by Sharmakartik** [Hygieia/Hygieia#2682]

**Comment by Sharmakartik** [comment]
properties file of sonar
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false 
sonar.cron=0 0/5 * * * *
# Sonar server(s) (required) - Can provide multiple
sonar.servers[0]=http://localhost:9000	
# Sonar version, match array index to the server. If not set, will default to version prior to 6.3.
sonar.versions[0]=6.7
# For Sonar version 6.3 and above
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details
# Sonar login credentials
sonar.username=admin
sonar.password=admin

**Comment by Sharmakartik** [comment]
this is coming in CMD while running sonar collector

Sbrenthughes @Sbrenthughes Jan 21 20:59
Just realized I helped you on the issue.
Feel free to reach out to me here if you have anymore questions

Sharmakartik @Sharmakartik Jan 21 21:10
thanks

Sbrenthughes @Sbrenthughes Jan 21 21:11
So has you project in sonar done a scan yet?

Sharmakartik @Sharmakartik Jan 21 21:11
yes
pls let me know how to configure
with sonarqube

Sbrenthughes @Sbrenthughes Jan 21 21:12
Sorry, I can't help you configure a sonar project. I only know how to setup hygieia.

Sharmakartik @Sharmakartik Jan 21 21:13
what should i fill in codeanalysis section

Sbrenthughes @Sbrenthughes Jan 21 21:13
It is where sonar data would be put

Sharmakartik @Sharmakartik Jan 21 21:13
coz their is no job in that section

Sbrenthughes @Sbrenthughes Jan 21 21:14
Right, you need to configure your sonarqube to work
and then run the collector. Once your project is sonarqube is configured and a scan is ran, you will see it pull in the collector.

Sharmakartik @Sharmakartik Jan 21 21:14
i have done all these things
Could not parse response from: http://localhost:9000 /api/qualityprofiles/search

Sbrenthughes @Sbrenthughes Jan 21 21:16
A scan has been ran in sonarqube?
Can you paste that whole log
How are you running the API and sonar on the same port?

Sharmakartik @Sharmakartik Jan 21 21:17
no
api is on 8080
sonar is on 9000

Sbrenthughes @Sbrenthughes Jan 21 21:18
Could not parse response from: http://localhost:9000 /api/qualityprofiles/search
means you have an issue with Sonar

Sharmakartik @Sharmakartik Jan 21 21:19
will check
give me some time

Sbrenthughes @Sbrenthughes Jan 21 21:19
But actually, you have a space in your url you posted above. try http://localhost:9000/api/qualityprofiles/search

Sharmakartik @Sharmakartik Jan 21 21:19
yes
their is a space
org.json.simple.parser.ParseException: null

Sbrenthughes @Sbrenthughes Jan 21 21:21
Are your getting this error from the collector?
http://localhost:9000/api/qualityprofiles/search paste this into your browser

Sharmakartik @Sharmakartik Jan 21 21:21
2019-01-21 15:48:44,463 INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:31}] to 127.0.0.1:27017
2019-01-21 15:48:44,487 INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 9]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=22674100}
2019-01-21 15:48:44,919 INFO o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2019-01-21 15:48:44,929 INFO o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-01-21 15:48:44,932 INFO o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-01-21 15:48:44,933 INFO o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-01-21 15:48:44,936 INFO o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-01-21 15:48:44,956 INFO o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-01-21 15:48:44,991 INFO o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=c890e7f,type=ConfigurationPropertiesRebinder]
2019-01-21 15:48:45,059 INFO com.capitalone.dashboard.Application - Started Application in 11.021 seconds (JVM running for 12.691)
2019-01-21 15:50:00,018 INFO c.c.d.collector.CollectorTask - Running Collector: Sonar
2019-01-21 15:50:00,021 INFO org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:28}] to 127.0.0.1:27017 because it is past its maximum allowed idle time.
2019-01-21 15:50:00,040 INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:32}] to 127.0.0.1:27017
2019-01-21 15:50:00,085 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-01-21 15:50:00,086 INFO c.c.d.collector.CollectorTask - http://localhost:9000
2019-01-21 15:50:00,086 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-01-21 15:50:00,214 ERROR c.c.d.collector.DefaultSonar6Client - Could not parse response from: http://localhost:9000 /api/components/search?qualifiers=TRK&ps=500
org.json.simple.parser.ParseException: null
at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
at com.capitalone.dashboard.collector.DefaultSonar6Client.getResponse(DefaultSonar6Client.java:263) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultSonar6Client.parseJsonObject(DefaultSonar6Client.java:256) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultSonar6Client.getProjects(DefaultSonar6Client.java:104) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultSonar6Client.getProjects(DefaultSonar6Client.java:83) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.jav

Sbrenthughes @Sbrenthughes Jan 21 21:22
http://localhost:9000/api/qualityprofiles/search paste this into your browser

Sharmakartik @Sharmakartik Jan 21 21:22
2019-01-21 15:50:00,085 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-01-21 15:50:00,086 INFO c.c.d.collector.CollectorTask - http://localhost:9000
2019-01-21 15:50:00,086 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-01-21 15:50:00,214 ERROR c.c.d.collector.DefaultSonar6Client - Could not parse response from: http://localhost:9000 /api/components/search?qualifiers=TRK&ps=500
org.json.simple.parser.ParseException: null
at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
at com.capitalone.dashboard.collector.DefaultSonar6Client.getResponse(DefaultSonar6Client.java:263) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultSonar6Client.parseJsonObject(DefaultSonar6Client.java:256) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultSonar6Client.getProjects(DefaultSonar6Client.java:104) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultSonar6Client.getProjects(DefaultSonar6Client.java:83) ~[sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:104) [sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.SonarCollectorTask.collect(SonarCollectorTask.java:37) [sonar-codequality-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0-SNAPSHOT.jar!/:3.0.1]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_191]
at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_191]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_191]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_191]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_191]
2019-01-21 15:50:00,218 INFO c.c.d.collector.CollectorTask - Fetched projects 0 0s
2019-01-21 15:50:00,239 INFO c.c.d.collector.CollectorTask - New projects 0 0s
2019-01-21 15:50:00,258 INFO c.c.d.collector.CollectorTask - Updated 0 0s
2019-01-21 15:50:00,266 ERROR c.c.d.collector.DefaultSonar6Client - Could not parse response from: http://localhost:9000 /api/qualityprofiles/search
org.json.simple.parser.ParseException: null
at org.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
at com.capitalone.dashboard.collector.DefaultSon

**Comment by Sharmakartik** [comment]
something json parsing problem.

PLZ HELP!!
Thanks

**Comment by Sbrenthughes** [comment]
Can you update the title to be more appropriate? Like “Parse exception while running sonar collector”
