### ISSUE TITLE
not able to fetch jobs from jenkins collector (not showing list of jobs in dropdown of build widget)

### ISSUE THREAD

**Issue by ansha1** [Hygieia/Hygieia#2685]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Collector schedule (required)
jenkins.cron=0 0/1 * * * *

# The page size
jenkins.pageSize=1000

# The folder depth - default is 10
jenkins.folderDepth=10

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=http://10.132.209.175:8080/jenkins/

jenkins.usernames[0]=devops
jenkins.apiKeys[0]=<api_token>
jenkins.saveLog=true
jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= options.folderName
--------------------------------------------------------------------------------------------------
Please explain searchFields properties in detail, like how diffrently we can use this to search job. Problem is when i am going to dashboard > configure build widget , i am not able to see jenkins jobs in drop down. Also do we need to run API/UI after building any collector to reflect on dashboard. 
-------------------------------------------
java -jar jenkins-build-collector-3.0.1.jar --spring.config.location=/opt/Hygieia/collectors/build/jenkins/application.properties -Djasypt.encryptor.password=hygieiasecret
---------------------------------------------------------------------------------------
build Logs 
========
13:09:06,626 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
13:09:06,627 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
13:09:06,627 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/logback.xml]
13:09:06,628 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
13:09:06,628 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/lib/core-3.0.4.jar!/logback.xml]
13:09:06,628 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/logback.xml]
13:09:06,650 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@4bd5e8e0 - URL [jar:file:/opt/Hygieia/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/logback.xml] is not of type file
13:09:06,697 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
13:09:06,703 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
13:09:06,713 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
13:09:06,738 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
13:09:06,794 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
13:09:06,796 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
13:09:06,820 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
13:09:06,821 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/buildcollector-%d{yyyy-MM-dd}.%i.log for the active file
13:09:06,823 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@70012002 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/buildcollector-%d{yyyy-MM-dd}.%i.log'.
13:09:06,823 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@70012002 - Roll-over at midnight.
13:09:06,825 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@70012002 - Setting initial period to Thu Jan 24 13:09:06 IST 2019
13:09:06,827 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
13:09:06,827 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/buildcollector-2019-01-24.0.log
13:09:06,827 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
13:09:06,828 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
13:09:06,828 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
13:09:06,828 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
13:09:06,828 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
13:09:06,829 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@140783cd - Registering current configuration as safe fallback point

2019-01-24 13:09:07,741 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1ec60436: startup date [Thu Jan 24 13:09:07 IST 2019]; root of context hierarchy
2019-01-24 13:09:07,917 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-01-24 13:09:07,980 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$12c06609] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
_   _             _      _             ______       _ _     _        _____       _ _           _
| | | |           (_)    (_)            | ___ \     (_) |   | |      /  __ \     | | |         | |
| |_| |_   _  __ _ _  ___ _  __ _ ______| |_/ /_   _ _| | __| |______| /  \/ ___ | | | ___  ___| |_ ___  _ __
|  _  | | | |/ _` | |/ _ \ |/ _` |______| ___ \ | | | | |/ _` |______| |    / _ \| | |/ _ \/ __| __/ _ \| '__|
| | | | |_| | (_| | |  __/ | (_| |      | |_/ / |_| | | | (_| |      | \__/\ (_) | | |  __/ (__| || (_) | |
\_| |_/\__, |\__, |_|\___|_|\__,_|      \____/ \__,_|_|_|\__,_|       \____/\___/|_|_|\___|\___|\__\___/|_|
        __/ | __/ |
       |___/ |___/                                                                                            

2019-01-24 13:09:08,201 INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://localhost:8888
2019-01-24 13:09:08,272 WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2019-01-24 13:09:08,274 INFO  com.capitalone.dashboard.Application - No profiles are active
2019-01-24 13:09:08,285 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@f5ba37: startup date [Thu Jan 24 13:09:08 IST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@1ec60436
2019-01-24 13:09:09,196 INFO  o.s.cloud.context.scope.GenericScope - BeanFactory id=e8e784d2-4823-3463-802d-d612227f8c18
2019-01-24 13:09:09,199 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2019-01-24 13:09:09,208 INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encryptor based on properties with name 'jasyptStringEncryptor'
2019-01-24 13:09:09,214 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2019-01-24 13:09:09,214 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2019-01-24 13:09:09,214 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2019-01-24 13:09:09,215 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2019-01-24 13:09:09,215 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource applicationConfig: [file:/opt/Hygieia/collectors/build/jenkins/application.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2019-01-24 13:09:09,215 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2019-01-24 13:09:09,215 INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource defaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2019-01-24 13:09:09,218 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-01-24 13:09:09,253 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$12c06609] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-01-24 13:09:09,316 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2019-01-24 13:09:09,371 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2019-01-24 13:09:09,430 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2019-01-24 13:09:09,456 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-24 13:09:09,513 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@81813394, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@1be5f509, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@630d84c5, socketFactory=javax.net.DefaultSocketFactory@21752b2f, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2019-01-24 13:09:09,650 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:21}] to localhost:27017
2019-01-24 13:09:09,656 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 3]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=483215}
2019-01-24 13:09:09,883 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:22}] to localhost:27017
2019-01-24 13:09:10,120 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2019-01-24 13:09:10,120 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2019-01-24 13:09:10,121 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-24 13:09:10,121 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@81813394, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@1be5f509, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@630d84c5, socketFactory=javax.net.DefaultSocketFactory@21752b2f, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2019-01-24 13:09:10,126 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2019-01-24 13:09:10,127 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2019-01-24 13:09:10,127 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-24 13:09:10,136 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@81813394, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@1be5f509, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@630d84c5, socketFactory=javax.net.DefaultSocketFactory@21752b2f, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2019-01-24 13:09:10,175 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:23}] to localhost:27017
2019-01-24 13:09:10,175 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 3]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=196942}
2019-01-24 13:09:10,189 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:24}] to localhost:27017
2019-01-24 13:09:10,190 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 3]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=319388}
2019-01-24 13:09:10,542 INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2019-01-24 13:09:10,542 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2019-01-24 13:09:10,542 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-01-24 13:09:10,543 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@81813394, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@1be5f509, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@630d84c5, socketFactory=javax.net.DefaultSocketFactory@21752b2f, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2019-01-24 13:09:10,562 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:25}] to localhost:27017
2019-01-24 13:09:10,563 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 3]}, minWireVersion=0, maxWireVersion=6, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=259269}
2019-01-24 13:09:11,144 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2019-01-24 13:09:11,153 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-01-24 13:09:11,154 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-01-24 13:09:11,155 INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-01-24 13:09:11,157 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-01-24 13:09:11,168 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-01-24 13:09:11,174 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=f5ba37,type=ConfigurationPropertiesRebinder]
2019-01-24 13:09:11,224 INFO  com.capitalone.dashboard.Application - Started Application in 4.314 seconds (JVM running for 4.804)
----------------------------------------------------------
2019-01-24 13:10:00,005 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2019-01-24 13:10:00,122 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-24 13:10:00,123 INFO  c.c.d.collector.CollectorTask - http://10.132.209.175:8080/jenkins
2019-01-24 13:10:00,123 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-24 13:10:00,143 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/18 pageSize 1000...
2019-01-24 13:10:00,781 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2019-01-24 13:10:00,787 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2019-01-24 13:10:00,798 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2019-01-24 13:10:00,799 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2019-01-24 13:10:00,800 INFO  c.c.d.collector.CollectorTask - Finished                         0s

----------------------------------------------------------
![screenshot_2019-01-24 hygieia dashboard](https://user-images.githubusercontent.com/29368310/51662060-a7324f80-1fd8-11e9-9313-51616d6669b9.png)
---------------------------------------------------------------------

**Comment by ansha1** [comment]
Thanks for responding @Sbrenthughes !
I have tried same command, its not showing that drop down list of jobs i have in jenkins. My jenkins instance is having 16 project folders and 2 jobs on home page. Why its interacting with jenkins but not able to fetch jobs to dashboard. I tried restarting UI and API, tried logging out and page refresh as well. 

Also can you clear above mentioned doubts please. Do we need to launch collectors each time we restart UI and API ? 
Also after collectors do we need to restart UI to reflect data ? is there any way we can automate some of our required collectors as a service so we just have to run a script to relaunch all our required set of collectors and features in hygieia. 

2019-01-28 11:33:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2019-01-28 11:33:00,057 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-28 11:33:00,057 INFO  c.c.d.collector.CollectorTask - http://10.132.209.175:8080/jenkins
2019-01-28 11:33:00,057 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-01-28 11:33:00,061 INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/18 pageSize 1000...
2019-01-28 11:33:00,692 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2019-01-28 11:33:00,695 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2019-01-28 11:33:00,697 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2019-01-28 11:33:00,698 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2019-01-28 11:33:00,698 INFO  c.c.d.collector.CollectorTask - Finished                         0s
-------------------------------------------------------------------------
Please help me to fix above issues.

**Comment by Sbrenthughes** [comment]
The collector only collectors build information once a build has been tied to a dashboard. If you are not seeing any builds in the drop down then either your api or your collector is pointing to the wrong db. 

Can you paste your api properties here as well? 

Collectors need to run continually to refresh data. UI and API only need to be restarted when there are updates.

**Comment by ansha1** [comment]
api.properties
=========
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]
server.contextPath=/api
server.port=8080
------------------------------------------
I have checked db configurations for api and collector, which is same. Please find attached api logs. I can see some errors like "Field error in object 'codeQualityRequest' on field 'componentId': rejected value [null]". I am sure something is not working from api side. 
-------------------------
2019-01-24 14:54:12,625 INFO  o.s.t.w.s.TestDispatcherServlet - FrameworkServlet '': initialization completed in 2 ms
2019-01-24 14:54:12,631 WARN  c.c.d.rest.RestApiExceptionHandler - Bad Request - bind exception: 
org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'buildDataCreateRequest' on field 'jobName': rejected value [null]; codes [NotNull.buildDataCreateRequest.jobName,NotNull.jobName,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [buildDataCreateRequest.jobName,jobName]; arguments []; default message [jobName]]; default message [may not be null]
	at com.capitalone.dashboard.rest.RestApiExceptionHandler.handleMethodArgumentNotValid(RestApiExceptionHandler.java:60) [classes/:na]
	at org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(ResponseEntityExceptionHandler.java:167)
-------------------------------------

Link "http://10.132.208.173:8080/api/collector/type/Build/" giving output "[]" on blank screen. 

---------------------------------
My jenkins is running on version 2.114, is there any compatibility concerns with old version on jenkins ? 
---------------------------------
Suggestion : It would be really helpful, if you can upload video tutorials on youtube with basic understanding. Hygieia is amazing tool but very complicated when you configure it. 
---------------------------------------
@Sbrenthughes can we have a webex or something so that we can fix it quickly and i can have better understanding ?

**Comment by ansha1** [comment]
Somehow DB i have created earlier was not able to collect the data. I created a new DB and reconfigured everything which fixed the issue. 
Thanks for your support !

**Comment by poojithkumar** [comment]
> Can you paste `http://localhost:8080api/collector/type/Build` and let me know what the response is

[] is for me

**Comment by Sbrenthughes** [comment]
@poojithkumar that is because, based on the other 2 issues you have open, you haven't successfully ran the collector yet. 

@ansha1 thank you for responding with your fix. I apologize for not getting back sooner.

**Comment by sundeepk1** [comment]
[{"id":"5cee5dfc8a6fb236a965195c","name":"Hudson","collectorType":"Build","enabled":true,"online":true,"errors":[],"uniqueFields":{"jobName":"","jobUrl":""},"allFields":{"jobName":"","jobUrl":"","instanceUrl":""},"lastExecuted":1559128205108,"searchFields":["options.jobName","niceName"],"properties":{}}]
