### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid character ':' for HOST_IPV4

### ISSUE THREAD

**Issue by rishi-mukherjee** [Hygieia/Hygieia#2716]
2019-02-06 12:56:00,003 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2019-02-06 12:56:00,011 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-06 12:56:00,011 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-06 12:56:00,011 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-06 12:56:00,033 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalArgumentException: Invalid character ':' for HOST_IPV4 in "https://gitlab.mycompany.com"
        at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:312) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.util.HierarchicalUriComponents.verify(HierarchicalUriComponents.java:275) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.util.HierarchicalUriComponents.<init>(HierarchicalUriComponents.java:89) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.util.UriComponentsBuilder.build(UriComponentsBuilder.java:389) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.gitlab.GitlabUrlUtility.buildApiUrl(GitlabUrlUtility.java:74) ~[gitlab-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.gitlab.DefaultGitlabGitClient.getCommits(DefaultGitlabGitClient.java:58) ~[gitlab-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.GitlabGitCollectorTask.collect(GitlabGitCollectorTask.java:116) ~[gitlab-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]

**Property file**

dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=9085
dbusername=
dbpassword=
logging.file=./logs/gitlabFeature.log
gitlab.cron=0 0/1 * * * *
gitlab.host=https://gitlab.mycompany.com
gitlab.protocol=https
gitlab.port=
#gitlab.path=/gitlab/resides/here
gitlab.apiToken=xB9nWZ-7BrfLUM
gitlab.selfSignedCertificate=false
gitlab.apiVersion=4

**Comment by rishi-mukherjee** [comment]
Mentioned issue is resolved by changing the property to 
gitlab.host=gitlab.mycompany.com

After this I am seeing this exception in log - 

2019-02-06 15:07:00,039 INFO  c.c.d.gitlab.GitlabUrlUtility - ---> Gitlab URI: https://gitlab.tavant.com/api/v4/projects/finxservicing%2Fservicing/repository/commits/?ref_name=development&since=2019-01-23T09:37:00.039Z&per_page=100
2019-02-06 15:07:00,163 INFO  c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: https://gitlab.mycompany.com/finxservicing/servicing, 404 Not Found
2019-02-06 15:07:00,163 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2019-02-06 15:07:00,163 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-02-06 15:07:00,163 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Note - I have used the solution suggested in https://github.com/Hygieia/Hygieia/issues/1516

**Comment by Sbrenthughes** [comment]
Your properties file is wrong.. even compared to the issue you posted.. here is the docs https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/feature-gitlab.md

**Comment by rishi-mukherjee** [comment]
Thank you @Sbrenthughes for looking into 

https://gitlab.tavant.com/api/v4/projects/finxservicing%2Fservicing/repository/commits/?ref_name=development&since=2019-01-23T09:37:00.039Z&per_page=100

is returning 404

Please suggest...I am stuck badly

**Comment by Sbrenthughes** [comment]
Is this a private repo?

**Comment by rishi-mukherjee** [comment]
yes Sbrenthughes

**Comment by Sbrenthughes** [comment]
Can you try collect against a public repo?

**Comment by rishi-mukherjee** [comment]
Thanks for your suggestion Sbrenthughes

with Public repo I am not seeing the said exception. Snippet of log below - 

2019-02-07 13:19:59,914 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2019-02-07 13:19:59,917 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-07 13:19:59,918 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-07 13:19:59,918 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-07 13:19:59,935 INFO  c.c.d.gitlab.GitlabUrlUtility - ---> Gitlab URI: https://gitlab.com/api/v4/projects/coldnight%2Fci-test/repository/commits/?ref_name=master&since=2019-02-07T07:39:59.935Z&per_page=100
2019-02-07 13:20:00,583 INFO  c.c.d.gitlab.DefaultGitlabGitClient - page 1: 200
2019-02-07 13:20:00,595 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2019-02-07 13:20:00,596 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-02-07 13:20:00,596 INFO  c.c.d.collector.CollectorTask - Finished                         0s

Are you telling the issue is because of some permission? it may not be credential as without mentioning the Repo URL in UI widget I am not seeing such exception.

Please share your thoughts. Thanks.

**Comment by Sbrenthughes** [comment]
With the public repo can you make some commits etc? And then run the collector. Let’s see if we can collect the data. But my suspicion is that your gitlab token isn’t working for the private repo

**Comment by rishi-mukherjee** [comment]
Hi Sbrenthughes, dashboard is displaying the commits which I made in my public repo. This signifies that collector/UI is working as desired for public repo.

Now the question comes what is the problem with private repo, is it credential/permission. I am suspecting it is permission. Since you are suspecting it is credential, can you please suggest the path forward to debug the issue

**Comment by Sbrenthughes** [comment]
The `gitlab.apiToken` you are using, is that for this repo?

**Comment by rishi-mukherjee** [comment]
Yes Sbrenthughes

**Comment by rishi-mukherjee** [comment]
I found the problem, I was using gitlab.apiVersion=4 which is not supported by my gitlab. changing it to
gitlab.apiVersion=3 worked for me.

Thanks a lot Sbrenthughes for your time and suggestions.

**Comment by Sbrenthughes** [comment]
Thank you for the update!
