### ISSUE TITLE
Bamboo collector not storing data in database even after successful run of collector.

### ISSUE THREAD

**Issue by buradeshruti** [Hygieia/Hygieia#2724]
On running the Bamboo collector it is scanning through all the plans. There is no error or exception raised. But the data is not written in mongoDB database hence it is not displayed on dashboard. 
**Following is my application.properties file:**
dbname=dashboarddb

dbhost=localhost

dbport=27017

dbreplicaset=false

dbusername=dashboarduser

dbpassword=dashboarduser123

bamboo.cron=0 0/1 * * * *

bamboo.servers[0]=https://xxxxx.com

bamboo.username=uname
bamboo.apiKey=password

bamboo.savelog=false

**Following are the logs of bamboo collector:**
2019-02-11 14:10:48,091 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/SVAUTO-DAMO
2019-02-11 14:10:51,266 INFO  c.c.d.collector.DefaultBambooClient - Plan:SVAUTO-VJR7
2019-02-11 14:10:51,266 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/SVAUTO-VJR7
2019-02-11 14:10:54,339 INFO  c.c.d.collector.DefaultBambooClient - Plan:SVAUTO-VR7
2019-02-11 14:10:54,339 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/SVAUTO-VR7
2019-02-11 14:10:57,308 INFO  c.c.d.collector.DefaultBambooClient - Plan:SVAUTO-SERVERUPGRADE
2019-02-11 14:10:57,308 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/SVAUTO-SERVERUPGRADE
2019-02-11 14:11:00,072 INFO  c.c.d.collector.DefaultBambooClient - Plan:SVAUTO-LRV
2019-02-11 14:11:00,072 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/SVAUTO-LRV
2019-02-11 14:11:03,861 INFO  c.c.d.collector.DefaultBambooClient - Plan:SVAUTO-TEST
2019-02-11 14:11:03,861 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/SVAUTO-TEST
2019-02-11 14:11:06,730 INFO  c.c.d.collector.CollectorTask - Fetched jobs                  2286s
2019-02-11 14:11:06,735 INFO  c.c.d.collector.CollectorTask - New jobs                0        0s
2019-02-11 14:11:06,757 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:9, serverValue:13}] to localhost:27017
2019-02-11 14:11:06,758 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2019-02-11 14:11:06,758 INFO  c.c.d.collector.CollectorTask - Finished                      2286s
2019-02-11 14:12:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Bamboo
2019-02-11 14:12:00,076 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-11 14:12:00,076 INFO  c.c.d.collector.CollectorTask - https://xxxx.com
2019-02-11 14:12:00,076 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-11 14:12:06,116 INFO  c.c.d.collector.DefaultBambooClient - Plan:ACMACOS-TEST
2019-02-11 14:12:06,117 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/ACMACOS-TEST
2019-02-11 14:12:09,007 INFO  c.c.d.collector.DefaultBambooClient - sub Plan:ACMACOS-TEST2
2019-02-11 14:12:09,007 INFO  c.c.d.collector.DefaultBambooClient - sub plan-Result URL:https://xxxx.com/rest/api/latest/result/ACMACOS-TEST2
2019-02-11 14:12:10,733 INFO  c.c.d.collector.DefaultBambooClient - sub Plan:ACMACOS-TEST1
2019-02-11 14:12:10,733 INFO  c.c.d.collector.DefaultBambooClient - sub plan-Result URL:https://xxxx.com/rest/api/latest/result/ACMACOS-TEST1
2019-02-11 14:12:12,413 INFO  c.c.d.collector.DefaultBambooClient - sub Plan:ACMACOS-TEST0
2019-02-11 14:12:12,413 INFO  c.c.d.collector.DefaultBambooClient - sub plan-Result URL:https://xxxx.com/rest/api/latest/result/ACMACOS-TEST0
2019-02-11 14:12:14,212 INFO  c.c.d.collector.DefaultBambooClient - Plan:ACMACOS-BLACKDUCK
2019-02-11 14:12:14,213 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/ACMACOS-BLACKDUCK
2019-02-11 14:12:18,719 INFO  c.c.d.collector.DefaultBambooClient - Plan:ACMACOS-CAN
2019-02-11 14:12:18,719 INFO  c.c.d.collector.DefaultBambooClient - PlanURL: https://xxxx.com/rest/api/latest/plan/ACMACOS-CAN
2019-02-11 14:12:24,639 INFO  c.c.d.collector.DefaultBambooClient - sub Plan:ACMACOS-CAN216
2019-02-11 14:12:24,639 INFO  c.c.d.collector.DefaultBambooClient - sub plan-Result URL:https://xxxx.com/rest/api/latest/result/ACMACOS-CAN216
2019-02-11 14:12:27,241 INFO  c.c.d.collector.DefaultBambooClient - sub Plan:ACMACOS-CAN248
2019-02-11 14:12:27,241 INFO  c.c.d.collector.DefaultBambooClient - sub plan-Result URL:https://xxxx.com/rest/api/latest/result/ACMACOS-CAN248
2019-02-11 14:12:31,674 INFO  c.c.d.collector.DefaultBambooClient - sub Plan:ACMACOS-CAN198

Can somebody please help with a resolution?

**Comment by Sbrenthughes** [comment]
If it wasn’t written to mongo then it wouldn’t have completed successfully. Your api is not pointing to the same db that the collector is pointing at. 

Since this is local then remove the dbuser and db pass from the collector/api properties and try again.

**Comment by buradeshruti** [comment]
Is there any dependency of Bamboo Collector on api? The api and collector properties file have same database details. 

I have tried out both the options mentioned by you. I cannot see any data in drop down. I am using Robo 3T. I can see "Fetched 0 record(s) in 4ms" for this "db.getCollection('builds').find({})" query. 

Whereas jira collector's data is stored in database with same set of credentials. 

I removed dbuser and dbpass from both collector and api, yet the result is not getting added in database. Am I messing anything?

**Comment by Sbrenthughes** [comment]
When you run `db.collectors.find()` what do you see?

**Comment by siva-veeraraj** [comment]
please find the output of db.collectors.find(). I think properties mentioned in the property file are not updated in the DB.

{ "_id" : ObjectId("5c61a8e4d79c5f0b60dc1597"), "_class" : "com.capitalone.dashboard.model.RallyCollector", "rallyServers" : [ ], "name" : "Rally", "collectorType" : "AgileTool", "enabled" : true, "online" : true, "errors" : [ ], "uniqueFields" : { }, "allFields" : { }, "lastExecuted" : NumberLong("1549923900150"), "searchFields" : [ "description" ] }

**Comment by siva-veeraraj** [comment]
@Sbrenthughes

**Comment by Sbrenthughes** [comment]
This confirms that the collector is not inserting into the same db. Can you print the list of dbs you have on your local mongo?

**Comment by Sbrenthughes** [comment]
@buradeshruti see: https://github.com/Hygieia/Hygieia/issues/2685#issuecomment-463055214

**Comment by Sbrenthughes** [comment]
@siva-veeraraj can you post your API properties?

**Comment by buradeshruti** [comment]
Hi @Sbrenthughes,
**Following is my API properties file:**
# api.properties
dbname=dashboarddb

dbhost=localhost
dbport=27017
dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]
server.contextPath=/api
server.port=8080
logRequest=false
#logSplunkRequest=false
#corsEnabled=false
#corsWhitelist=http://domain1.com:port,http://domain2.com:port
version.number=1.0

auth.expirationTime=7200000

**Following is application.properties of Bamboo collector:**
dbname=dashboarddb

dbhost=localhost

dbport=27017

dbreplicaset=false

bamboo.cron=0 0/1 * * * *

bamboo.servers[0]=https://xxxxx.com/

bamboo.username=xxxxx
bamboo.apiKey=xxxxx

bamboo.savelog=false

On executing the bamboo collector, the output of db.collector.find() is blank.. I cannot see any exception or error in the logs, yet no data is written in database. 
Can you please help me in understanding how to recover? Or are there any other steps that I am missing out?

**Comment by Sbrenthughes** [comment]
Can you try “dropping” dashboarddb? Afterwards restart the collector and api. A fix will be coming for this issue.  Unfortunately, it won’t be in the near future.

**Comment by buradeshruti** [comment]
I actually tried creating an altogether new database, that also did not help.

**Comment by nireeshT** [comment]
@buradeshruti  did you try creating dashboard from UI after setting up UI and api. Follow these steps after setting up dashboarddb.
1) build project Hygieia 
2) run api 
3) run UI with gulp serve 
4) from UI create a dashboard 
5) verify dashboards collection in dashboarddb.

**Comment by poojithkumar** [comment]
I have facing issues with GitHub
this is my log
[org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=12bee3bd,type=ConfigurationPropertiesRebinder]
2019-02-27 01:42:22,379 INFO com.capitalone.dashboard.Application - Started Application in 15.805 seconds (JVM running for 20.316)
2019-02-27 01:43:00,005 INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - Starting...
2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:43:01,564 INFO c.c.d.collector.CollectorTask - Repo Count 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Commits 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Pulls 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Issues 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - Finished 0s
2019-02-27 01:44:00,001 INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - Starting...
2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:44:00,705 INFO c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/poojithkumar/demo/}::master:: get commits
2019-02-27 01:44:00,764 INFO c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/poojithkumar/demo//commits?sha=master&since=2019-02-13T01:44Z
2019-02-27 01:44:00,943 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Input length must be multiple of 8 when decrypting with padded cipher
2019-02-27 01:44:01,643 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/poojithkumar/demo/
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/poojithkumar/demo/commits?sha=master&since=2019-02-13T01:44Z": Received fatal alert: access_denied; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_191]
at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_191]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
... 15 common frames omitted
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - Repo Count 1 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Commits 0 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Pulls 0 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Issues 0 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - Finished 1s
public account .. and my properties file
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
github.key=bUlSRZidDsiu3OmAwRParb8V47CM8g73
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.com/poojithkumar/demo/
github.commitThresholdDays=15
github.errorThreshold=1
github.personalAccessToken=given
github.connectTimeout=20000
github.readTimeout=20000
github.username=given
github.password=given
thanks

**Comment by Sbrenthughes** [comment]
@poojithkumar I am deleting the below because it is unrelated to this thread.

> I have facing issues with GitHub
> this is my log
> [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=12bee3bd,type=ConfigurationPropertiesRebinder]
> 2019-02-27 01:42:22,379 INFO com.capitalone.dashboard.Application - Started Application in 15.805 seconds (JVM running for 20.316)
> 2019-02-27 01:43:00,005 INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
> 2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - -----------------------------------
> 2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - Starting...
> 2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - -----------------------------------
> 2019-02-27 01:43:01,564 INFO c.c.d.collector.CollectorTask - Repo Count 0 0s
> 2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Commits 0 0s
> 2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Pulls 0 0s
> 2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Issues 0 0s
> 2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - Finished 0s
> 2019-02-27 01:44:00,001 INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
> 2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - -----------------------------------
> 2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - Starting...
> 2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - -----------------------------------
> 2019-02-27 01:44:00,705 INFO c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=[https://github.com/poojithkumar/demo/}::master](https://github.com/poojithkumar/demo/%7D::master):: get commits
> 2019-02-27 01:44:00,764 INFO c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/poojithkumar/demo//commits?sha=master&since=2019-02-13T01:44Z
> 2019-02-27 01:44:00,943 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
> Input length must be multiple of 8 when decrypting with padded cipher
> 2019-02-27 01:44:01,643 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/poojithkumar/demo/
> org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/poojithkumar/demo/commits?sha=master&since=2019-02-13T01:44Z": Received fatal alert: access_denied; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
> at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
> at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
> at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
> at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
> at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
> at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
> Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
> at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_191]
> at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_191]
> at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_191]
> at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_191]
> at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_191]
> at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_191]
> at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_191]
> at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
> at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
> ... 15 common frames omitted
> 2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - Repo Count 1 1s
> 2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Commits 0 1s
> 2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Pulls 0 1s
> 2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Issues 0 1s
> 2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - Finished 1s
> public account .. and my properties file
> dbname=dashboard
> dbhost=localhost
> dbport=27017
> dbreplicaset=false
> dbhostport=localhost:27017
> server.contextPath=/api
> server.port=8080
> github.key=bUlSRZidDsiu3OmAwRParb8V47CM8g73
> logging.file=./logs/github.log
> github.cron=0 0/1 * * * *
> github.host=https://github.com/poojithkumar/demo/
> github.commitThresholdDays=15
> github.errorThreshold=1
> github.personalAccessToken=given
> github.connectTimeout=20000
> github.readTimeout=20000
> github.username=given
> github.password=given
> thanks

**Comment by ansha1** [comment]
Hello @Sbrenthughes hope you are doing well. This is a bug and occurs most of the time while running collectors after system restarts. Are we working on its fix ?

**Comment by Sbrenthughes** [comment]
@ansha1 can you post the solution you found?

**Comment by Sbrenthughes** [comment]
Can you try specifying a port for it to run on? @ansha1 has had success with this.

**Comment by Sbrenthughes** [comment]
@buradeshruti any update?

**Comment by Sbrenthughes** [comment]
Closing due to inactivity
