### ISSUE TITLE
rally collector not fetching any data

### ISSUE THREAD

**Issue by siva-veeraraj** [Hygieia/Hygieia#2725]
2019-02-11 13:04:09,970 INFO  com.capitalone.dashboard.Application - Started Application in 14.703 seconds (JVM running for 17.898)
2019-02-11 13:05:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:06:00,003 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:07:00,003 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:08:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:09:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:10:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:11:00,003 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:12:00,003 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally
2019-02-11 13:13:00,004 INFO  c.c.d.collector.CollectorTask - Running Collector: Rally

i dont see any error in the collector log. 

properties 

dbname=dashboarddb
dbusername=dashboarduser
dbpassword=********
dbhost=localhost
dbport=27017
rally.cron=0 0/1 * * * *
rally.servers[0]=https://rally1.rallydev.com
rally.usernames[0]=*******
rally.passwords[0]=******

 i dont see any data in feature collection in mongodb.

**Comment by siva-veeraraj** [comment]
please find the output of db.collectors.find(). I think properties mentioned in the property file are not updated in the DB.

{ "_id" : ObjectId("5c61a8e4d79c5f0b60dc1597"), "_class" : "com.capitalone.dashboard.model.RallyCollector", "rallyServers" : [ ], "name" : "Rally", "collectorType" : "AgileTool", "enabled" : true, "online" : true, "errors" : [ ], "uniqueFields" : {  }, "allFields" : {  }, "lastExecuted" : NumberLong("1549923900150"), "searchFields" : [ "description" ] }

This is how am running the application:

java -jar rally-collector-3.0.1.jar --spring.config.name=rally --spring.config.location=C:\*******\Hygieia-master\Hygieia-master\collectors\feature\rally\application.properties

**Comment by buradeshruti** [comment]
I guess this issue is similar to #2724.

**Comment by siva-veeraraj** [comment]
@buradeshruti ... it didnt work.. actually my problem is something the rally configuration details are not getting stored in collector collection in mongodb.

{ "_id" : ObjectId("5c61a8e4d79c5f0b60dc1597"), "_class" : "com.capitalone.dashboard.model.RallyCollector", **"rallyServers" : [ ], "n**ame" : "Rally", "collectorType" : "AgileTool", "enabled" : true, "online" : true, "errors" : [ ], "uniqueFields" : { }, "allFields" : { }, "lastExecuted" : NumberLong("1549923900150"), "searchFields" : [ "description" ] }

**Comment by siva-veeraraj** [comment]
if the properties are stored in the DB then it will work i guess.

**Comment by siva-veeraraj** [comment]
@tabladrum . Hi can you please help me in this issue

**Comment by siva-veeraraj** [comment]
@matthewbeasley 

Hi Can you please help me on this. I dont see any data fetched from rally. I think problem with loading the application properties.

**Comment by siva-veeraraj** [comment]
@Sbrenthughes
Hi,

I have all the details  mentioned above

**Comment by Sbrenthughes** [comment]
When you created a dashboard did you select the Rally widget?
![image](https://user-images.githubusercontent.com/26173728/52660508-cdf3ef80-2ecd-11e9-9115-9c614dd5cbc2.png)

**Comment by siva-veeraraj** [comment]
@Sbrenthughes .. Thank you so much for replying and please find the details below. 

i removed the .springBeans file from the code and build the code and ran the collector and now i can see the configurations are inserted into the db. As you mentioned i have selected the rally widget and now i can see the list of projects. i selected one project and saved the widget and now am seeing the below error in the collector log.

019-02-12 13:04:01,149 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
2019-02-12 13:04:01,149 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[na:1.8.0_201]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[na:1.8.0_201]
	at java.lang.Double.parseDouble(Unknown Source) ~[na:1.8.0_201]
	at com.capitalone.dashboard.collector.DefaultRallyClient.getBurnDownData(DefaultRallyClient.java:317) ~[rally-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.RallyCollectorTask.refreshIterationBurnDownData(RallyCollectorTask.java:330) ~[rally-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.RallyCollectorTask.refreshData(RallyCollectorTask.java:279) ~[rally-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.RallyCollectorTask.collect(RallyCollectorTask.java:143) ~[rally-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.RallyCollectorTask.collect(RallyCollectorTask.java:42) ~[rally-collector-3.0.1.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.0.1]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_201]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]

**Comment by Sbrenthughes** [comment]
When you run the collector what is the output now?

**Comment by siva-veeraraj** [comment]
@Sbrenthughes .. you are right.. it takes time to fetch the data but its working as expected.  i can see the data populated to rally widget. The only thing i did was removed the .springBean file from the rally collector repo and selected the rally widget.

Thank you so much for the help

**Comment by Sbrenthughes** [comment]
No problem can we close this?

**Comment by siva-veeraraj** [comment]
@Sbrenthughes .. I have one more doubt in github configuration. in dashboard.properties we have property 

# API token generated for basic authentication to secure APIs.
key=***********************

github collector application property contains     
# This is the key generated using the Encryption class in core
    github.key=<your-generated-key>

Is this both are same if so do i need to give the key generated through admin ui in the both the fields or the key generated through core jar as mentioned in http://hygieia.github.io/Hygieia/collectors.html#encryption-for-private-repos in both the fields

**Comment by siva-veeraraj** [comment]
@Sbrenthughes 

Hi,

I gave the same the key generated through UI in both the property file and it worked. Before  giving the key i have configured that repo in the widget so it showed an error like below.
![repo](https://user-images.githubusercontent.com/47429392/52668730-f08c0580-2ed9-11e9-9df6-9da01d6633fc.png)

after giving the key it started pulling the data but still that 404 error is showing in the widget.

**Comment by siva-veeraraj** [comment]
@Sbrenthughes ... one last question does rally collector collect the feature id details ?

**Comment by Sbrenthughes** [comment]
I am not sure what the feature id is in Rally. I can only help with general collector setup issues in the instance.

**Comment by nitingoyal8** [comment]
@siva-veeraraj - I am also facing the same issue where rally server information is not updated in mongo database, I tried dropping database, deleting .spring file and all the suggestion. Is there any specific things you performed?
