### ISSUE TITLE
collector build 

### ISSUE THREAD

**Issue by poojithkumar** [Hygieia/Hygieia#2727]
C:\opt\Hygieia-master\collectors\build\jenkins\target>java -jar jenkins-build-collector-3.0.1.jar --spring.config.name=jenkins --spring.config.location=C:\opt\Hygieia-master\collectors\build\jenkins\application.properties
16:50:07,997 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:50:08,001 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:50:08,003 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/opt/Hygieia-master/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/logback.xml]
16:50:08,012 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:50:08,014 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/opt/Hygieia-master/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/logback.xml]
16:50:08,014 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/opt/Hygieia-master/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/lib/core-3.0.4.jar!/logback.xml]
16:50:08,375 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6ed02ae3 - URL [jar:file:/C:/opt/Hygieia-master/collectors/build/jenkins/target/jenkins-build-collector-3.0.1.jar!/logback.xml] is not of type file
16:50:08,696 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:50:08,786 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:50:08,837 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:50:08,912 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:50:09,226 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:50:09,292 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
16:50:09,540 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
16:50:09,547 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/buildcollector-%d{yyyy-MM-dd}.%i.log for the active file
16:50:09,569 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@606575fc - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/buildcollector-%d{yyyy-MM-dd}.%i.log'.
16:50:09,569 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@606575fc - Roll-over at midnight.
16:50:09,599 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@606575fc - Setting initial period to Tue Feb 12 16:50:09 IST 2019
16:50:09,616 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:50:09,618 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/buildcollector-2019-02-12.0.log
16:50:09,618 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
16:50:09,626 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:50:09,626 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
16:50:09,630 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:50:09,630 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:50:09,634 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@25a7235a - Registering current configuration as safe fallback point

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.util.Properties.loadConvert(Unknown Source)
        at java.util.Properties.load0(Unknown Source)
        at java.util.Properties.load(Unknown Source)
        at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:139)
        at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:121)
        at org.springframework.boot.env.PropertiesPropertySourceLoader.load(PropertiesPropertySourceLoader.java:44)
        at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:127)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:452)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:417)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:360)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:200)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:169)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:161)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:146)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
        at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:175)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
        at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
        at com.capitalone.dashboard.Application.main(Application.java:16)
        ... 6 more

help me to solve this

**Comment by poojithkumar** [comment]
this is my properties  file


#Database Name 
dbname=dashboarddb
 
#Database HostName - default is localhost
dbhost=localhost
 
#Database Port - default is 27017
dbport=27017
 
#Database Username - default is blank
#dbusername=dashboarduser
 
#Database Password - default is blank
#dbpassword=dbpass
 
jenkins.servers[0]=http://localhost:8190/jenkins/
#Collector schedule (required)
jenkins.cron=0 0/1 * * * *
 
#Jenkins server (required) - Can provide multiple
 
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
jenkins.servers[1]=http://username:token@jenkins.company.com
 
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.username=admin
#jenkins.apiKey=
 
#Determines if build console log is collected - defaults to false
jenkins.saveLog=true

**Comment by nireeshT** [comment]
@poojithkumar  use index for usernames
`jenkins.usernames[0]=admin`
`jenkins.usernames[1]=admin`
