### ISSUE TITLE
Jira - Failed to collect jira information

### ISSUE THREAD

**Issue by rikameajay1** [Hygieia/Hygieia#2741]
hi getting following error while configuring jira collector

2019-02-20 16:40:00,368 INFO  c.c.d.collector.CollectorTask - Project Data Collected 10        0s
2019-02-20 16:40:00,378 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_191]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_191]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_191]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_191]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.refreshValidIssues(FeatureCollectorTask.java:372) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:141) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:46) [jira-feature-collector.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0-SNAPSHOT.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by Sbrenthughes** [comment]
@rikameajay1 Can you pull the latest? This issue should be resolved with latest.

**Comment by harish123321** [comment]
Still I am unable to collect data. Here are my properties.

logging.file=./logs/jira.log
feature.pageSize=100
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.deltaCollectorItemStartDate=2019-01-01T00:00:00.000000
feature.jiraBaseUrl=https://syscobt.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=
feature.jiraIssueTypeId=Story
feature.jiraSprintDataFieldName=customfield_*****
feature.jiraEpicIdFieldName=customfield_*****
feature.jiraStoryPointsFieldName=customfield_*****
feature.jiraTeamFieldName=customfield_*****
feature.cron=0 0/1 * * * *
feature.deltaStartDate=2019-01-01T00:00:00.000000
feature.masterStartDate=2019-01-01T00:00:00.00000
feature.jiraBoardAsTeam=true
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done
logging.level.com.atlassian.jira=DEBUG
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG

**Comment by Sbrenthughes** [comment]
Same error?

**Comment by harish123321** [comment]
I am not getting error this time but data is not populated in UI

**Comment by Sbrenthughes** [comment]
Can you reach out directly to me on gitter?

**Comment by rikameajay1** [comment]
@Sbrenthughes after pull the latest code the error got resolved. But feature widget shows 0 as the output.

2019-02-22 14:38:00,118 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-02-22 14:38:00,184 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-02-22T14:36:00.012 0        0s
2019-02-22 14:38:00,187 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 2 of 3 boards.
2019-02-22 14:38:00,334 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-02-22T14:36:00.177 0        0s
2019-02-22 14:38:00,336 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 3 of 3 boards.

**Comment by Sbrenthughes** [comment]
Can you delete the team, scope and feature collection? Once that is done can you verify that the project/board combo on the UI matches what is in Jira?

**Comment by rikameajay1** [comment]
hi @Sbrenthughes,  deleted team, scope and feature collection and now jira doesn't even add projects and board.
Even tried with some wrong values for jira url and credentials, still jira is not throwing any errors, no entry in logs as well.

**Comment by rikameajay1** [comment]
working now

**Comment by Sbrenthughes** [comment]
What did you do to resolve it ?

**Comment by rikameajay1** [comment]
> hi @Sbrenthughes, deleted team, scope and feature collection and now jira doesn't even add projects and board.
> Even tried with some wrong values for jira url and credentials, still jira is not throwing any errors, no entry in logs as well.

this started working after altering the src code @Sbrenthughes

**Comment by rikameajay1** [comment]
> @Sbrenthughes after pull the latest code the error got resolved. But feature widget shows 0 as the output.
> 
> 2019-02-22 14:38:00,118 INFO c.c.d.collector.CollectorTask - Finished 0s
> 2019-02-22 14:38:00,184 INFO c.c.d.collector.CollectorTask - Story Data Collected since 2019-02-22T14:36:00.012 0 0s
> 2019-02-22 14:38:00,187 INFO c.c.d.collector.FeatureCollectorTask - Collecting 2 of 3 boards.
> 2019-02-22 14:38:00,334 INFO c.c.d.collector.CollectorTask - Story Data Collected since 2019-02-22T14:36:00.177 0 0s
> 2019-02-22 14:38:00,336 INFO c.c.d.collector.FeatureCollectorTask - Collecting 3 of 3 boards.

this issue is still present

**Comment by Sbrenthughes** [comment]
Are you still facing issues or not? I am confused by 

> working now

and 

> > @Sbrenthughes after pull the latest code the error got resolved. But feature widget shows 0 as the output.
> > 2019-02-22 14:38:00,118 INFO c.c.d.collector.CollectorTask - Finished 0s
> > 2019-02-22 14:38:00,184 INFO c.c.d.collector.CollectorTask - Story Data Collected since 2019-02-22T14:36:00.012 0 0s
> > 2019-02-22 14:38:00,187 INFO c.c.d.collector.FeatureCollectorTask - Collecting 2 of 3 boards.
> > 2019-02-22 14:38:00,334 INFO c.c.d.collector.CollectorTask - Story Data Collected since 2019-02-22T14:36:00.177 0 0s
> > 2019-02-22 14:38:00,336 INFO c.c.d.collector.FeatureCollectorTask - Collecting 3 of 3 boards.
> 
> this issue is still present

**Comment by rikameajay1** [comment]
jira widget does not show anything, but logs show **Board: 'board_name' passes the feature max limit at 7233 features. Skipping..** and feature collection is empty.

**Comment by Sbrenthughes** [comment]
Is that the only board you have?

**Comment by Sbrenthughes** [comment]
If so you you can add `feature.maxNumberOfFeaturesPerBoard=8000` and try again

**Comment by rikameajay1** [comment]
2019-03-01 13:39:00,016 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-03-01 13:39:00,023 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 2 boards.
2019-03-01 13:44:32,328 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 1970-01-01T05:30 0      332s
2019-03-01 13:44:32,335 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 2 of 2 boards.
2019-03-01 13:49:52,484 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 1970-01-01T05:30 0      652s
2019-03-01 13:49:52,493 INFO  c.c.d.collector.CollectorTask - Finished                       652s
2019-03-01 13:50:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira

this is what I'm getting after **feature.maxNumberOfFeaturesPerBoard=8000**

But still nothing in feature collection nor on widget

**Comment by Sbrenthughes** [comment]
It’s trying to collect from today. You need to again delete the team, scope and feature collections. Update the collector’s timestamp fields to 0 for the jira collector in the `collectors` collection.

**Comment by Sbrenthughes** [comment]
Also, go ahead and add this property `feature.collectorItemOnlyUpdate=false`

**Comment by Sbrenthughes** [comment]
This is probably because your story/ epic ideas don’t match update to the latest

**Comment by hungrypanda** [comment]
facing the same issue even with the latest src code, please help

**Comment by Hemila-S** [comment]
Hi Sbrenthughes,
Facing the same issue, not able to fetch the data in UI 

2019-12-03 10:36:00,128 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://parkercfa.atlassian.net/rest/api/2/issuetype status=200 duration=120
2019-12-03 10:36:00,132 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-12-03 10:36:00,132 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - https://parkercfa.atlassian.net/
2019-12-03 10:36:00,133 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-12-03 10:36:00,134 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-12-03 10:36:00,135 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-12-03 10:36:00,138 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s

Help me to resolve this!

**Comment by Hemila-S** [comment]
Hi, 
Facing the same issue , not able to fetch the data in UI but it is not throwing any errors.

2019-12-03 10:36:00,134 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-12-03 10:36:00,135 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-12-03 10:36:00,138 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s

Help me to resolve !

**Comment by rvema** [comment]
@Hemila-S please create an issue against the hygieia-feature-jira-collector repository.
