### ISSUE TITLE
Unable to display dashboard data

### ISSUE THREAD

**Issue by varshinichowdary27** [Hygieia/Hygieia#2751]
TypeError: Unable to get property 'forEach' of undefined or null reference
   at hasDashboardConfigPermission (http://localhost:3001/app/dashboard/services/userService.js:61:8)
   at hasPermission (http://localhost:3001/app/dashboard/directives/widget.js:140:14)
   at fn (Function code:2:207)
   at Scope.prototype.$digest (http://localhost:3001/node_modules/angular.js:17828:21)
   at Scope.prototype.$apply (http://localhost:3001/node_modules/angular.js:18102:13)
   at tick (http://localhost:3001/node_modules/angular.js:12898:25)

**Comment by kheinz04** [comment]
We recently updated the project to remove bower so there may be some dependency issues. Try deleting 'node_modules', 'dist', and 'bower_components' from your UI folder manually, then try rebuilding. This should force your project to use the latest set of dependencies. You can also make sure npm is up to date by running 'npm update'.

Also make sure you have the latest version of the core downloaded and built.
We recommend having the latest version of node as well.

These were the resolutions to the main issues our team was having after the update. Let us know if you are still having problems after trying these out.

**Comment by Sbrenthughes** [comment]
Closing due to inactivity.
