### ISSUE TITLE
github collectors(401 unauthorized error)

### ISSUE THREAD

**Issue by poojithkumar** [Hygieia/Hygieia#2753]
if i use private repo iam getting 401 unauthorized error and in command line its not getting any error.
i can see error on my UI only.

if i use public repo its giving personal acces token = Error
decryption not possible...
i set api properties file with key and github properties with ket as well
 

thank you

**Comment by poojithkumar** [comment]
this is my log 
  
[org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=12bee3bd,type=ConfigurationPropertiesRebinder]
2019-02-27 01:42:22,379 INFO  com.capitalone.dashboard.Application - Started Application in 15.805 seconds (JVM running for 20.316)
2019-02-27 01:43:00,005 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-02-27 01:43:00,919 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:43:00,919 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-27 01:43:00,919 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:43:01,564 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2019-02-27 01:43:01,565 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-02-27 01:43:01,565 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-02-27 01:43:01,565 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-02-27 01:43:01,565 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-02-27 01:44:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-02-27 01:44:00,053 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:44:00,053 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-27 01:44:00,053 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:44:00,705 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/poojithkumar/demo/}::master:: get commits
2019-02-27 01:44:00,764 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/poojithkumar/demo//commits?sha=master&since=2019-02-13T01:44Z
2019-02-27 01:44:00,943 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Input length must be multiple of 8 when decrypting with padded cipher
2019-02-27 01:44:01,643 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/poojithkumar/demo/
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/poojithkumar/demo/commits?sha=master&since=2019-02-13T01:44Z": Received fatal alert: access_denied; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_191]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_191]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 15 common frames omitted
2019-02-27 01:44:01,667 INFO  c.c.d.collector.CollectorTask - Repo Count              1        1s
2019-02-27 01:44:01,667 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2019-02-27 01:44:01,667 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s
2019-02-27 01:44:01,667 INFO  c.c.d.collector.CollectorTask - New Issues              0        1s
2019-02-27 01:44:01,667 INFO  c.c.d.collector.CollectorTask - Finished                         1s


public account .. and my properties file
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
github.key=bUlSRZidDsiu3OmAwRParb8V47CM8g73
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.com/poojithkumar/demo/
github.commitThresholdDays=15
github.errorThreshold=1
github.personalAccessToken=<given>
github.connectTimeout=20000
github.readTimeout=20000
github.username=<given>
github.password=<given>


thanks

**Comment by Sbrenthughes** [comment]
From the ui are you adding a token when configuring the widget?

**Comment by poojithkumar** [comment]
I tried both way...

**Comment by Sbrenthughes** [comment]
It won’t work passing it from the UI if you don’t have the encryption setup. Which you don’t.

**Comment by poojithkumar** [comment]
iam using public account ...

**Comment by poojithkumar** [comment]
2019-03-04 01:26:00,235 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/Hygieia/hygieia-query}::master:: get commits
2019-03-04 01:26:00,282 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-03-04 01:26:00,283 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/Hygieia/hygieia-query/commits?sha=master&since=2019-02-18T01:26Z
2019-03-04 01:26:00,283 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-03-04 01:26:00,738 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/Hygieia/hygieia-query
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/Hygieia/hygieia-query/commits?sha=master&since=2019-02-18T01:26Z": Received fatal alert: access_denied; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:596) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_191]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_191]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_191]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 15 common frames omitted
2019-03-04 01:26:00,755 INFO  c.c.d.collector.CollectorTask - Repo Count              3        0s
2019-03-04 01:26:00,755 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-03-04 01:26:00,756 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-03-04 01:26:00,756 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-03-04 01:26:00,756 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-03-04 01:27:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-03-04 01:27:00,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------




properties file  
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
#github.key=bUlSRZidDsiu3OmAwRParb8V47CM8g73
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.com

github.commitThresholdDays=15
github.errorThreshold=1
github.personalAccessToken=498dc1c62cebeddb7f3795cffa48281eec2b8c55
github.connectTimeout=20000
github.readTimeout=20000

**Comment by Sbrenthughes** [comment]
Did you resolve this?

**Comment by poojithkumar** [comment]
I didn't checked yet..let you know about that

**Comment by poojithkumar** [comment]
yes..., this is also solved now :)

**Comment by zerolaser** [comment]
@poojithkumar how did you resolve this ?
