### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by shreyamNewt** [Hygieia/Hygieia#2756]
Hi,
When  tryning to access Hygieia UI I'm getting following error. Please chechk and reply.
Uncaught ReferenceError: config is not defined
    at localhost/:10
template-cache.js:1 Uncaught ReferenceError: angular is not defined
    at template-cache.js:1

**Comment by kheinz04** [comment]
Did you download the latest version and build? Were there any build errors?

**Comment by nireeshT** [comment]
@shreyamNewt  get latest code and do clean install. We did remove bower config from UI https://github.com/Hygieia/Hygieia/pull/2732, so it is just npm and gulp.  Refer https://github.com/Hygieia/Hygieia/blob/7f4e3597ff65cd015db576125c82d6fbdbbafe3e/pages/hygieia/UI/ui.md for installation steps. 
Recommended to upgrade node version to latest

**Comment by kheinz04** [comment]
If you are stilling having issues, try deleting 'node_modules', 'dist', and 'bower_components' from your UI folder manually. Then try rebuilding. This should force your project to use the latest set of dependencies.

Also make sure you have the latest version of the core downloaded and built. 

Let us know if you are still having problems.

**Comment by sameer-shukur** [comment]
Hi,
I'm facing issue while running,
$ mvn clean install package -rf :UI
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.115 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.1.9-SNAPSHOT
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api:jar:3.0.1
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.capitalone.dashboard:api-audit:jar:3.0.1
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jenkins-ci.plugins:hygieia-publisher:hpi:2.1.9-SNAPSHOT
[WARNING] 'dependencies.dependency.version' for com.capitalone.dashboard:core:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 124, column 22
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.1.9-SNAPSHOT (C:\Users\sameer\Desktop\test\Hygieia\hygieia-jenkins-plugin\pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] com.capitalone.dashboard:UI                                        [pom]
[INFO] com.capitalone.dashboard:ui-tests                                  [jar]
[INFO]
[INFO] --------------------< com.capitalone.dashboard:UI >---------------------
[INFO] Building com.capitalone.dashboard:UI 3.0.1                         [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO]
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ UI >>>
[INFO]
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
[INFO]
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ UI <<<
[INFO]
[INFO]
[INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
[INFO] argLine set to -javaagent:C:\\Users\\sameer\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.6.201602180812\\org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=C:\\Users\\sameer\\Desktop\\test\\Hygieia\\UI\\target\\jacoco.exec
[INFO]
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ UI ---
[INFO] Node v11.9.0 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.6:gulp (gulp build) @ UI ---
[INFO] Running 'gulp build' in C:\Users\sameer\Desktop\test\Hygieia\UI
[INFO] [22:39:08] Using gulpfile ~\Desktop\test\Hygieia\UI\gulpfile.js
[INFO] [22:39:09] Starting 'build'...
[INFO] [22:39:09] Starting 'clean'...
[INFO] [22:39:09] Finished 'clean' after 204 ms
[INFO] [22:39:09] Starting 'assets'...
[INFO] [22:39:09] Starting 'themes'...
[INFO] [22:39:09] Starting 'fonts'...
[INFO] [22:39:09] Starting 'js'...
[INFO] [22:39:09] Starting 'views'...
[INFO] [22:39:09] Starting 'test-data'...
[ERROR] Error in plugin 'gulp-less'
[INFO] [22:39:11] Finished 'themes' after 2.57 s
[ERROR] Message:
[ERROR]     '../../../../node_modules/ui-select/dist/select.css' wasn't found in file C:\Users\sameer\Desktop\test\Hygieia\UI\src\components\widgets\build\build.less line no. 3
[ERROR] Details:
[ERROR]     type: File
[ERROR]     filename: C:\Users\sameer\Desktop\test\Hygieia\UI\src\components\widgets\build\build.less
[ERROR]     index: 107
[ERROR]     line: 3
[ERROR]     callLine: NaN
[ERROR]     callExtract: undefined
[ERROR]     column: 0
[ERROR]     extract: @import (reference) '../../../app/css/mixins.less';,@import (less)  '../../../../node_modules/ui-select/dist/select.css';,
[ERROR]     lineNumber: 3
[ERROR]     fileName: C:\Users\sameer\Desktop\test\Hygieia\UI\src\components\widgets\build\build.less
[INFO] [22:39:12] Finished 'assets' after 3.46 s
[INFO] [22:39:12] Finished 'views' after 3.39 s
[INFO] [22:39:12] Finished 'test-data' after 3.59 s
[INFO] [22:39:18] Finished 'js' after 8.94 s
[INFO] [22:39:29] Finished 'fonts' after 20 s
[INFO] [22:39:29] Starting 'html'...
[INFO] [22:39:29] 'html' errored after 18 ms
**[INFO] [22:39:29] Error: Error: jquery is not installed. Try running `bower install` or remove the component from your bower.json file.**
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\npm-wiredep.js:29:56
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\lib\detect-dependencies.js:149:29
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:4911:15
[INFO]     at baseForOwn (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:2996:24)
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:4880:18
[INFO]     at Function.forEach (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:9344:14)
[INFO]     at detectDependencies (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\lib\detect-dependencies.js:34:7)
[INFO]     at wiredep (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\npm-wiredep.js:69:39)
[INFO]     at Gulp.<anonymous> (C:\Users\sameer\Desktop\test\Hygieia\UI\gulpfile.js:262:13)
[INFO]     at module.exports (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\orchestrator\lib\runTask.js:34:7)
[INFO] [22:39:29] 'build' errored after 20 s
[INFO] [22:39:29] Error in plugin 'run-sequence(html)'
[INFO] Message:
[INFO]     Error: jquery is not installed. Try running `bower install` or remove the component from your bower.json file.
[INFO] Stack:
[INFO] Error: Error: jquery is not installed. Try running `bower install` or remove the component from your bower.json file.
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\npm-wiredep.js:29:56
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\lib\detect-dependencies.js:149:29
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:4911:15
[INFO]     at baseForOwn (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:2996:24)
[INFO]     at C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:4880:18
[INFO]     at Function.forEach (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\node_modules\lodash\lodash.js:9344:14)
[INFO]     at detectDependencies (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\lib\detect-dependencies.js:34:7)
[INFO]     at wiredep (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\npm-wiredep\npm-wiredep.js:69:39)
[INFO]     at Gulp.<anonymous> (C:\Users\sameer\Desktop\test\Hygieia\UI\gulpfile.js:262:13)
[INFO]     at module.exports (C:\Users\sameer\Desktop\test\Hygieia\UI\node_modules\orchestrator\lib\runTask.js:34:7)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for com.capitalone.dashboard:UI 3.0.1:
[INFO]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 26.234 s]
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.749 s
[INFO] Finished at: 2019-03-01T22:39:29+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:gulp (gulp build) on project UI: Failed to run task: 'gulp build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Node version: v11.9.0
npm version: 6.8.0
Gulp: CLI version: 2.0.0 Local version: 4.0.0

Please note, as per above comments mentioned by @nireeshT , I performed git pull before actually building the project and even removed bower.json files from the local repo.

**Comment by nireeshT** [comment]
@shreyamNewt  @sameer-shukur  if you have node_modules and bower_components under UI, delete them and 
1) run npm install 
2) gulp serve

**Comment by Sbrenthughes** [comment]
Closing due to inactivity.
