### ISSUE TITLE
Getting 401 error when trying to configure gitlab collector

### ISSUE THREAD

**Issue by Sathyap3** [Hygieia/Hygieia#2758]
Hi ,

I am getting 401 Unauthorized when trying to configure SCM widget and collector for Hygieia. Do i have to add the generated key to gitlab ? where in gitlab should i update

Any help is appreciated . Thanks in Advance

I have passed the project ID as well but still won't fetch info. and below are details of application.properties , Output and widget configuration

**Application.properties**

dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
dbusername=dashboarduser
dbpassword=dbpassword
logging.file=./logs/gitlabFeature.log
gitlab.cron=* * * * * *
gitlab.host=git.company.com
gitlab.protocol=https
gitlab.port=
gitlab.path=
gitlab.apiToken=iN1Lb+dNRqagRq4HUeMfDRnmrDo0j3Ac4kvgHlsLnUx
gitlab.commitThresholdDays=15
gitlab.key=0CaGVCAHikVRH48WKZHpfD7NAQ4ET6T

**To generate API key followed the below steps**

1. create an admin user - useername - "admin" , password -"you can chose any password"
2. go to admin settings -> Generate Api token -> create new key by setting name  and expiration date.

**Repo Widget have updated the below info:**

Collector Type : Gitlab
Repo URL : https://git.company.com/1691
Branch : Develop
API key : 0CaGVCAHikVRH48WKZHpfD7NAQ4ET6T

**Output after running API**
2019-02-27 17:11:53,978 INFO c.c.d.gitlab.GitlabUrlUtility - ---> Gitlab URI: https://git.company.com/api/v4/projects/1691/repository/commits/?ref_name=Develop&since=2019-02-13T11:41:53.701Z&per_page=100
2019-02-27 17:11:55,646 INFO c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: https://git.virtusa.com/1699, 401 Unauthorized
2019-02-27 17:11:55,661 INFO c.c.d.collector.CollectorTask - Repo Count 1 4s
2019-02-27 17:11:55,668 INFO c.c.d.collector.CollectorTask - New Commits 0 4s
2019-02-27 17:11:55,671 INFO c.c.d.collector.CollectorTask - Finished 4s
2019-02-27 17:11:56,001 INFO c.c.d.collector.CollectorTask - Running Collector: Gitlab
2019-02-27 17:11:56,007 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 17:11:56,007 INFO c.c.d.collector.CollectorTask - Starting...
2019-02-27 17:11:56,009 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 17:11:56,063 INFO c.c.d.gitlab.GitlabUrlUtility - ---> Gitlab URI: https://git.company.com/api/v4/projects/1699/repository/commits/?ref_name=Develop&since=2019-02-13T11:41:56.063Z&per_page=100
2019-02-27 17:11:56,167 INFO c.c.d.c.GitlabGitCollectorTask - Failed to retrieve data, the repo or collector is most likey misconfigured: https://git.company.com/1699, 401 Unauthorized

**Comment by nireeshT** [comment]
@Sathyap3  if this is not a private repo, I would recommend to remove all api tokens and run collector. 
1) delete widget and reconfigure with out api token 
2) remove below props 
`gitlab.apiToken=iN1Lb+dNRqagRq4HUeMfDRnmrDo0j3Ac4kvgHlsLnUx
gitlab.commitThresholdDays=15
gitlab.key=0CaGVCAHikVRH48WKZHpfD7NAQ4ET6T`

if it is private repo, follow these steps 
1) deleted configured widget
2) remove below props 
`gitlab.apiToken=iN1Lb+dNRqagRq4HUeMfDRnmrDo0j3Ac4kvgHlsLnUx
gitlab.commitThresholdDays=15
gitlab.key=0CaGVCAHikVRH48WKZHpfD7NAQ4ET6T`
3) generate personal access token in gitlab -> developer settings -> genereate token 
4) use generated token in prop file as 
gitlab.apiToken= <generated from gitlab
`
5) reconfigure repo widget without apiToken, process will take it from prop file.  If you configure on widget, that will take precedence over prop file. 
6) run collector

**Comment by poojithkumar** [comment]
iam also getting error in github


2019-03-06 01:04:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-03-06 01:04:00,015 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-06 01:04:00,015 INFO  c.c.d.collector.CollectorTask - Starting...
2019-03-06 01:04:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-06 01:04:00,269 INFO  c.c.d.collector.CollectorTask - Repo Count              2        0s
2019-03-06 01:04:00,269 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-03-06 01:04:00,269 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-03-06 01:04:00,270 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-03-06 01:04:00,270 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-03-06 01:05:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-03-06 01:05:00,031 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-06 01:05:00,031 INFO  c.c.d.collector.CollectorTask - Starting...
2019-03-06 01:05:00,032 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-06 01:05:00,241 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/leereilly/games}::master:: get commits
2019-03-06 01:05:00,259 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/leereilly/games/commits?sha=master&since=2019-02-20T01:05Z
2019-03-06 01:05:01,035 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/leereilly/games
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/leereilly/games/commits?sha=master&since=2019-02-20T01:05Z": Received fatal alert: access_denied; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:598) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_201]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_201]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_201]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_201]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_201]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_201]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_201]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 15 common frames omitted
2019-03-06 01:05:01,058 INFO  c.c.d.collector.CollectorTask - Repo Count              3        1s
2019-03-06 01:05:01,059 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2019-03-06 01:05:01,059 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s
2019-03-06 01:05:01,060 INFO  c.c.d.collector.CollectorTask - New Issues              0        1s
2019-03-06 01:05:01,060 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-03-06 01:06:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-03-06 01:06:00,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-03-06 01:06:00,015 INFO  c.c.d.collector.CollectorTask - Starting...
2019-03-06 01:06:00,015 INFO  c.c.d.c







my properties file


dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
#github.key=bUlSRZidDsiu3OmAwRParb8V47CM8g73
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.com

github.commitThresholdDays=15
github.errorThreshold=1
#github.personalAccessToken=498dc1c62cebeddb7f3795cffa48281eec2b8c55
github.connectTimeout=20000
github.readTimeout=20000


and i run collector with 
java -jar  github-scm-collector-3.0.1.jar  --spring.config.name=github --spring.config.location=/workspace/opt1/hygieia/collectors/scm/github/target/application.properties
