### ISSUE TITLE
JIRA collector is not gathering data in feature db collection

### ISSUE THREAD

**Issue by meghnakale** [Hygieia/Hygieia#2807]
I have configured the JIRA collector, it did reflected the Project and Board Name. So the data was collected under "team" DB collection but the collector is not pulling data for issues.

These are the logs

2019-04-01 15:17:00,018 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 boards.
2019-04-01 15:17:01,348 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-01T15:16:00.017 0        1s
2019-04-01 15:17:01,357 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-04-01 15:18:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-01 15:18:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-01 15:18:00,008 INFO  c.c.d.collector.CollectorTask - https://jira.com/
2019-04-01 15:18:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-01 15:18:00,008 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-01 15:18:00,009 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 8. Collector is only collecting updated/new issues.

Can you please help me with this issue.
If you need more information please let me know.

**Comment by Sbrenthughes** [comment]
Can you post properties

**Comment by IATVirtusa** [comment]
Even i had the same issue . here i am posting my properties file
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=[localhost:27017,127.0.0.1:27017,127.0.0.:27017]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/1 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY

feature.jiraBaseUrl=https://iatvirtusa.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=SUFUVmlydHVzYUBnbWFpbC5jb206SUFUVmlydHVzYTEyMyQ=

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
		feature.jiraOauthRedirecturi=
		feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story,Task,Bug

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10021

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10018

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10023

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

**Comment by IATVirtusa** [comment]
2019-04-02 16:45:00,062 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-02 16:45:00,063 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:45:00,092 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-04-02 16:45:00,092 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-04-02 16:45:00,680 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-04-02 16:45:01,672 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-02T16:44:00.396 0        1s
2019-04-02 16:45:01,724 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-04-02 16:46:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-02 16:46:00,370 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:46:00,370 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-02 16:46:00,370 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:46:00,371 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-04-02 16:46:00,371 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-04-02 16:46:00,492 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-04-02 16:46:02,150 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-02T16:45:00.681 0        1s
2019-04-02 16:46:02,209 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-04-02 16:47:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-02 16:47:00,303 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:47:00,304 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-02 16:47:00,304 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:47:00,304 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-04-02 16:47:00,305 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-04-02 16:47:00,463 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-04-02 16:47:01,325 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-02T16:46:00.531 0        1s
2019-04-02 16:47:01,614 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-04-02 16:48:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-02 16:48:00,145 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:48:00,145 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-02 16:48:00,146 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:48:00,146 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-04-02 16:48:00,146 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-04-02 16:48:00,235 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-04-02 16:48:01,323 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-02T16:47:00.463 0        1s
2019-04-02 16:48:01,324 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-04-02 16:49:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-02 16:49:00,005 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:49:00,005 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-02 16:49:00,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:49:00,006 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-04-02 16:49:00,006 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-04-02 16:49:00,041 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-04-02 16:49:01,010 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-02T16:48:00.236 0        1s
2019-04-02 16:49:01,021 INFO  c.c.d.collector.CollectorTask - Finished                         1s

**Comment by meghnakale** [comment]
Hey sorry for the late reply.

Here is my application.properties file

`# Database Name
dbname=dashboard

# Database HostName - default is localhost
dbhost=127.0.0.1

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=127.0.0.1:27017

# Database Username - default is blank
dbusername=dbuser

# Database Password - default is blank
dbpassword=*********

# Logging File location
logging.file=./logs/jira.log
#logging.level.com.atlassian.jira=INFO
logging.level.com.capitalone.dashboard=DEBUG
logging.level.com.capitalone.dashboard.collector=DEBUG

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=50

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2018-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/1 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=https://jira.com/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=*****************************************

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
                feature.jiraOauthRedirecturi=
                feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story,Epic

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_XXXXX

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_XXXX

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customefield_XXXX

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

#Additional Parameters
#feature.jiraSprintDataFieldName=customfield_10007
#feature.jiraEpicIdFieldName=customfield_10003
#feature.jiraStoryPointsFieldName=customfield_10004
#feature.jiraTeamFieldName=customfield_11248
#feature.collectorItemOnlyUpdate=false
#feature.maxNumberOfFeaturesPerBoard=8000
`

**Comment by Sbrenthughes** [comment]
1) Go here `https://<URL>/rest/api/2/issuetype` and get the ids of the issuetypes that you want to pull.
2) Gor each issuetype execpt epic you need to add the following:
`feature. jiraStoryIds[0]=<id_from_above>`
`feature. jiraStoryIds[1]=<next_id_from_above>`
3) Get the epic id from step 1 and add it here: 
`feature.jiraEpicId=`
4) Make sure each of the following are field out correctly:
```
feature.jiraSprintDataFieldName=
feature.jiraEpicIdFieldName=
feature.jiraStoryPointsFieldName=
feature.jiraTeamFieldName=
```
5) Once the above has be verified to be correct, delete the Team, Scope and Feature collections. Finally, in the `collectors` collection find the Jira collector and set `lastRefreshTime` and `lastExecuted` to `0`

**Comment by meghnakale** [comment]
Thanks for a quick response.

So delete the Team, Scope and Feature collections from mongo DB correct? And when I re-run the collector will these collectors get created ?

**Comment by Sbrenthughes** [comment]
Yes they will be recreated. But make sure you have updated the 1-4 correctly.

**Comment by meghnakale** [comment]
Problem ... @Sbrenthughes 
The restarted the collector with the change mentioned by you.
getting null pointer errrr

2019-04-02 16:01:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-02 16:01:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:01:00,010 INFO  c.c.d.collector.CollectorTask - https://mountdiablo.jira.com/
2019-04-02 16:01:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-02 16:01:00,010 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-04-02 16:01:00,010 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 5. Collector is only collecting updated/new issues.
2019-04-02 16:01:00,016 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 2 projects.
2019-04-02 16:01:01,398 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:365) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_201]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:356) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:322) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$6(FeatureCollectorTask.java:256) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_201]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:252) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:153) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:46) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.co

**Comment by meghnakale** [comment]
@Sbrenthughes The changes mentioned by you are as per the latest commits with respect to the multiple jira Ids. I have an instance where I have setup Hygieia on the older version (before 12 days). Can you guide me on it. 
Can you help me with the JIRA Apis through which I can verify the customfield IDS  ?

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/jira.md shows how you can find custom fields

**Comment by IATVirtusa** [comment]
still getting the same , i updated above all
2019-04-03 16:40:00,016 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-03 16:40:00,017 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-03 16:40:00,017 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-03 16:40:00,033 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-03 16:40:00,035 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-03 16:40:00,091 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 boards.
2019-04-03 16:40:05,259 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-03T16:37:57.167 0        5s
2019-04-03 16:40:05,273 INFO  c.c.d.collector.CollectorTask - Finished                         5s
2019-04-03 16:41:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-03 16:41:00,024 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-03 16:41:00,025 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-03 16:41:00,025 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-03 16:41:00,026 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-03 16:41:00,026 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-03 16:41:00,030 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 boards.
2019-04-03 16:41:00,892 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-03T16:40:00.091 0        0s
2019-04-03 16:41:00,896 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-04-03 16:42:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-03 16:42:00,031 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-03 16:42:00,031 INFO  c.c.d.collector.CollectorTask - https://iatvirtusa.atlassian.net/
2019-04-03 16:42:00,033 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-03 16:42:00,033 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-03 16:42:00,033 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-04-03 16:42:00,038 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 boards.
2019-04-03 16:42:01,040 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-04-03T16:41:00.030 0        1s
2019-04-03 16:42:01,046 INFO  c.c.d.collector.CollectorTask - Finished                         1s

**Comment by Sbrenthughes** [comment]
The collector says that it’s collecting from today. Did you delete the collections mentioned?

**Comment by gopiprasanthpotipireddy** [comment]
> @Sbrenthughes The changes mentioned by you are as per the latest commits with respect to the multiple jira Ids. I have an instance where I have setup Hygieia on the older version (before 12 days). Can you guide me on it.
> Can you help me with the JIRA Apis through which I can verify the customfield IDS ?

feature.jiraTeamFieldName=customefield_XXXX  make this blank if you want to use board mode and for older versions 
feature.jiraStoryId=xxxxx. should be set 
it will collect only stories. the new master has code for all. it worked for me thank you.

**Comment by continuum-vikrant-tyagi** [comment]
https://github.com/Hygieia/Hygieia/issues/2979#issuecomment-519777039

**Comment by Navya-V** [comment]
what happens if i delete feature collection from mongodb manually? will it be recreated after i rub the command for jira collector?

**Comment by continuum-vikrant-tyagi** [comment]
yes it will recreate again feature collection.

**Comment by Navya-V** [comment]
thanks @continuum-vikrant-tyagi

**Comment by Navya-V** [comment]
i am able to fetch type=story ,i am not able to get all tasks that are epics .though i have configured properties 
feature.jiraIssueTypeNames=Story,Task,Epic
feature.jiraIssueTypeID=Story
feature.collectorItemOnlyUpdate=false
feature.jiraSprintDataFieldName=customfield_10020
feature.jiraEpicIdFieldName=customfield_10014
feature.jiraStoryPointsFieldName=customfield_10016
feature.jiraTeamFieldName=
feature.jiraBoardAsTeam=true

what may be the issue? 
can anyone help

**Comment by No6-start** [comment]
The same question

2019-12-17 15:00:00,652 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Refreshing issues for Team ID:10502
2019-12-17 15:00:00,741 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=http://10.1.135.25:8080/rest/agile/1.0/team/10502/issue?jql=issueType in ('Task') and updatedDate>='2019/11/17 15:00'&fields=id&startAt=0 status=404 duration=68
2019-12-17 15:00:00,742 [taskScheduler-1] ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: http://10.1.135.25:8080/rest/agile/1.0/team/10502/issue?jql=issueType in ('Task') and updatedDate>='2019/11/17 15:00'&fields=id&startAt=0
2019-12-17 15:00:00,745 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Team Issues Refreshed            0s
2019-12-17 15:00:00,748 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collected 0 teams and 21 projects
2019-12-17 15:00:00,754 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-12-17 15:00:01,605 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=http://10.1.135.25:8080/rest/api/2/search?jql=project=10502 and issueType in ('Task') and updatedDate>='2019/11/17 15:00'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,,customfield_10000,customfield_10002,customfield_10003&startAt=0 status=200 duration=850
2019-12-17 15:00:01,620 [taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:402) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:393) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:359) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$6(FeatureCollectorTask.java:262) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:258) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:159) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.9.jar!/:3.1.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by No6-start** [comment]
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=http://1.1.1.1:8080
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=ZHkteGppbnl1OlpoYW53YW5nMDAw
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Task
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=
feature.collectorItemOnlyUpdate=true
feature.maxNumberOfFeaturesPerBoard=1000
feature.refreshTeamAndProjectHours=1
feature.jiraStoryIds[0]=3

**Comment by No6-start** [comment]
This is my configuration，It's a problem there

**Comment by Navya-V** [comment]
Anybody help!!!!

**Comment by cernenwein** [comment]
any updates on this?
