### ISSUE TITLE
Jira - Failed to collect jira information: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by hungrypanda** [Hygieia/Hygieia#2809]
Collector throwing error while pulling data for the boards:

`2019-04-02 11:11:00,005 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 2 boards.
2019-04-02 11:11:00,991 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:365) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_201]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:356) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:267) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$7(FeatureCollectorTask.java:271) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_201]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:268) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:153) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:46) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
`

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/Hygieia/issues/2807#issuecomment-478969586

**Comment by Sbrenthughes** [comment]
@hungrypanda Update?

**Comment by Sbrenthughes** [comment]
Closing due to inactivity. Reopen if you require further assistance
