### ISSUE TITLE
Github Collector 401 unauthorized error on UI.

### ISSUE THREAD

**Issue by sudhanshusr** [Hygieia/Hygieia#2820]
Github Collector is showing 401 unauthorised issue on UI. 

#github.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false	
logging.file=./logs/github.log
github.cron=0 0/5 * * * *
github.host=github.com
github.commitThresholdDays=15
github.errorThreshold=1

#Key Generated by Hygiea-Core also added to api.properties as key
github.key=GZGhoUnq+2u2qywEpHWhkUWukWvQ1WIg 

#Generated from developer setting github
github.personalAccessToken=829bb3ddae294945a3xxxxxxxxxxxxxxxxx

java -jar github-scm-collector-3.0.2-SNAPSHOT.jar --spring.config.name=github --spring.config.location=C:\Devops\Hygieia\Hygieia\collectors\scm\github\target\github.properties

![image](https://user-images.githubusercontent.com/10558551/55715690-e5091680-5a12-11e9-8f59-9e6a3a622227.png)

![image](https://user-images.githubusercontent.com/10558551/55715620-b8ed9580-5a12-11e9-8a0a-e415bd749ce2.png)

**Comment by Sbrenthughes** [comment]
Delete the widget from UI and re add it. Then add the the personal access token from the UI and remove from properties file. I would also suggest updating `github.errorThreshold=1` to `github.errorThreshold=10` or more

**Comment by Sbrenthughes** [comment]
With adding the personal access token for your private repo to the UI and deleting and recreating the widget, you still get unauthorized?

**Comment by sudhanshusr** [comment]
Getting Below error for private repository:

2019-04-09 23:40:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-04-09 23:40:00,053 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:1183}] to localhost:27017
2019-04-09 23:40:00,073 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-09 23:40:00,074 INFO  c.c.d.collector.CollectorTask - Starting...
2019-04-09 23:40:00,076 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-09 23:40:00,425 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=to-shared-cluster, userID=, url=https://github.com/xxxxxxx-ds/maxxxxx-geo-coding}::to-shared-cluster:: get commits
2019-04-09 23:40:00,478 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Input length must be multiple of 8 when decrypting with padded cipher
2019-04-09 23:40:00,479 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/https://github.com/xxxxxxx-ds/maxxxxx-geo-coding/commits?sha=to-shared-cluster&since=2019-03-26T23:40Z
2019-04-09 23:40:02,234 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/https://github.com/xxxxxxx-ds/maxxxxx-geo-coding
org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:598) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:198) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_201]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]
2019-04-09 23:40:02,264 INFO  c.c.d.collector.CollectorTask - Repo Count              1        2s
2019-04-09 23:40:02,266 INFO  c.c.d.collector.CollectorTask - New Commits             0        2s
2019-04-09 23:40:02,267 INFO  c.c.d.collector.CollectorTask - New Pulls               0        2s
2019-04-09 23:40:02,268 INFO  c.c.d.collector.CollectorTask - New Issues              0        2s
2019-04-09 23:40:02,271 INFO  c.c.d.collector.CollectorTask - Finished                         2s
2019-04-09 23:41:44,079 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:6, serverValue:1183}] to localhost:27017 because it is past its maximum allowed idle time.

**Comment by Sbrenthughes** [comment]
`GZGhoUnq+2u2qywEpHWhkUWukWvQ1WIg` is also in the API properties?

**Comment by sudhanshusr** [comment]
Yes below us is my api.properties:

# api.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
key=GZGhoUnq+2u2qywEpHWhkUWukWvQ1WIg

**Comment by Sbrenthughes** [comment]
What command are you using to run the API?

**Comment by sudhanshusr** [comment]
java -jar api.jar --spring.config.location=C:\Devops\Hygieia\Hygieia\api\target\api.properties

**Comment by Sbrenthughes** [comment]
I have replied to you on gitter.

**Comment by Sbrenthughes** [comment]
`- {password=, personalAccessToken=ERROR, branch=to-shared-cluster, userID=, url=https://github.com/xxxxxxx-ds/maxxxxx-geo-coding}::to-shared-cluster:: get commits`. `personalAccessToken=ERROR` is your issue here.

**Comment by sudhanshusr** [comment]
19-04-18 16:55:00,034 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-18 16:55:00,034 INFO  c.c.d.collector.CollectorTask - Starting...
2019-04-18 16:55:00,035 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-18 16:55:00,287 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=/jou92BTu8Sxxxxxxxxxxxxxxxxxxxxth+vOnTrqdHCtbskG4/m63AY2RYwuU, branch=to-shared-cluster, userID=, url=https://github.com/pxxxxxxxs-ds/mxiX-xxxxxxxxxxing}::to-shared-cluster:: get commits
2019-04-18 16:55:00,326 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
2019-04-18 16:55:00,327 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos//pxxxxxxxs-ds/mxiX-xxxxxxxxxxing/commits?sha=to-shared-cluster&since=2019-04-04T16:55Z
2019-04-18 16:55:01,940 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com//pxxxxxxxs-ds/mxiX-xxxxxxxxxxing
org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:598) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:198) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_201]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]
2019-04-18 16:55:01,951 INFO  c.c.d.collector.CollectorTask - Repo Count              1        1s
2019-04-18 16:55:01,951 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2019-04-18 16:55:01,952 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s
2019-04-18 16:55:01,952 INFO  c.c.d.collector.CollectorTask - New Issues              0        1s
2019-04-18 16:55:01,953 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-04-18 16:56:40,349 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:7, serverValue:43}] to localhost:27017 because it is past its maximum allowed idle time.




Now getting this issue

**Comment by zerolaser** [comment]
@Sbrenthughes I got the same issue where It was throwing personalAccessToken=ERROR. I was setting it from the Widget. but still it was throwing the error. I don't understand why it isn't taking the token from UI. I tried setting it from properties file still no change. 

also looking at the log it was pulling the data from current date
```
2019-05-14 21:08:01,942 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://github.company.com/api/v3/repos/assort-visual/av-web-workspace/commits?sha=master&since=2019-05-14T20:45Z

``` 

adding more logs...

```
2019-05-14 21:08:01,900 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.company.com/assort-visual/av-web-workspace}::master:: get commits
2019-05-14 21:08:01,941 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-05-14 21:08:01,942 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://github.company.com/api/v3/repos/assort-visual/av-web-workspace/commits?sha=master&since=2019-05-14T20:45Z
2019-05-14 21:08:01,951 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-05-14 21:08:02,642 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.company.com/assort-visual/av-web-workspace
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:604) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:107) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:198) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
```

**Comment by rvema** [comment]
@zerolaser Can you get the latest code frommaster branch and retry? If this is still an issue please let us know

**Comment by gopiprasanthpotipireddy** [comment]
@rvema i tried the latest code i am getting the same error. 

> {password=, personalAccessToken=ERROR, branch=to-shared-cluster, userID=, url=https://github.com/xxxxxxx-ds/maxxxxx-geo-coding}::to-shared-cluster:: get commits

**Comment by gopiprasanthpotipireddy** [comment]
2019-06-10 15:49:30,003 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-10 15:49:30,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:49:30,019 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master:: get commits
2019-06-10 15:49:30,020 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:49:30,020 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/commits?sha=master&since=2019-06-10T15:39Z
2019-06-10 15:49:30,330 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master get issues
2019-06-10 15:49:30,330 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:49:30,332 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/issues?state=all&since=2019-06-10T15:39Z
2019-06-10 15:49:30,630 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master::get pulls
2019-06-10 15:49:30,631 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:49:30,632 INFO  c.c.d.collector.DefaultGitHubClient - Executing [https://api.github.com/repos/IATVirtusa/devops/pulls?state=all&base=master&sort=updated&direction=desc
2019-06-10 15:49:30,940 INFO  c.c.d.collector.DefaultGitHubClient - pr 2 changed publish step to QA from Dev
2019-06-10 15:49:30,940 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:49:31,242 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:49:31,519 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:49:31,825 INFO  c.c.d.collector.CollectorTask - Repo Count              1        1s
2019-06-10 15:49:31,825 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2019-06-10 15:49:31,827 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s
2019-06-10 15:49:31,830 INFO  c.c.d.collector.CollectorTask - New Issues              0        1s
2019-06-10 15:49:31,831 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-06-10 15:50:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-06-10 15:50:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:50:00,012 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-10 15:50:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:50:00,040 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master:: get commits
2019-06-10 15:50:00,041 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:00,046 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/commits?sha=master&since=2019-06-10T15:39Z
2019-06-10 15:50:00,338 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master get issues
2019-06-10 15:50:00,338 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:00,340 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/issues?state=all&since=2019-06-10T15:39Z
2019-06-10 15:50:00,618 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master::get pulls
2019-06-10 15:50:00,620 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:00,622 INFO  c.c.d.collector.DefaultGitHubClient - Executing [https://api.github.com/repos/IATVirtusa/devops/pulls?state=all&base=master&sort=updated&direction=desc
2019-06-10 15:50:01,114 INFO  c.c.d.collector.DefaultGitHubClient - pr 2 changed publish step to QA from Dev
2019-06-10 15:50:01,114 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:01,378 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:01,644 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:02,000 INFO  c.c.d.collector.CollectorTask - Repo Count              1        1s
2019-06-10 15:50:02,000 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2019-06-10 15:50:02,001 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s
2019-06-10 15:50:02,005 INFO  c.c.d.collector.CollectorTask - New Issues              0        1s
2019-06-10 15:50:02,005 INFO  c.c.d.collector.CollectorTask - Finished                         1s
2019-06-10 15:50:30,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-06-10 15:50:30,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:50:30,003 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-10 15:50:30,006 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:50:30,019 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master:: get commits
2019-06-10 15:50:30,019 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:30,020 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/commits?sha=master&since=2019-06-10T15:40Z
2019-06-10 15:50:30,303 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master get issues
2019-06-10 15:50:30,304 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:30,305 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/issues?state=all&since=2019-06-10T15:40Z
2019-06-10 15:50:30,592 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master::get pulls
2019-06-10 15:50:30,594 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:30,594 INFO  c.c.d.collector.DefaultGitHubClient - Executing [https://api.github.com/repos/IATVirtusa/devops/pulls?state=all&base=master&sort=updated&direction=desc
2019-06-10 15:50:30,972 INFO  c.c.d.collector.DefaultGitHubClient - pr 2 changed publish step to QA from Dev
2019-06-10 15:50:30,972 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:31,242 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:31,517 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:50:31,844 INFO  c.c.d.collector.CollectorTask - Repo Count              1        1s
2019-06-10 15:50:31,845 INFO  c.c.d.collector.CollectorTask - New Commits             0        1s
2019-06-10 15:50:31,849 INFO  c.c.d.collector.CollectorTask - New Pulls               0        1s

**Comment by gopiprasanthpotipireddy** [comment]
2019-06-10 15:52:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-06-10 15:52:00,007 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:52:00,007 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-10 15:52:00,011 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 15:52:00,083 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master:: get commits
2019-06-10 15:52:00,084 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-06-10 15:52:00,092 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/IATVirtusa/devops/commits?sha=master&since=2019-06-10T15:41Z
2019-06-10 15:52:00,466 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.com/IATVirtusa/devops}::master get issues
2019-06-10 15:52:00,467 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message

**Comment by Sbrenthughes** [comment]
@gopiprasanthpotipireddy can you paste your api and github properties?
