### ISSUE TITLE
NullPointer for Jira Collector

### ISSUE THREAD

**Issue by sudhanshusr** [Hygieia/Hygieia#2821]
#application.properties for JIRA colllector
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]
dbusername=dashboarduser
dbpassword=dbpassword
logging.file=./logs/jira.log
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=http://pxxxxdevkb.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=RWt0YV9UaGFrdXJAcGFwYWpxxxxxxxxxxxxxxxxxxxxxx

# OAuth is not fully implemented; please blank-out the OAuth values:

#feature.jiraOauthAuthtoken=
#feature.jiraOauthRefreshtoken=
#feature.jiraOauthRedirecturi=
#feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story, Epic

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10016

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10017

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10021

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
#feature.jiraTeamFieldName=

#############################################################################
# In Jira, your instance will have its own Id for the issueTypes. 
# You can retrieve the issueType IDs from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
feature.jiraStoryIds[0]=60711
#feature.jiraStoryIds[1]=

#############################################################################
# In Jira, your instance will have its own Id for the Epic
# You can find the value from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
#feature.jiraEpicId=54614

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
#feature.collectorItemOnlyUpdate=

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
#feature.maxNumberOfFeaturesPerBoard=

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

Error on Collector Console:

2019-04-09 19:15:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-09 19:15:00,013 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-09 19:15:00,014 INFO  c.c.d.collector.CollectorTask - http://pjolodevkb.atlassian.net/
2019-04-09 19:15:00,015 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-09 19:15:00,016 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-09 19:15:00,017 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 431893. Collector is about to refresh Team/Board information
2019-04-09 19:15:00,348 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at java.io.StringReader.<init>(Unknown Source) ~[na:1.8.0_201]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:79) ~[json-simple-1.1.1.jar!/:na]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getBoards(DefaultJiraClient.java:168) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateTeamInformation(FeatureCollectorTask.java:170) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:137) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:46) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.1-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_201]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]

Note: I have tried Deleting Team, Scope, Feature Collection, Also removed the Jira entry from collector collection but issue persist. Before deleting these i was able to see my boards in UI but now nothing i can see. Its new and failing.

**Comment by Sbrenthughes** [comment]
jiraEpicId is a required field.

**Comment by sudhanshusr** [comment]
Added Epic ID error as well error is still the same. Yes, the above URL is returning data.

**Comment by Sbrenthughes** [comment]
The reason you are getting a null pointer is because that api is returning null.

**Comment by sudhanshusr** [comment]
Any Suggestion for the fix?

**Comment by Sbrenthughes** [comment]
Can you put a  a ` LOGGER.info` right before that line and print out the URL it is getting that error for?

**Comment by sudhanshusr** [comment]
Added LOGGER.info for url 
o/p: http://pxjixxxx.atlassian.net/rest/agile/1.0/board?startAt=0 
Verified above URL on the browser it is returning data.

Added LOGGER.info for responseBody
O/p: null

**Comment by Sbrenthughes** [comment]
Can you see put a logger. info to see what the http response code is?

**Comment by sudhanshusr** [comment]
I have added LOGGER.info like this.

try {
                ResponseEntity<String> responseEntity = makeRestCall(url);
				LOGGER.info("Print " + url);
				String responseBody = responseEntity.getBody();
				LOGGER.info("Print" + responseBody);
                JSONObject teamsJson = (JSONObject) parser.parse(responseBody);

Can't find response code variable in the source code. Can you please help on this?

**Comment by Sbrenthughes** [comment]
We have resolved the null pointer. It had to do with you using http instead of https. I am closing this issue.
