### ISSUE TITLE
SASL SCRAM-SHA-1 authentication failed for dashboarduser on dashboarddb from client

### ISSUE THREAD

**Issue by mySphere** [Hygieia/Hygieia#2846]
I am getting an error after reverting back from mongodb 4.0 to 3.4, as suggested here.  I validated that the user exists and is able to authenticate (using mongod and then mongo...).

SASL SCRAM-SHA-1 authentication failed for dashboarduser on dashboarddb from client XX.XX.XX.XX:XXXXX; UserNotFound: Could not find user dashboarduser@dashboarddb

Also, seeing the below error in logs:  (could the issue be related to somehow mongodb shell being used is v4.0.6, whereas i had removed 4.0 and installed 3.4)

db_1                           | 2019-04-22T23:50:46.494+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
db-setup_1                     | MongoDB shell version v4.0.6
db-setup_1                     | connecting to: mongodb://db:27017/admin?gssapiServiceName=mongodb
db-setup_1                     | 2019-04-22T23:50:45.841+0000 E QUERY    [js] Error: couldn't connect to server db:27017, connection attempt failed: SocketException: Error connecting to db:27017 (172.18.0.2:27017) :: caused by :: Connection refused :
db-setup_1                     | connect@src/mongo/shell/mongo.js:343:13
db-setup_1                     | @(connect):1:6
db-setup_1                     | exception: connect failed

Thanks for any help or suggestions.

**Comment by Sbrenthughes** [comment]
What command are you running mongo with?

**Comment by mySphere** [comment]
The first error (auth) got resolved as I believe it was related to where the property file needs to be placed.  Even though the property file that I had updated had dashboarddb, there was another property file saved in location hygieia/src/main/resources/, which has the dashboard as the db (which I don't recall putting one there but who knows after all the debugging changes...)

For the second error, 
mongod - opens and wait for connection
mongo - i am able to connect to db and query 

But, when I do the, docker-compose up --force-recreate -d
The logs show the error noted in prior post.  

Couple of updates since then.... (incl above error)
1) Sonar collector - works and dashboard is able to show the data.
2) Jenkins collector - mongodb timeout - socket exception (log error below)
   - 2.1) why (or from where) is the mongodb_host being set to 27017, in property file its not set as such (verified)
   - 2.2) what should be the location for the application.properties file?
3) Feature JIRA collector - mongodb timeout - socket exception (log error below)
   - 3.1) why (or from where) is dbhost getting set to 27017, its not in the property file (verified)

I have included both scenarios in this issue, as both seems to be related to the same issue.
Thanks for any ideas or suggestions.

==============================================================
Jenkins error: (from the log)
[XXXXXXXXXXX hygieia]# docker logs ae3360210278
MONGODB_HOST: 27017
MONGODB_PORT: 27017
===========================================
Properties file created Thu Apr 25 23:38:04 UTC 2019:  config/hygieia-jenkins-build-collector.properties
Note: passwords & apiKey hidden
===========================================
dbname=dashboarddb
dbhost=27017
dbport=27017
dbusername=dashboarduser

>>>> further down, from the log...

2019-04-26 13:32:47,828 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
        ... 3 common frames omitted
==============================================================

==============================================================
Feature JIRA collector log:
=================
[XXXXXXXXXX hygieia]# docker logs 361e1192e1c6
MONGODB_HOST: 27017
MONGODB_PORT: 27017

===========================================
Properties file created:  /hygieia/config/application.properties
Note: passwords hidden
===========================================
dbname=dashboarddb
dbhost=27017
dbport=27017
dbusername=dashboarduser

>>>> further down, from the log...

2019-04-26 13:32:50,103 INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server 27017:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.net.ConnectException: Invalid argument (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.0.2.jar!/:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.0.2.jar!/:na]
        ... 3 common frames omitted

==============================================================

**Comment by mySphere** [comment]
This error seems to be related to spring mongoautoconfiguration discussed here - https://github.com/spring-projects/spring-boot/issues/4807

Can anyone confirm that is the case and if so how they got it resolved?

Jenkins Log:
-------------
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:370)
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
        at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:166)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:394)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:57)
        at com.mongodb.Mongo.execute(Mongo.java:738)
        at com.mongodb.Mongo$2.execute(Mongo.java:725)
        at com.mongodb.DBCollection.findOne(DBCollection.java:737)
        at com.mongodb.DBCollection.findOne(DBCollection.java:710)
        at com.mongodb.DBCollection.findOne(DBCollection.java:657)
        at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2080)
        at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2064)
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:1839)
        ... 45 more
