### ISSUE TITLE
Nexus IQ NullPointerException Getting Username

### ISSUE THREAD

**Issue by ewh0005** [Hygieia/Hygieia#2867]
I am currently trying to configure and run the Nexus IQ collector for Hygieia, but I am currently getting the following error when the collector runs: 

```
2019-05-01 12:35:00,186 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-01 12:35:00,187 INFO  c.c.d.collector.CollectorTask - https://my.nexus.iq.url
2019-05-01 12:35:00,187 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-01 12:35:00,195 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultNexusIQClient.createHeaders(DefaultNexusIQClient.java:392) ~[nexus-iq-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultNexusIQClient.parseAsObject(DefaultNexusIQClient.java:335) ~[nexus-iq-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultNexusIQClient.getApplications(DefaultNexusIQClient.java:73) ~[nexus-iq-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.NexusIQCollectorTask.collect(NexusIQCollectorTask.java:84) ~[nexus-iq-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.NexusIQCollectorTask.collect(NexusIQCollectorTask.java:29) ~[nexus-iq-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
```

It looks to me like it is getting a NullPointer when trying to read the username, but I am including it in the config file:

```
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=my.db.ip.address

# Database Port - default is 27017
dbport=27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Collector schedule (required)
nexusiq.cron=0 0/5 * * * *

# Nexus IQ server(s) (required) - Can provide multiple
nexusiq.servers[0]=https://my.nexus.iq.url

# Nexus IQ username/password - with read-access to all reports, and so on.
nexusiq.username=myUsername
nexusiq.password=myPassword

logging.level.com.capitalone.dashboard.collector=DEBUG

#In case of multiple license violations for a given library, consider the strictest violation
nexusiq.selectStricterLicense=true
```

(I have replaced my urls, credentials, ips, etc. with placeholder values).

It looks like it is finding my properties file, as my NexusIQ url is correctly loaded, but it does not seem to be able to find the username for some reason. Am I configuring something incorrectly, or is there an issue with how the properties file is loaded in the collector?

**Comment by Booma-Baskaran** [comment]
As far as I know Nexus IQ Scan used to capture/scan open source vulnerabilities in an applications such as License, Security and Policy Alerts. Not sure, it can capture Build violations. Hygieia captures only open source vulnerabilities in an applications and not build violation or so.
