### ISSUE TITLE
Connection timed out: connect - while trying to connect Jira using Jira Collector

### ISSUE THREAD

**Issue by AbhiAuto** [Hygieia/Hygieia#2886]
2019-05-10 21:15:21,136 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://uadviser.atlassian.net/rest/agile/1.0/board?startAt=0": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:784) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getBoards(DefaultJiraClient.java:166) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateTeamInformation(FeatureCollectorTask.java:170) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:137) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:46) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.1-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_181]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_181]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_181]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_181]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[na:1.8.0_181]
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[na:1.8.0_181]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_181]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:1.8.0_181]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 17 common frames omitted

**Comment by AbhiAuto** [comment]
Properties file

server.contextPath=/jira
server.port=8082

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
feature.jiraBaseUrl=https://myjira.site.net
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=emailID:Password

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10000

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10003

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

#############################################################################
# In Jira, your instance will have its own Id for the issueTypes. 
# You can retrieve the issueType IDs from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
feature.jiraStoryIds[0]=
feature.jiraStoryIds[1]=

#############################################################################
# In Jira, your instance will have its own Id for the Epic
# You can find the value from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
feature.jiraEpicId=

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
#feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=100

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

**Comment by AbhiAuto** [comment]
I have tired all  the different possible ways to get it resolved. Need help to resolve this issue.

**Comment by Sbrenthughes** [comment]
Timeout is usually associated with a proxy. Have you tried passing proxy info?

**Comment by AbhiAuto** [comment]
Yes I have tried with proxy URL and proxy port number. Stil no go. 

I am using my email address as username for jira authentication. Does that create any issues? I could see somewhere in github issues it’s mentioned that we have to use only jira username not email address. It would be great if you give some sample on how to provide the details on proxy.

**Comment by AbhiAuto** [comment]
I have provided the proxy details, now its working fine. Thank you. I have entered the proxy details wrongly.
