### ISSUE TITLE
After AD integration jenkins build connector not working

### ISSUE THREAD

**Issue by imranmaddekar** [Hygieia/Hygieia#2905]
Hi 

Post configuration of AD in Jenkins, the jenkins build collector has stopped working.  However if the build connector is pointed to a non-ad jenkins its working.  Please help if my configuration is wrong or if AD user can't be configured in application.propertiesfile.

**### **Error:****
2019-05-16 06:15:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2019-05-16 06:15:00,018 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:846, serverValue:4730}] to 127.0.0.1:27017
2019-05-16 06:15:00,019 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:87) ~[jenkins-build-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.HudsonCollectorTask.getCollector(HudsonCollectorTask.java:42) ~[jenkins-build-collector-3.0.1.jar!/:3.0.1]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-3.0.4.jar!/:3.0.1]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**application.propertiesfile**

Config 1:
jenkins.server[0]=http://my-jenkins.com
jenkins.usernames[0]=AD_USER_NAME
jenkins.apiKeys[0]=<<API-TOKEN>>

Config 2:
jenkins.servers[0]=http://AD_USER_NAME:<<API-TOKEN>>@my-jenkins.com

Config 3:
jenkins.server[0]=http://my-jenkins.com
jenkins.usernames[0]=AD_USER_NAME
jenkins.apiKeys[0]=AD_USER_PASSWORD

**Comment by Sbrenthughes** [comment]
Can you try with https? This is the configuration I use with ad.
`jenkins.servers[0]=https://AD_USER_NAME:<>@my-jenkins.com`

**Comment by Sbrenthughes** [comment]
But this error is only coming when `jenkins.servers[0]=` is null. Do you have any special characters in your password?

**Comment by imranmaddekar** [comment]
Thanks @Sbrenthughes  !!
In addition to this config =>> jenkins.servers[0]=https://AD_USER_NAME:<>@my-jenkins.com
I used below 
jenkins.usernames[0]=
jenkins.apiKeys[0]=

Collector started working again.

Earlier it was a commented
#jenkins.usernames[0]=
#jenkins.apiKeys[0]=

I dont understand why comments need to be removed as these properties doesn't have the significance as the user and token is being passed in URL itself.

**Comment by imranmaddekar** [comment]
Hence closing the issue
