### ISSUE TITLE
github collector 401 unauthorized 

### ISSUE THREAD

**Issue by zerolaser** [Hygieia/Hygieia#2916]
Im getting the 401 error on the UI for github collector
![image](https://user-images.githubusercontent.com/7926653/57887915-986ce400-77e5-11e9-9e99-5e2100732328.png)

Using the following application.properties  

```
# Database Name
dbname=dashboarddb
dbusername=hygieia
dbpassword=hygieiapassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.company.com
github.commitThresholdDays=45
github.errorThreshold=10
#github.key=<your-generated-key>
github.personalAccessToken=Mytoken
github.connectTimeout=2000
github.readTimeout=2000
```

Then I removed the github token from the properties file and gave the token from UI. it's still the same issue and no error in log file at all. 

I tried adding another repo to other dashboard then it threw me this error ( used the same github token for both repo's.)
I verified the token via curl its working fine. 

```
2019-05-16 21:09:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-16 21:09:00,003 INFO  c.c.d.collector.CollectorTask - Starting...
2019-05-16 21:09:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-16 21:09:00,029 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2019-05-16 21:09:00,029 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-05-16 21:09:00,029 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-05-16 21:09:00,029 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-05-16 21:09:00,029 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-05-16 21:10:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-05-16 21:10:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-16 21:10:00,003 INFO  c.c.d.collector.CollectorTask - Starting...
2019-05-16 21:10:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-16 21:10:00,046 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2019-05-16 21:10:00,046 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-05-16 21:10:00,046 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-05-16 21:10:00,046 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-05-16 21:10:00,046 INFO  c.c.d.collector.CollectorTask - Finished                         0s


2019-05-16 21:11:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-05-16 21:11:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-16 21:11:00,003 INFO  c.c.d.collector.CollectorTask - Starting...
2019-05-16 21:11:00,003 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-16 21:11:00,065 INFO  c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=ERROR, branch=master, userID=, url=https://github.company.com/vkris9/test}::master:: get commits
2019-05-16 21:11:00,065 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
null
2019-05-16 21:11:00,065 INFO  c.c.d.collector.DefaultGitHubClient - Executing https://github.company.com/api/v3/repos/vkris9/test/commits?sha=master&since=2019-05-16T21:00Z
2019-05-16 21:11:00,159 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.company.com/vkris9/test
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:598) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:198) ~[github-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
2019-05-16 21:11:00,164 INFO  c.c.d.collector.CollectorTask - Repo Count              2        0s
2019-05-16 21:11:00,164 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-05-16 21:11:00,164 INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2019-05-16 21:11:00,164 INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2019-05-16 21:11:00,164 INFO  c.c.d.collector.CollectorTask - Finished                         0s
```

@Sbrenthughes  All these issues needs to closed if this gets fixed

https://github.com/Hygieia/Hygieia/issues/2285
https://github.com/Hygieia/Hygieia/issues/2753
https://github.com/Hygieia/Hygieia/issues/2820
I tried this also https://github.com/Hygieia/Hygieia/issues/2172#issuecomment-429380602
it dint work.

**Comment by mitunmbj** [comment]
U could configure only "n" number of private repo from a single profile. one private repo from one profile and another one from another profile cannot be configured at a time

**Comment by Sbrenthughes** [comment]
First, You need `github.key=<your-generated-key>` to match the `key=<your-generated-key>` in your API properties.

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/Hygieia/pull/2919 should fix the decryption issue when passing the token from properties file. But it will not fix the configuration issue you have above.

**Comment by zerolaser** [comment]
@Sbrenthughes What exactly is the github.key here ? 
I have the github personal access token.  Do I need to create a new OAUTH application use its client secret here ?

**Comment by zerolaser** [comment]
@mitunmbj not sure what you meant here. 
I'm using two github personal access token for two different repo's im configuring from UI.

**Comment by Sbrenthughes** [comment]
> @Sbrenthughes What exactly is the github.key here ?
> I have the github personal access token. Do I need to create a new OAUTH application use its client secret here ?

https://hygieia.github.io/Hygieia/collectors.html#encryption-for-private-repos

If you are trying to use `github.personalAccessToken=Mytoken` it will fail until you update to the latest. The PR was just merged.

**Comment by Sbrenthughes** [comment]
@zerolaser any update?

**Comment by Sbrenthughes** [comment]
Close due to inactivity.
