### ISSUE TITLE
Query regarding Bitbucket collector token

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [Hygieia/Hygieia#2942]
@Sbrenthughes 

We are using bitbucket stash version 4.1.4. I am not sure if we need to generate repo key and how to generate it. i dont see any errors or auth issue but still it is not pulling any metrics from stash.

Bitbucket application.properties:
# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=********
# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=****

# Logging File location
logging.file=./logs/bitbucket.log

# Collector schedule (required)
git.cron=0 0/5 * * * *

# Mandatory parameters
git.host=http://****/rest/api/1.0/
git.api=/rest/api/1.0/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
# Set to 'cloud' to use Bitbucket Cloud (formerly known as Bitbucket)
# Set to 'server' to use Bitbucket Server (formerly known as Stash)
# More information can be found here:   
        https://github.com/capitalone/Hygieia/issues/609
        git.product=server

# Bitbucket key for private repos
 bitbucket.key=<your-generated-key>

logs:
2019-05-30 14:35:00,265 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:632}] to *****:27017
2019-05-30 14:35:00,345 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-30 14:35:00,345 INFO  c.c.d.collector.CollectorTask - Starting...
2019-05-30 14:35:00,345 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-30 14:35:00,503 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2019-05-30 14:35:00,503 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-05-30 14:35:00,503 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-05-30 14:36:21,088 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:6, serverValue:632}] to *****:27017 because it is past its maximum allowed idle time.

**Comment by Sbrenthughes** [comment]
Did you create a dashboard with an scm widget?

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes Thanks , you mean Configure Code Repo Widget ??

**Comment by Sbrenthughes** [comment]
Yes configure it and then the collector should try to collect

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes it is not allowing to configure in the frontend 

![image](https://user-images.githubusercontent.com/32649250/58664449-a437ca80-82fc-11e9-8240-a3a051c6823b.png)

**Comment by Sbrenthughes** [comment]
Can you post your api properties

**Comment by ajayakumar-jayaraj** [comment]
Thanks @Sbrenthughes , I am able to configure repo widget now and run the collector . but it is not pulling up metrics and failing with below error.

2019-05-31 10:00:00,342 INFO  c.c.d.collector.CollectorTask - Starting...
2019-05-31 10:00:00,342 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-05-31 10:00:00,917 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://*****/rest/api/1.0/projects/projects/projects/repos/***/browse/commits?until=master&limit=25
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]


here is my api properties 

spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_DATABASE
          value: dashboarddb
        - name: SPRING_DATA_MONGODB_HOST
          value: hygieia-***
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: *****
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: dashboarduser
        - name: AUTH_EXPIRATION_TIME
          value: "7200000"
        - name: AUTH_AUTHENTICATION_PROVIDERS
          value: STANDARD
        - name: AUTH_SECRET
          value: hygieia**
        image: gcr.io/****

**Comment by Sbrenthughes** [comment]
@shishirchaturvedi can you provide your thoughts here?

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Looking at your log my guess is that you git.host is wrong. Git host should be proper bitbucket server url.
example config,
```java
git.host=https://bitbucket.server.com/
git.api=/rest/api/1.0/
git.username=bitbucket_user
git.password=secret
```

**Comment by ajayakumar-jayaraj** [comment]
same error @Sbrenthughes @shishirchaturvedi 

2019-05-31 17:20:00,490 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://***/rest/api/1.0/projects/projects/repos/MSA/repos/atd-microservices/browse/commits?until=master&limit=20
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:235) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:148) [bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
2019-05-31 17:20:00,622 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2019-05-31 17:20:00,622 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-05-31 17:20:00,622 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj  
http://***/rest/api/1.0/projects/projects/repos/MSA/repos/atd-microservices/**browse**/commits?until=master&limit=20

I see **browse** in the rest API URL. This is wrong. There should not be a browse in API URL. This might have happened due to wrong Repo URL in the configuration of repo widget. Can you please share your repo URL which you have used in the configuration of your repo widget.

**Comment by ajayakumar-jayaraj** [comment]
I corrected the repo url ,
this is url in the widget http://<hostname>/scm/msa/**-microservices

Application.properties:
git.host=****
git.api=/rest/api/1.0/
git.username=***
git.password=***

I am getting 401 unauthorized error now:

2019-06-01 06:10:00,290 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-01 06:10:00,291 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-01 06:10:00,291 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-01 06:10:00,722 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://******/rest/api/1.0/projects/msa/repos/**-microservices/commits?until=master&limit=20
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.makeRestCall(DefaultBitbucketServerClient.java:235) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:90) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Can you successfully get a response from bitbucket server from the [Postman](https://www.getpostman.com/) or using any other rest client. I suspect the user and credentials which you are using is unauthorized. Also please use encrypt credentials in `git.password = ***`.

**Comment by ajayakumar-jayaraj** [comment]
yes @shishirchaturvedi  I am able to see response in postman. I tried encrypt password with base64 and rerun even same 401 unauthorized error.

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Can you try configuring username and password in the repo widget configuration.  The current implementation is using the username/password(encrypted) from the repo widget configuration.

**Comment by ajayakumar-jayaraj** [comment]
> https://github.com/Hygieia/Hygieia/pull/2678/files#diff-9bb51a759b60fb0dbc004798bba7a269R28

Hi @shishirchaturvedi  I removed credentials on application.properties and updated in repo widget with password (encrypted with base64). I still face the same issue.

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Can you try this curl command to ensure that your credentials are correct -
```bash
curl https://bitbucket.server.com/rest/api/1.0/projects/my_project_name/repos/repo_name/commits/commit_sha/changes -u username:password
```

**Comment by ajayakumar-jayaraj** [comment]
I am able to get response for curl http://**/rest/api/1.0/projects/m*/repos/microservices/commits -u username:Password

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj This is great that you make rest api call through curl command. Now I am sure that the encryption mechanism you are using is incorrect. Can you please use this class to generate an encryption key and use that to encrypt your secret. You will use configure this encrypted key with git.key=someLongKey.
For example when I execute Encryption.java then I get this output,
```
Your secret key is:
/oZFLKeRgxMBhrxAhm7mUjjB5T37tXNr
Sample encrypted string with the above key for 'thisIsMyPassword' is:
AdshEXW4j/AJW1Uh8fNdGKIIzn+HBcmM
```
Here key is  `/oZFLKeRgxMBhrxAhm7mUjjB5T37tXNr`
and encrypted password is `AdshEXW4j/AJW1Uh8fNdGKIIzn+HBcmM` 

With this data as an example, you can configure,
``` git.key=/oZFLKeRgxMBhrxAhm7mUjjB5T37tXNr ```

**Comment by ajayakumar-jayaraj** [comment]
Thanks @shishirchaturvedi  it is working .

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi I see a weird issue , the encrypted password setup on widget gets reset or stops working in the subsequent collector run. I updated the password again on the widget it started working again .

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj What exception do you get when collector stops working? Is it still -  ```org.springframework.web.client.HttpClientErrorException: 401 Unauthorized```.

**Comment by ajayakumar-jayaraj** [comment]
Hi @shishirchaturvedi attached the error logs

2019-06-06 11:20:00,006 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2019-06-06 11:20:00,233 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:34, serverValue:6081}] to **:27017
2019-06-06 11:20:00,291 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-06 11:20:00,291 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-06 11:20:00,291 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-06 11:20:01,297 ERROR c.c.d.c.DefaultBitbucketServerClient - Cannot decrypt this message
Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
2019-06-06 11:20:01,306 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from https://****:7999/rest/api/1.0/projects/ms/repos/microservices/commits?until=master&limit=20
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://***:7999/rest/api/1.0/projects/ms/repos/microservices/commits?until=master&limit=20": Unrecognized SSL message, plaintext connection?; nested exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj I see two issues here.
**1. Encryption Key is not used for both encryption and decryption** Please configure SCM collector to use same Encryption Key which you have used to encrypt your password.
**2. bitbucket server is sending response over HTTP** I see an exception with a message `Unrecognized SSL message, plaintext connection`. This means that Bitbucket server is sending response over HTTP. Reference: https://stackoverflow.com/questions/6532273/unrecognized-ssl-message-plaintext-connection-exception

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi 

 1)  it is getting expiring or failing to use the git.key/encrypted Password after 30 minutes, any runs within 30 mins are successful after the password update on widget.

2) our stash end point is http 

![image](https://user-images.githubusercontent.com/32649250/59052636-7c48e980-885d-11e9-99c7-cfd3bd86c9ca.png)

# Mandatory parameters
git.host=stash.***
git.api=/rest/api/1.0/
#git.userId=
#git.password=

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj It is strange that Bitbucket collector is unable to decrypt credentials after 30 mins. I don't see any reason why it is behaving that way. Encryption keys in Hygieia are loaded at startup time. There is no reason why it should reset the encryption key. 
One possibility is that somehow encrypted password, which is stored in Hygieia MongoDB, is getting changed/updated.
Can you enable DEBUG log level so that you can get a detailed log of what is going on, 
logging.level.com.capitalone.dashboard.collector=DEBUG
logging.level.org.springframework=DEBUG

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi yes I agree , encrypted password is getting changed with 30 min duration.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi pls see attached log file
[bitbucket-collector-2019-06-06.0.txt](https://github.com/Hygieia/Hygieia/files/3263305/bitbucket-collector-2019-06-06.0.txt)

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj I don't see log file link.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi Pls check now

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj I didn't find anything suspicious in the log file. Bitbucket calls are getting 200 response. 
Anyways, can you pull the latest source code of Hygieia? My PR was merged recently and it will allow you to use global Bitbucket password in the application.properties file. So after pulling latest code, you can configure Bitbucket username/password as,
```
git.username=username
git.password=encryptedPassword
git.key=encryptionKey
```

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi removed the username and passwd on widget and included delcaration on application.properties. it didnt work getting org.springframework.web.client.HttpClientErrorException: 401 Unauthorized 
# Mandatory parameters
git.host=stas***
git.api=/rest/api/1.0/
git.username=A**
git.password=B**
git.key=zbz***

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Have you pulled latest source code of Hygeia? Can you run SCM collector in debug mode and check credentials in the rest call or in the debug logs?

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi yes I took the latest code. I am using the same key and credentials which was working before . one bug i see it is pulling the old credentials which should not be used  , it is not getting the credential hardcoded in the application.properties . i believe if we update the credentials it shd overwrite the older one. Please looks into asap. it is completely broken now.

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Current implementation works like this,
1. If repo credentials are configured in repo config widget then it is given priority.
2. When repo credentials are missing in config widget then use globally configured credentials.
https://github.com/Hygieia/Hygieia/blob/master/collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/SCMHttpRestClient.java#L34-L38
3. If no credentials are configured then make Rest API call without credentials.

When you said SCM collector is picking up old credentials, I suspect that you still have userID/password in the repo config. There is no other way Hygieia will have knowledge about old credentials. 
Looking forward to more input on this.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi i verfied no credentials are hardcoded widget . I verified key and encrypted password set in appl properties. I have below error now 


2019-06-07 10:50:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2019-06-07 10:50:00,242 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:7623}] to ***:27017
2019-06-07 10:50:00,318 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-07 10:50:00,318 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-07 10:50:00,318 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-07 10:50:01,516 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Date
	at com.capitalone.dashboard.model.GitRepo.getLastUpdateTime(GitRepo.java:53) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:154) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
^C2019-06-07 10:50:49,884 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@439c8c80: startup date [Fri Jun 07 10:45:12 EDT 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@767aa305
2019-06-07 10:50:49,892 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2019-06-07 10:50:49,899 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans
2019-06-07 10:50:49,990 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj This is a valid error. The root cause for this error is the incompatible conversion of LastUpdateTime filed on GitRepo collection. This change is related to my last PR. I have issued a PR which should address this issue. 
However, I don't see any 401 unauthenticated user error in your log and seems like your collector was able to authenticate Bitbucket successfully.

**Comment by ajayakumar-jayaraj** [comment]
Thanks @shishirchaturvedi . Please let me know once the fix is ready, ..

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj It would great if you can validate this PR: #2958

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj #2958 is merged. Can you please pull latest source code?

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi i pulled the latest code. org.springframework.web.client.HttpClientErrorException: 401 Unauthorized is back again ..

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj I don't think that the latest changes(#2958) have anything to do with authentication. Can you please double check your logs for encrypted password? Additionally can you please check what credentials are being passed to Bitbucket Rest API call.
Just to confirm, now you don't see ```java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Date
at com.capitalone.dashboard.model.GitRepo.getLastUpdateTime(GitRepo.java:53) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]``` error in the logs. This is what I attempted to fixe in #2958.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi I am using same credential which was working . i validated it again . yes i dont see the "java.lang.Long cannot be cast to java.util.Date " but seeing the 401 error with the credentials encoded in application.properties file ,
git.host=s***
git.api=/rest/api/1.0/
git.username=**
git.password=***encryptedpassword
git.key=****

2019-06-07 14:00:00,003 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2019-06-07 14:00:00,267 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:7844}] to 35.227.94.60:27017
2019-06-07 14:00:00,342 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-07 14:00:00,342 INFO  c.c.d.collector.CollectorTask - Starting...
2019-06-07 14:00:00,342 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-07 14:00:01,743 ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://stash.prod.icd/rest/api/1.0/projects/msa/repos/atd-microservices/commits?until=refs%2Fheads%2Fmaster&since=2ed033472511a96749beaf39d11ce8c7e19fddcf&limit=20
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.SCMHttpRestClient.makeRestCall(SCMHttpRestClient.java:41) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultBitbucketServerClient.getCommits(DefaultBitbucketServerClient.java:87) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:156) [bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj I am glad that this error is resolved.
```java
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Date
at com.capitalone.dashboard.model.GitRepo.getLastUpdateTime(GitRepo.java:53) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
```
========
I see that authentication is failing here - SCMHttpRestClient.java:41
Can you please enable debug logs so that you can see details logs for Spring. Please enable debug properties which I shared earlier.

**Comment by ajayakumar-jayaraj** [comment]
are you in gitter ? what is your gitter id so i canPM the errors

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj yes, let's chat in giiter. I am new to Gitter, can you send me a direct message.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi i cant find you , what is ur id ??

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj I have posted `Hi` to the Hygieia channel on Gitter. Can you see my message?

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Now we are connected on Gitter.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi i rebuilt the mongodb again , i no more see the old credential however i am still getting 401 error 2019-06-09 08:35:00,612 INFO c.c.d.collector.GitCollectorTask - {password=, personalAccessToken=, branch=develop, userID=, url=http://sta*.***/projects/micros/repos/microservices/}::develop::get pulls
2019-06-09 08:35:00,640 INFO c.c.d.collector.PullRequestCollector - Executing [http://sta****/rest/api/1.0/projects/projects/repos/micros/repos/microservices//pull-requests?at=refs%2Fheads%2Fdevelop&state=all&limit=20
2019-06-09 08:35:00,678 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Can you enable debug logs? Also please step through rest call in debugging to see what credentials are being passed in the Rest call.

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi Thanks . Please find the attached debug logs
[bitbucket-collector-2019-06-10.0.txt](https://github.com/Hygieia/Hygieia/files/3272363/bitbucket-collector-2019-06-10.0.txt)

**Comment by shishirchaturvedi** [comment]
@ajayakumar-jayaraj Can we chat on Gitter?

**Comment by ajayakumar-jayaraj** [comment]
@shishirchaturvedi it works perfect now . Thanks.

**Comment by Sbrenthughes** [comment]
Thank you @shishirchaturvedi !

**Comment by njayabaFT** [comment]
Bitbucket is not collecting data and we're unable to save data from the dashboard due to the error "No matching urls". We tried adding data directly in the tables to enable collection. Can someone please help with sample data for collector_items, collector and components and other related tables for Bitbucket?
