### ISSUE TITLE
jira collector Null pointer exception

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [Hygieia/Hygieia#2943]
Getting below exception:
Exception:
2019-05-30 22:16:00,136 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-05-30 22:16:00,136 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 433130. Collector is about to refresh Team/Board information
2019-05-30 22:16:00,170 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[na:1.8.0_201]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:79) ~[json-simple-1.1.1.jar!/:na]
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getBoards(DefaultJiraClient.java:169) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.updateTeamInformation(FeatureCollectorTask.java:176) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:143) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

Jira Application.properties:

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=********

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=password

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=25

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2019-05-30T00:00:00.000000
feature.masterStartDate=2019-10-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2019-05-30T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=http://******
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=*****************

# OAuth is not fully implemented; please blank-out the OAuth values:

#feature.jiraOauthAuthtoken=
#feature.jiraOauthRefreshtoken=
#feature.jiraOauthRedirecturi=
#feature.jiraOauthExpiretime=

feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10941
feature.jiraEpicIdFieldName=customfield_11141
feature.jiraStoryPointsFieldName=customfield_10162
feature.jiraTeamFieldName=
# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=1000

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

#Defines the number of hours between each board/team and project data refresh
feature.refreshTeamAndProjectHours=3

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes  pls help on this

**Comment by Sbrenthughes** [comment]
Do you get a response when you navigate to `https://<jiralurl>/rest/agile/1.0/board`?

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes yes i get response when i navigate with https://<jiralurl>/rest/agile/1.0/board

{"maxResults":50,"startAt":0,"isLast":false,"values":[{"id":1,"self" ....}

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes Any update on this ??

**Comment by rvema** [comment]
@ajayakumar-jayaraj looking at the stack trace there seems to be an issue making the rest call and getting the response. Most likely the response is null. Do you see any error related to the network call from the logs?

**Comment by ajayakumar-jayaraj** [comment]
@rvema i can see application is not coming up with null pointer exception with below log in jira.log, I can see api response with below endpoint http://***/rest/agile/1.0/board with no issues but noticed to null response to http://**/rest/agile/1.0/board/rest/agile/1.0/board?startat=0

2019-06-04 08:43:39,500 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'featureCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

**Comment by ajayakumar-jayaraj** [comment]
Attached complete logs
[jiracollector-2019-06-04.0.log](https://github.com/Hygieia/Hygieia/files/3253681/jiracollector-2019-06-04.0.log)

**Comment by rvema** [comment]
@ajayakumar-jayaraj Can you check the feature.cron property? The null pointer seems to be happening due to bad cron setting

**Comment by rvema** [comment]
seems that you are using `feature.cron=0 * * * * *` can you change it to `feature.cron=0 * * * * `

**Comment by ajayakumar-jayaraj** [comment]
[jiracollector-2019-06-04.0.log](https://github.com/Hygieia/Hygieia/files/3254098/jiracollector-2019-06-04.0.log)
Failed again with same error . Attached log file. @rvema

**Comment by rvema** [comment]
The cron schedule is an issue per the below error
`Caused by: java.lang.NullPointerException: null
	at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-3.1.0.jar!/:3.0.2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	... 23 common frames omitted
`

**Comment by ajayakumar-jayaraj** [comment]
@rvema . I built and applied the properties from beginning. Still we have null pointer exception. 

2019-06-05 10:29:00,001 INFO c.c.d.collector.CollectorTask - Running Collector: Jira
2019-06-05 10:29:00,133 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-06-05 10:29:00,133 INFO c.c.d.collector.CollectorTask - http://***/
2019-06-05 10:29:00,133 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-06-05 10:29:00,134 INFO c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-06-05 10:29:00,134 INFO c.c.d.collector.FeatureCollectorTask - Hours since last run = 433262. Collector is about to refresh Team/Board information
2019-06-05 10:29:00,171 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
at java.io.StringReader.<init>(StringReader.java:50) ~[na:1.8.0_201]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:79) ~[json-simple-1.1.1.jar!/:na]
at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar!/:na]
at com.capitalone.dashboard.collector.DefaultJiraClient.getTeams(DefaultJiraClient.java:222) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
at

**Comment by rvema** [comment]
@ajayakumar-jayaraj can you re attach the entire log file?

**Comment by ajayakumar-jayaraj** [comment]
attached the log file
[jiracollectorupdated.txt](https://github.com/Hygieia/Hygieia/files/3258444/jiracollectorupdated.txt)

**Comment by rvema** [comment]
@ajayakumar-jayaraj Logs have error connecting to the database. please fix the appropriate information in the properties file.

**Comment by ajayakumar-jayaraj** [comment]
@rvema I fixed the password . Please review the bottom of file for the latest logs.

**Comment by ajayakumar-jayaraj** [comment]
@rvema Any update on this ?

**Comment by rvema** [comment]
@ajayakumar-jayaraj Per the latest log there seems to be an connectivity error while connecting to jira server. 
`019-06-05 12:58:00,067 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://jira/rest/api/2/issuetype": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:826) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getJiraIssueTypeIds(DefaultJiraClient.java:302) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.getCollector(FeatureCollectorTask.java:95) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.getCollector(FeatureCollectorTask.java:48) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-3.1.0.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)`

**Comment by rvema** [comment]
@ajayakumar-jayaraj do verify the value of `feature.jiraBaseUrl`

**Comment by ajayakumar-jayaraj** [comment]
@rvema you are seeing old logs which i tried out for https endpoint. we are using http and feature.jiraBaseUrl looks fine.

**Comment by ajayakumar-jayaraj** [comment]
[jiracollector-2019-06-06.0.txt](https://github.com/Hygieia/Hygieia/files/3262134/jiracollector-2019-06-06.0.txt)
@rvema please see the latest failiure logs . Hopefully this help.

**Comment by ajayakumar-jayaraj** [comment]
@rvema did you got a chance to look at the logs

**Comment by Sbrenthughes** [comment]
> Do you get a response when you navigate to `https://<jiralurl>/rest/agile/1.0/board`?

Can you use http here and see if you get a response?

**Comment by Sbrenthughes** [comment]
I get the exact same error when I do not use https.. I would suggest switching your jira to use it.

**Comment by ajayakumar-jayaraj** [comment]
> > Do you get a response when you navigate to `https://<jiralurl>/rest/agile/1.0/board`?
> 
> Can you use http here and see if you get a response?

I can get response for it ...

**Comment by ajayakumar-jayaraj** [comment]
@Sbrenthughes @rvema 

I am able to connect to https jira instance . However I don’t see data collected in the dashboard also I see below error in the logs but it is accessible.
 
Error in calling JIRA API: https://jira***.**.com/rest/agile/1.0/board?startAt=0
 
2019-06-10 08:21:04,757 INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=439c8c80,type=ConfigurationPropertiesRebinder]
2019-06-10 08:21:04,809 INFO  com.capitalone.dashboard.Application - Started Application in 8.753 seconds (JVM running for 9.602)
2019-06-10 08:22:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-06-10 08:22:00,447 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 08:22:00,447 INFO  c.c.d.collector.CollectorTask - https://jir**.a**.com/
2019-06-10 08:22:00,448 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 08:22:00,448 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-06-10 08:22:00,448 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 162. Collector is about to refresh Team/Board information
2019-06-10 08:22:00,472 ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: https://jira2test.atd-us.com/rest/agile/1.0/board?startAt=0
2019-06-10 08:22:00,474 INFO  c.c.d.collector.CollectorTask - Board Data Collected. Added  0        0s
2019-06-10 08:22:00,559 INFO  c.c.d.collector.CollectorTask - Project Data Collected  0        0s
2019-06-10 08:22:00,757 INFO  c.c.d.collector.CollectorTask - Board Issues Refreshed           0s
2019-06-10 08:22:00,794 INFO  c.c.d.collector.FeatureCollectorTask - Collected 0 teams and 0 projects
2019-06-10 08:22:00,871 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2019-06-10 08:23:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-06-10 08:23:00,133 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 08:23:00,133 INFO  c.c.d.collector.CollectorTask - https://jir**.***.com/
2019-06-10 08:23:00,133 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-10 08:23:00,133 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-06-10 08:23:00,133 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 0. Collector is only collecting updated/new issues.
2019-06-10 08:23:00,204 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by rvema** [comment]
@ajayakumar-jayaraj The error you are seeing do you have additional information on it? Also do you have the certs for https jira url imported under your jdk?
