### ISSUE TITLE
Bug with Bitbucket collector after initial commit/pr pull

### ISSUE THREAD

**Issue by OneMoreByte** [Hygieia/Hygieia#2956]
With one of the recent PRs related to the Bitbucket collector (PR #2678) I've encountered an issue after the collector writes it's first time to the database. It thereafter can't read the time back from the collector_item, and would crash with the exception...
```
 java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Date
 	at com.capitalone.dashboard.model.GitRepo.getLastUpdateTime(GitRepo.java:53) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.4]
 	at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:154) ~[bitbucket-scm-collector-3.0.2-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
 	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.0.2-SNAPSHOT]
 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
 	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_212]
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_212]
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212
```

Did I misconfigure something or is did `getLastUpdateTime()` miss the refactor of how the collector handles it's time?

**Comment by OneMoreByte** [comment]
@shishirchaturvedi  @rvema @Sbrenthughes

**Comment by shishirchaturvedi** [comment]
@OneMoreByte I am looking at this.

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes In my last PR for Bitbucket enhancement, I changed `LastUpdateTime` field on GitRepo collection from java.util.Date to Long(milliSeconds). It is Hygeia standard to use Time Stamps in long millis. Based on the review comments I've changed 'LastUpdateTime' to long but it is breaking existing users of SCM bitbucket collectors. I can submit a PR to change this field back to java.util.Date. What do you think? 
https://github.com/Hygieia/Hygieia/pull/2678/files/c80ecf29b462e618ad01fc81aa5fa1eced5d98cd..ac22374626fc5cc70a72b2eade3773ece2d10397#r252381324

**Comment by shishirchaturvedi** [comment]
@OneMoreByte You are right. I missed the conversion of LastUpdateTime field (Date->Long). My intention was to use Long for LastDateTime field but somehow missed to update it uniformly.
I have submitted this [PR](https://github.com/Hygieia/Hygieia/pull/2958) and it would be great if you can validate it.

**Comment by shishirchaturvedi** [comment]
@OneMoreByte Please let me know if you still encounter any issue. I feel that this change of LastUpdateTime from Date to Long might break existing users fo Bitbucket scm collector. I could be wrong. 
cc @Sbrenthughes

**Comment by rvema** [comment]
@OneMoreByte The PR is in, please validate

**Comment by OneMoreByte** [comment]
@shishirchaturvedi @rvema Sorry to get to this so late on Friday. The PR seemed to do the trick. Thanks so much for your promptness!
