### ISSUE TITLE
Jira Collector NPE, different from 2943

### ISSUE THREAD

**Issue by jarbil** [Hygieia/Hygieia#2979]
I updated the Jira source last week, so I should have the latest changes. It looks like the docs haven't updated in the past month though. The removed settings just ignored, correct?

Here are the settings I have:
```
#DB
dbname=hdb04
dbusername=huser
dbpassword=****
dbhost=localhost
dbport=27017

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2017-03-01T00:00:00.000000
feature.masterStartDate=2017-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2017-03-01T00:00:00.000000
# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 2/3 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
feature.jiraBaseUrl=https://jira:8443/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
#feature.jiraCredentials=****
feature.jiraCredentials=****

# OAuth is not fully implemented; please blank-out the OAuth values:
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10005

#############################################################################
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_21737

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_10509

#############################################################################
# In Jira, your instance will have its own Id for the issueTypes. 
# You can retrieve the issueType IDs from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
feature.jiraStoryIds[0]=Onboarding
feature.jiraStoryIds[1]=Issue
feature.jiraStoryIds[2]=Enhancement
feature.jiraStoryIds[3]=Incident
feature.jiraStoryIds[4]=Service Request
feature.jiraStoryIds[5]=Change
feature.jiraStoryIds[6]=Problem
feature.jiraStoryIds[7]=Sub-task
feature.jiraStoryIds[8]=Portfolio Epic
feature.jiraStoryIds[9]=Strategic Initiative
feature.jiraStoryIds[10]=Story
feature.jiraStoryIds[11]=Defect
feature.jiraStoryIds[12]=Test
feature.jiraStoryIds[13]=Task
feature.jiraStoryIds[14]=Spike
feature.jiraStoryIds[15]=Debt
feature.jiraStoryIds[16]=Test Set
feature.jiraStoryIds[17]=Test Execution
feature.jiraStoryIds[18]=Test Plan
feature.jiraStoryIds[19]=Risk/Impediment/Dependency
feature.jiraStoryIds[20]=Pre-Condition
feature.jiraStoryIds[21]=Capability
feature.jiraStoryIds[22]=IT Help
feature.jiraStoryIds[23]=Purchase
feature.jiraStoryIds[24]=Fault
feature.jiraStoryIds[25]=Access
feature.jiraStoryIds[26]=Virtualized Base Path Review
feature.jiraStoryIds[27]=Dataset Definition Review
feature.jiraStoryIds[28]=Technical Debt
feature.jiraStoryIds[29]=Swagger Review
feature.jiraStoryIds[30]=Feature
feature.jiraStoryIds[31]=Enabler
feature.jiraStoryIds[32]=Program Epic
feature.jiraStoryIds[33]=Adhoc
feature.jiraStoryIds[34]=Architecture
feature.jiraStoryIds[35]=Analyst Issue
feature.jiraStoryIds[36]=Service Desk Agent License
feature.jiraStoryIds[37]=JE-Report
feature.jiraStoryIds[38]=Activity
feature.jiraStoryIds[39]=Customer
feature.jiraStoryIds[40]=Dependency

#############################################################################
# In Jira, your instance will have its own Id for the Epic
# You can find the value from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
#feature.jiraEpicId=

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=false

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=1000

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

#############################################################################
# Internal Status Mappings - THESE SHOULD BE FILLED OUT FOR EVERY CUSTOM STATUS VALUE
# IN YOUR JIRA INSTANCE
#
# Use the following API call to get all of your status mappings:  http://jira.your.instance.com/rest/api/2/status/
#############################################################################
feature.todoStatuses[0]=Open
feature.todoStatuses[1]=Reopened
feature.todoStatuses[2]=New
feature.todoStatuses[3]=Analysis
feature.todoStatuses[4]=Portfolio Backlog
feature.todoStatuses[5]=Value Stream Backlog
feature.todoStatuses[6]=Review
feature.todoStatuses[7]=Funnel
feature.todoStatuses[8]=Program Backlog
feature.todoStatuses[9]=Team Backlog
feature.todoStatuses[10]=Analyze - In Progress
feature.todoStatuses[11]=Analyze - Ready
feature.todoStatuses[12]=Iteration Backlog
feature.todoStatuses[13]=Submit
feature.todoStatuses[14]=Assign
feature.todoStatuses[15]=Backlog
feature.todoStatuses[16]=Reopen
feature.todoStatuses[17]=Awaiting approval
feature.todoStatuses[18]=Submitted for review
feature.todoStatuses[19]=Assigned - Evaluating
feature.todoStatuses[20]=Investigating
feature.todoStatuses[21]=Awaiting Production Release
feature.todoStatuses[22]=Upcoming

feature.doingStatuses[0]=In Progress
feature.doingStatuses[1]=Blocked
feature.doingStatuses[2]=On Hold
feature.doingStatuses[3]=Waiting for customer
feature.doingStatuses[4]=Implementation
feature.doingStatuses[5]=Construction In Progress
feature.doingStatuses[6]=PI Objectives Agreed
feature.doingStatuses[7]=Build - Ready
feature.doingStatuses[8]=Resolve
feature.doingStatuses[9]=Fail
feature.doingStatuses[10]=Customer Review
feature.doingStatuses[11]=WIP - Dev
feature.doingStatuses[12]=WIP - ReadyForTest
feature.doingStatuses[13]=WIP - Test
feature.doingStatuses[14]=Cycle Time Start
feature.doingStatuses[15]=WIP 1
feature.doingStatuses[16]=WIP 2
feature.doingStatuses[17]=WIP 3
feature.doingStatuses[18]=Update
feature.doingStatuses[19]=Data Team Review
feature.doingStatuses[20]=Accept
feature.doingStatuses[21]=Scheduled
feature.doingStatuses[22]=Assigned - Evaluation Complete
feature.doingStatuses[23]=Awaiting Prioritization
feature.doingStatuses[24]=WIP - Analyze
feature.doingStatuses[25]=In Development
feature.doingStatuses[26]=Implementing
feature.doingStatuses[27]=Work in progress
feature.doingStatuses[28]=Active

feature.doneStatuses[0]=Done
feature.doneStatuses[1]=Defer
feature.doneStatuses[2]=Resolved
feature.doneStatuses[3]=Closed
feature.doneStatuses[4]=Cancelled
feature.doneStatuses[5]=Rejected
feature.doneStatuses[6]=Withdrawn
feature.doneStatuses[7]=Declined
feature.doneStatuses[8]=Completed
feature.doneStatuses[9]=Deployed
feature.doneStatuses[10]=Accepted
feature.doneStatuses[11]=Close
feature.doneStatuses[12]=Cancel
feature.doneStatuses[13]=Archive
feature.doneStatuses[14]=Cycle Time End
feature.doneStatuses[15]=In Use
feature.doneStatuses[16]=Obsolete
feature.doneStatuses[17]=Released
feature.doneStatuses[18]=Enhancement
feature.doneStatuses[19]=Pending with External Team
feature.doneStatuses[20]=Deleted

#No Category=Waiting for support
#No Category=Awaiting implementation
```

And here is the end of my log:
```
2019-06-18 11:20:00,296 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-18 11:20:00,296 INFO  c.c.d.collector.CollectorTask - https://jira:8443/
2019-06-18 11:20:00,296 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-18 11:20:00,296 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-06-18 11:20:00,297 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 21. Collector is only collecting updated/new issues.
2019-06-18 11:20:00,578 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 484 boards.
2019-06-18 11:20:00,705 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-06-18T11:17:00.517 0        0s
2019-06-18 11:20:00,767 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 2 of 484 boards.
2019-06-18 11:20:01,881 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$21(DefaultJiraClient.java:396) ~[jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient$$Lambda$25/220844810.accept(Unknown Source) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1234) ~[na:1.8.0]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:387) ~[jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:268) ~[jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$7(FeatureCollectorTask.java:277) [jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask$$Lambda$13/1409408445.accept(Unknown Source) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1234) ~[na:1.8.0]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:274) [jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:159) [jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.1-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
```

**Comment by Sbrenthughes** [comment]
Can you check the updated documentation at https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/jira.md. `jiraStoryIds` and `jiraEpicId` are no longer needed. 

You need to add them in a comma seperated string to `jiraIssueTypeNames`. Ex `feature.jiraIssueTypeNames=Stroy,Epic,Defect, etc`

`Epic` is required in the list.

**Comment by Sbrenthughes** [comment]
@jarbil

**Comment by jarbil** [comment]
Thanks! I'll try that as soon as work allows and report back.

**Comment by jarbil** [comment]
I added all the IssueTypes to `jiraIssueTypeNames` (Including Epic) and removed the `jiraStoryIds` and `jiraEpicId` sections. I then got the following in the log:
```
2019-07-01 11:41:40,815 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 502 of 503 boards.
2019-07-01 11:41:40,982 ERROR c.c.d.collector.DefaultJiraClient - ERROR collecting issues. {"errorMessages":["The value 'Change' does not exist for the field 'issueType'."],"errors":{}}. Url = https://jira:8443/rest/agile/1.0/board/37125/issue?jql=issueType in ('Story','Epic','Onboarding','Issue','Enhancement','Incident','Service Request','Change','Problem','Sub-task','Portfolio Epic','Strategic Initiative','Defect','Test','Task','Spike','Debt','Test Set','Test Execution','Test Plan','Risk/Impediment/Dependency','Pre-Condition','Capability','IT Help','Purchase','Fault','Access','Virtualized Base Path Review','Dataset Definition Review','Technical Debt','Swagger Review','Feature','Enabler','Program Epic','Adhoc','Architecture','Analyst Issue','Service Desk Agent License','JE-Report','Activity','Customer','Dependency') and updatedDate>='2019/06/01 11:41'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_10509,customfield_10005,customfield_10006,customfield_10002&startAt=0
2019-07-01 11:41:40,982 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 1969-12-31T19:00 0      114s
2019-07-01 11:41:41,014 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 503 of 503 boards.
2019-07-01 11:41:41,189 ERROR c.c.d.collector.DefaultJiraClient - ERROR collecting issues. {"errorMessages":["The value 'Change' does not exist for the field 'issueType'."],"errors":{}}. Url = https://jira:8443/rest/agile/1.0/board/36881/issue?jql=issueType in ('Story','Epic','Onboarding','Issue','Enhancement','Incident','Service Request','Change','Problem','Sub-task','Portfolio Epic','Strategic Initiative','Defect','Test','Task','Spike','Debt','Test Set','Test Execution','Test Plan','Risk/Impediment/Dependency','Pre-Condition','Capability','IT Help','Purchase','Fault','Access','Virtualized Base Path Review','Dataset Definition Review','Technical Debt','Swagger Review','Feature','Enabler','Program Epic','Adhoc','Architecture','Analyst Issue','Service Desk Agent License','JE-Report','Activity','Customer','Dependency') and updatedDate>='2019/06/01 11:41'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_10509,customfield_10005,customfield_10006,customfield_10002&startAt=0
2019-07-01 11:41:41,189 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 1969-12-31T19:00 0      114s
2019-07-01 11:41:41,243 INFO  c.c.d.collector.CollectorTask - Finished                       219s
```
I checked the issueTypes api call and Change indeed is no longer listed, so I removed it from the list. For reference the field value is now
```
feature.jiraIssueTypeNames=Story,Epic,Onboarding,Issue,Enhancement,Incident,Service Request,Problem,Sub-task,Portfolio Epic,Strategic Initiative,Defect,Test,Task,Spike,Debt,Test Set,Test Execution,Test Plan,Risk/Impediment/Dependency,Pre-Condition,Capability,IT Help,Purchase,Fault,Access,Virtualized Base Path Review,Dataset Definition Review,Technical Debt,Swagger Review,Feature,Enabler,Program Epic,Adhoc,Architecture,Analyst Issue,Service Desk Agent License,JE-Report,Activity,Customer,Dependency
```
However, upon restarting I came across a familiar sight, now failing on 10 instead of 2 at least...
```
2019-07-01 12:56:00,270 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-07-01 12:56:00,270 INFO  c.c.d.collector.CollectorTask - https://jira:8443/
2019-07-01 12:56:00,270 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-07-01 12:56:00,270 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-07-01 12:56:00,270 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 1. Collector is only collecting updated/new issues.
2019-07-01 12:56:00,416 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 503 boards.
2019-07-01 12:56:00,568 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:00.356 0        0s
2019-07-01 12:56:00,638 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 2 of 503 boards.
2019-07-01 12:56:00,771 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:00.645 0        0s
2019-07-01 12:56:00,833 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 3 of 503 boards.
2019-07-01 12:56:00,975 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:00.838 0        0s
2019-07-01 12:56:01,032 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 4 of 503 boards.
2019-07-01 12:56:01,182 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:01.044 0        0s
2019-07-01 12:56:01,214 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 5 of 503 boards.
2019-07-01 12:56:01,342 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:01.208 0        1s
2019-07-01 12:56:01,377 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 6 of 503 boards.
2019-07-01 12:56:01,506 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:01.392 0        1s
2019-07-01 12:56:01,539 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 7 of 503 boards.
2019-07-01 12:56:01,662 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:01.547 0        1s
2019-07-01 12:56:01,698 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 8 of 503 boards.
2019-07-01 12:56:01,830 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:01.714 0        1s
2019-07-01 12:56:01,869 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 9 of 503 boards.
2019-07-01 12:56:01,992 INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2019-07-01T12:53:01.906 0        1s
2019-07-01 12:56:02,084 INFO  c.c.d.collector.FeatureCollectorTask - Collecting 10 of 503 boards.
2019-07-01 12:56:02,682 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$21(DefaultJiraClient.java:396) ~[jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient$$Lambda$25/1692778713.accept(Unknown Source) ~[na:na]
        at java.util.ArrayList.forEach(ArrayList.java:1234) ~[na:1.8.0]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:387) ~[jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:268) ~[jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$7(FeatureCollectorTask.java:277) [jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask$$Lambda$13/1252005601.accept(Unknown Source) ~[na:na]
        at java.util.ArrayList.forEach(ArrayList.java:1234) ~[na:1.8.0]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:274) [jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:159) [jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira.jar!/:3.0.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.1-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0]
        at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
```

**Comment by jarbil** [comment]
@Sbrenthughes where do the auto-complete suggestions for the widget get stored? Because those work, but the "feature" collection in the database appears empty.

**Comment by Sbrenthughes** [comment]
They are stored in `team` and `scope` collections. The Null Pointer is interesting.

**Comment by jarbil** [comment]
I've followed the process in #2807 for the older (~April) instance but the team and scope collections repopulate normally while the feature collection remains empty. For the heck of it I tried clearing the collections in the newer (June) instance and still encounter the NPE.

FWIW, we do not have a type named "Epic" in https://jira:8443/rest/api/2/issuetype but we do have "Program Epic" and "Portfolio Epic".

**Comment by Sbrenthughes** [comment]
Okay the collector depends on the `Epic` issue type being used. If it isn't being used then the collector will not work in the current version.

**Comment by continuum-vikrant-tyagi** [comment]
Hi @Sbrenthughes  I do have all these below details but still data is not storing in feature collections.

```
feature.jiraIssueTypeNames=Story,Epic,Bug,Task,Sub-task
feature.todoStatuses[0]=Open
feature.doingStatuses[0]=WIP
feature.doneStatuses[0]=Done


feature.jiraSprintDataFieldName=customfield_13101
feature.jiraEpicIdFieldName=customfield_11300
feature.jiraStoryPointsFieldName=customfield_10105
feature.jiraTeamFieldName=
feature.collectorItemOnlyUpdate=false
feature.maxNumberOfFeaturesPerBoard=1000
feature.jiraBoardAsTeam=true
feature.refreshTeamAndProjectHours=1
logging.level.com.capitalone.dashboard.collector=INFO
logging.level.com.capitalone.dashboard=INFO
lastRefreshTime=0
lastExecuted=0
```

I am able to filter Project And Dashboard... but rest of the part not visible on widget screen.
please have a look at the image

![image](https://user-images.githubusercontent.com/33453392/62754898-60e1a100-ba8f-11e9-9f5b-58955057f04f.png)

**Comment by continuum-vikrant-tyagi** [comment]
> Hi @Sbrenthughes I do have all these below details but still data is not storing in feature collections.
> 
> ```
> feature.jiraIssueTypeNames=Story,Epic,Bug,Task,Sub-task
> feature.todoStatuses[0]=Open
> feature.doingStatuses[0]=WIP
> feature.doneStatuses[0]=Done
> 
> 
> feature.jiraSprintDataFieldName=customfield_13101
> feature.jiraEpicIdFieldName=customfield_11300
> feature.jiraStoryPointsFieldName=customfield_10105
> feature.jiraTeamFieldName=
> feature.collectorItemOnlyUpdate=false
> feature.maxNumberOfFeaturesPerBoard=1000
> feature.jiraBoardAsTeam=true
> feature.refreshTeamAndProjectHours=1
> logging.level.com.capitalone.dashboard.collector=INFO
> logging.level.com.capitalone.dashboard=INFO
> lastRefreshTime=0
> lastExecuted=0
> ```
> 
> I am able to filter Project And Dashboard... but rest of the part not visible on widget screen.
> please have a look at the image
> 
> also the way document(https://hygieia.github.io/Hygieia/jira.html) mentioned to find customfield is not pretty precise... and it landed to confuse that how we can validate is customfield correct or not.
> 
> so i have followed this API of Jira "https://continuum.atlassian.net/rest/api/2/field/"
> 
> Please help into getting Jira up on Hygieia. We are looking forward to get this tool up and running ASAP.
> 
> ![image](https://user-images.githubusercontent.com/33453392/62754898-60e1a100-ba8f-11e9-9f5b-58955057f04f.png)

any update
