### ISSUE TITLE
Jenkins code quality colelctor

### ISSUE THREAD

**Issue by adhish70** [Hygieia/Hygieia#2999]
Hello, I am getting this error when I try running the jenkins-codequaliy collector.

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jenkinsCodeQualityCollectorTask' defined in URL [jar:file:/hygieia/jenkins-codequality-3.0.2-SNAPSHOT.jar!/com/capitalone/dashboard/collector/JenkinsCodeQualityCollectorTask.class]: Unsatisfied dependency expressed through constructor argument with index 3 of type [com.capitalone.dashboard.jenkins.JenkinsSettings]: Error creating bean with name 'jenkinsSettings': Could not bind properties to JenkinsSettings (prefix=jenkins-codequality, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type [java.lang.String] to required type [com.capitalone.dashboard.model.quality.ArtifactType] for property 'null'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [com.capitalone.dashboard.model.quality.ArtifactType] for value '0'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.quality.ArtifactType.0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jenkinsSettings': Could not bind properties to JenkinsSettings (prefix=jenkins-codequality, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type [java.lang.String] to required type [com.capitalone.dashboard.model.quality.ArtifactType] for property 'null'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [com.capitalone.dashboard.model.quality.ArtifactType] for value '0'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.quality.ArtifactType.0
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
        at com.capitalone.dashboard.Application.main(Application.java:16)
        ... 6 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jenkinsSettings': Could not bind properties to JenkinsSettings (prefix=jenkins-codequality, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type [java.lang.String] to required type [com.capitalone.dashboard.model.quality.ArtifactType] for property 'null'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [com.capitalone.dashboard.model.quality.ArtifactType] for value '0'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.quality.ArtifactType.0
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:323)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:273)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 24 more
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type [java.lang.String] to required type [com.capitalone.dashboard.model.quality.ArtifactType] for property 'null'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [com.capitalone.dashboard.model.quality.ArtifactType] for value '0'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.quality.ArtifactType.0
        at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:586)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:394)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:260)
        at org.springframework.boot.bind.RelaxedDataBinder.extendMapIfNecessary(RelaxedDataBinder.java:381)
        at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:288)
        at org.springframework.boot.bind.RelaxedDataBinder.normalizePath(RelaxedDataBinder.java:259)
        at org.springframework.boot.bind.RelaxedDataBinder.modifyProperty(RelaxedDataBinder.java:240)
        at org.springframework.boot.bind.RelaxedDataBinder.modifyProperties(RelaxedDataBinder.java:155)
        at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:128)
        at org.springframework.validation.DataBinder.bind(DataBinder.java:715)
        at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:267)
        at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:240)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:318)
        ... 38 more
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [com.capitalone.dashboard.model.quality.ArtifactType] for value '0'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.quality.ArtifactType.0
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
        at org.springframework.boot.bind.RelaxedConversionService.convert(RelaxedConversionService.java:91)
        at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:173)
        at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:576)
        ... 50 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.quality.ArtifactType.0
        at org.springframework.boot.bind.RelaxedConversionService$StringToEnumIgnoringCaseConverterFactory$StringToEnum.convert(RelaxedConversionService.java:141)
        at org.springframework.boot.bind.RelaxedConversionService$StringToEnumIgnoringCaseConverterFactory$StringToEnum.convert(RelaxedConversionService.java:113)
        at org.springframework.core.convert.support.GenericConversionService$ConverterFactoryAdapter.convert(GenericConversionService.java:425)
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:35)
        ... 54 more
2019-06-25 15:40:46,643 ERROR o.s.boot.SpringApplication - Application startup failed`

Can someone help me with the same.

**Comment by OneMoreByte** [comment]
Would it be possible that you're using docker-compose?

**Comment by adhish70** [comment]
No, I am not using docker compose. I am basically trying to make a container.

**Comment by OneMoreByte** [comment]
Alright, but you are using the container. At quick glance it looks like the `properties-builder.sh` for that collector is out of date and I think that's breaking your setup. To get it running you'll need to modify `collectors/build/jenkins-codequality/docker/properties-builder.sh` so it spits out settings that match [what the documentation says the config should be.](https://hygieia.github.io/Hygieia/jira.html#sample-application-properties-file)

As an aside I believe they recommend using the Jenkins plugin if possible. I believe it collects everything that the three Jenkins collectors do and a bit more.

**Comment by adhish70** [comment]
So i went to the properties-builder.sh file and it looks up to date. 

You mentioned that having Jenkins plugin would be enough to have the data for three collector. Is that correct? I have already setup the jenkins collector and it is working good.

**Comment by OneMoreByte** [comment]
Do you mean up to date with the repo or against the current properties files? I think [this line](https://github.com/Hygieia/Hygieia/blob/67c78d92fe22b3a82af5f2d6ce32d78accf5d813/collectors/build/jenkins-codequality/docker/properties-builder.sh#L68) in particular is what's giving you issues in your error, and the properties file seems to use as follows...

```
# Collector types (not required, but regex should match only the type specified)
jenkins-codequality.artifactRegex.junit=TEST-.*\\.xml
jenkins-codequality.artifactRegex.findbugs=findbugsXml.xml
jenkins-codequality.artifactRegex.pmd=pmd.xml
jenkins-codequality.artifactRegex.checkstyle=checkstyle-result.xml
jenkins-codequality.artifactRegex.jacoco=jacoco.xml
```

The jenkins collector work really well (I'm using it), but yes the plugin collects test data and build data. The test data needs to be pushed with a `hygieiaCodeQualityPublishStep` step in your jenkinsfile. The build data you can configure it to send for every job or with a `hygieiaBuildPublishStep`.

**Comment by adhish70** [comment]
It was up to date with the repo. But on checking the repo I saw the lines that you mentioned are missing in the repo itself. Thank for pointing this out. Let me try to add them and see what the changes effect will be.

**Comment by stevegal** [comment]
Did you get the result you needed?
