### ISSUE TITLE
Hygieia publisher groovy script issue

### ISSUE THREAD

**Issue by SrinivReddy** [Hygieia/Hygieia#3060]
Hi Team,

I am trying to post metrics from jenkins server to hygieia api using groovy script (
https://github.com/Hygieia/Hygieia/blob/master/hygieia-jenkins-plugin-alt/src/main/hygieia/HygieiaJenkinsPluginAlt.groovy).

I am getting below error in hygieia api:

2019-07-18 16:38:00,982 ERROR c.c.d.rest.RestApiExceptionHandler - invalid hexadecimal representation of an ObjectId: [32]
java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [32]
at org.bson.types.ObjectId.parseHexString(ObjectId.java:519) ~[mongo-java-driver-3.0.2.jar:na]
at org.bson.types.ObjectId.<init>(ObjectId.java:233) ~[mongo-java-driver-3.0.2.jar:na]
at com.capitalone.dashboard.service.BinaryArtifactServiceImpl.create(BinaryArtifactServiceImpl.java:102) ~[classes/:na]
at com.capitalone.dashboard.rest.BinaryArtifactController.create(BinaryArtifactController.java:41) ~[classes/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]

can you please look into this issue.

**Comment by rvema** [comment]
@premyadav1 Any thoughts on this error?
