### ISSUE TITLE
JIRA collector config 404 error

### ISSUE THREAD

**Issue by mykiya** [Hygieia/Hygieia#3112]
# log
2019-08-19 12:01:20,003 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-08-19 12:01:20,118 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-08-19 12:01:20,118 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://127.0.0.1:8888
2019-08-19 12:01:20,119 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-08-19 12:01:20,119 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-08-19 12:01:20,119 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 435052. Collector is about to refresh Team/Board information
2019-08-19 12:01:20,214 [taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
org.springframework.web.client.HttpClientErrorException: 404 null
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:826) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getTeams(DefaultJiraClient.java:220) ~[jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.updateTeamInformation(FeatureCollectorTask.java:176) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:143) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira-feature-collector.jar!/:3.0.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.3-SNAPSHOT.jar!/:3.0.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

# jira-feature-collector.properties:
dbname=db
dbhost=127.0.0.1
dbport=27017
dbusername=zml
dbpassword=lo122333

logging.file=./logs/jira.log

feature.pageSize=100

feature.jiraDataFlushCron=0/10 * * * * *
feature.pageSize=50
feature.cron=0/10 * * * * *

feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

feature.jiraBaseUrl=http://127.0.0.1:8888
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=cm9vdDoxMjM0NTY=

feature.jiraIssueTypeNames=Task,Sub-task,Story,Bug,Epic

feature.jiraEpicIdFieldName=
feature.jiraStoryPointsFieldName=10002
feature.jiraSprintDataFieldName=
feature.jiraStoryPointsFieldName=
feature.jiraTeamFieldName=

feature.collectorItemOnlyUpdate=true
feature.maxNumberOfFeaturesPerBoard=1000
feature.jiraBoardAsTeam=false
feature.refreshTeamAndProjectHours=3

**Comment by mykiya** [comment]
# jira issuetype
[
    {
        "self": "http://127.0.0.1:8888/rest/api/2/issuetype/10003",
        "id": "10003",
        "description": "A task that needs to be done.",
        "iconUrl": "http://127.0.0.1:8888/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype",
        "name": "Task",
        "subtask": false,
        "avatarId": 10318
    },
    {
        "self": "http://127.0.0.1:8888/rest/api/2/issuetype/10000",
        "id": "10000",
        "description": "The sub-task of the issue",
        "iconUrl": "http://127.0.0.1:8888/images/icons/issuetypes/subtask_alternate.png",
        "name": "Sub-task",
        "subtask": true
    },
    {
        "self": "http://127.0.0.1:8888/rest/api/2/issuetype/10002",
        "id": "10002",
        "description": "Created by Jira Software - do not edit or delete. Issue type for a user story.",
        "iconUrl": "http://127.0.0.1:8888/images/icons/issuetypes/story.svg",
        "name": "Story",
        "subtask": false
    },
    {
        "self": "http://127.0.0.1:8888/rest/api/2/issuetype/10004",
        "id": "10004",
        "description": "A problem which impairs or prevents the functions of the product.",
        "iconUrl": "http://127.0.0.1:8888/secure/viewavatar?size=xsmall&avatarId=10303&avatarType=issuetype",
        "name": "Bug",
        "subtask": false,
        "avatarId": 10303
    },
    {
        "self": "http://127.0.0.1:8888/rest/api/2/issuetype/10001",
        "id": "10001",
        "description": "Created by Jira Software - do not edit or delete. Issue type for a big user story that needs to be broken down.",
        "iconUrl": "http://127.0.0.1:8888/images/icons/issuetypes/epic.svg",
        "name": "Epic",
        "subtask": false
    }
]
# jira project
[
    {
        "expand":"description,lead,url,projectKeys",
        "self":"http://127.0.0.1:8888/rest/api/2/project/10005",
        "id":"10005",
        "key":"KAN",
        "name":"KANBAN",
        "avatarUrls":{
            "48x48":"http://127.0.0.1:8888/secure/projectavatar?avatarId=10324",
            "24x24":"http://127.0.0.1:8888/secure/projectavatar?size=small&avatarId=10324",
            "16x16":"http://127.0.0.1:8888/secure/projectavatar?size=xsmall&avatarId=10324",
            "32x32":"http://127.0.0.1:8888/secure/projectavatar?size=medium&avatarId=10324"
        },
        "projectTypeKey":"software"
    },
    {
        "expand":"description,lead,url,projectKeys",
        "self":"http://127.0.0.1:8888/rest/api/2/project/10003",
        "id":"10003",
        "key":"NAME",
        "name":"NAME",
        "avatarUrls":{
            "48x48":"http://127.0.0.1:8888/secure/projectavatar?avatarId=10324",
            "24x24":"http://127.0.0.1:8888/secure/projectavatar?size=small&avatarId=10324",
            "16x16":"http://127.0.0.1:8888/secure/projectavatar?size=xsmall&avatarId=10324",
            "32x32":"http://127.0.0.1:8888/secure/projectavatar?size=medium&avatarId=10324"
        },
        "projectTypeKey":"software"
    },
    {
        "expand":"description,lead,url,projectKeys",
        "self":"http://127.0.0.1:8888/rest/api/2/project/10002",
        "id":"10002",
        "key":"TTTES",
        "name":"TTTEST",
        "avatarUrls":{
            "48x48":"http://127.0.0.1:8888/secure/projectavatar?avatarId=10324",
            "24x24":"http://127.0.0.1:8888/secure/projectavatar?size=small&avatarId=10324",
            "16x16":"http://127.0.0.1:8888/secure/projectavatar?size=xsmall&avatarId=10324",
            "32x32":"http://127.0.0.1:8888/secure/projectavatar?size=medium&avatarId=10324"
        },
        "projectTypeKey":"business"
    }
]
