### ISSUE TITLE
Unable to check out JIRA team and DB data

### ISSUE THREAD

**Issue by No6-start** [Hygieia/Hygieia#3204]
2019-12-17 15:00:00,741 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=http://10.1.135.25:8080/rest/agile/1.0/team/10502/issue?jql=issueType in ('Task') and updatedDate>='2019/11/17 15:00'&fields=id&startAt=0 status=404 duration=68
2019-12-17 15:00:00,742 [taskScheduler-1] ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: http://10.1.135.25:8080/rest/agile/1.0/team/10502/issue?jql=issueType in ('Task') and updatedDate>='2019/11/17 15:00'&fields=id&startAt=0
2019-12-17 15:00:00,745 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Team Issues Refreshed            0s
2019-12-17 15:00:00,748 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collected 0 teams and 21 projects
2019-12-17 15:00:00,754 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 1 projects.
2019-12-17 15:00:01,605 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=http://10.1.135.25:8080/rest/api/2/search?jql=project=10502 and issueType in ('Task') and updatedDate>='2019/11/17 15:00'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,,customfield_10000,customfield_10002,customfield_10003&startAt=0 status=200 duration=850
2019-12-17 15:00:01,620 [taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
	at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:402) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:393) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:359) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$6(FeatureCollectorTask.java:262) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:258) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:159) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.9.jar!/:3.1.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by No6-start** [comment]
my conf

dbname=dashboarddb
dbhost=localhost
dbport=27017
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2008-01-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=http://1.1.1.1:8080
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=ZHkteGppbnl1OlpoYW53YW5nMDAw
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Task
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=
feature.collectorItemOnlyUpdate=true
feature.maxNumberOfFeaturesPerBoard=1000
feature.refreshTeamAndProjectHours=1
feature.jiraStoryIds[0]=3
