### ISSUE TITLE
Find a Bug in Hygieia/UI 

### ISSUE THREAD

**Issue by xiegudong45** [Hygieia/Hygieia#3213]
Hi, 

I thought I just found a potential bug under Hygieia/UI. In line 20 of  src/components/widgets/log/view.js, there's a plugin called Chartist.plugins.legend(), but it has some error when the widget runs. Besides, under the src/app/chartist/plugins folder, there's no file called legend.js.

```
TypeError: Chartist.plugins.legend is not a function
    at new LogViewController (http://localhost:3000/components/widgets/log/view.js:20:34)
    at Object.instantiate (http://localhost:3000/node_modules/angular.js:4786:14)
    at $controller (http://localhost:3000/node_modules/angular.js:10607:28)
    at Scope.init (http://localhost:3000/app/dashboard/directives/widget.js:200:47)
    at Object.processWidget [as callback] (http://localhost:3000/app/dashboard/directives/widget.js:77:23)
    at controller.registerWidget (http://localhost:3000/app/dashboard/directives/widget-container.js:81:28)
    at Object.link (http://localhost:3000/app/dashboard/directives/widget.js:54:33)
    at http://localhost:3000/node_modules/angular.js:1259:18
    at http://localhost:3000/node_modules/angular.js:10146:44
    at invokeLinkFn (http://localhost:3000/node_modules/angular.js:10152:9) <widget name="{{widgetName}}" widget-title="{{template.widgetDisplay[widgetName.toLowerCase()]}}" class="ng-isolate-scope">
```

**Comment by rvema** [comment]
@xiegudong45 if you have a solution for this issue please create a PR fixing the same.
