### ISSUE TITLE
Build failed for UI - Linux, Fedora 31

### ISSUE THREAD

**Issue by Jaff** [Hygieia/Hygieia#3215]
Using the Hygieia/UI/ directory, ran `mvn clean package integration-test` and got this output:
```
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ UI ---
[INFO] Node v6.9.1 is already installed.
[INFO] NPM 5.0.1 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ UI ---
[INFO] Running 'npm install --ignore-scripts' in /home/mjaffe/work/DashBoards/Hygieia/UI
[INFO] up to date in 6.525s
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:gulp (gulp build) @ UI ---
[INFO] Running 'gulp build' in /home/mjaffe/work/DashBoards/Hygieia/UI
[INFO] [17:00:10] Using gulpfile ~/work/DashBoards/Hygieia/UI/gulpfile.js
[INFO] [17:00:10] Starting 'build'...
[INFO] [17:00:10] Starting 'clean'...
[INFO] [17:00:10] Finished 'clean' after 202 ms
[INFO] [17:00:10] Starting 'assets'...
[INFO] [17:00:10] Starting 'themes'...
[INFO] [17:00:10] Starting 'fonts'...
[INFO] [17:00:10] Starting 'js'...
[INFO] [17:00:10] Starting 'views'...
[INFO] [17:00:10] Starting 'test-data'...
[INFO] [17:00:19] Finished 'themes' after 8.46 s
[INFO] [17:00:19] Finished 'assets' after 8.48 s
[INFO] [17:00:19] Finished 'fonts' after 8.49 s
[INFO] [17:00:19] Finished 'test-data' after 8.62 s
[INFO] [17:00:19] Finished 'views' after 8.74 s
[INFO] [17:00:19] Finished 'js' after 8.79 s
[INFO] [17:00:19] Starting 'html'...
[INFO] [17:00:29] 'html' errored after 9.38 s
[INFO] [17:00:29] RangeError: Maximum call stack size exceeded
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/npm-wiredep/lib/detect-dependencies.js:149:29
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:4905:15
[INFO]     at baseForOwn (/home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:2990:24)
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:4874:18
[INFO]     at Function.forEach (/home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:9342:14)
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/npm-wiredep/lib/detect-dependencies.js:183:11
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:4905:15
[INFO]     at baseForOwn (/home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:2990:24)
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:4874:18
[INFO]     at Function.forEach (/home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/lodash/lodash.js:9342:14)
[INFO]     at /home/mjaffe/work/DashBoards/Hygieia/UI/node_modules/npm-wiredep/lib/detect-dependencies.js:183:11
[INFO] [17:00:29] 'build' errored after 18 s
[INFO] [17:00:29] Error in plugin 'run-sequence'
[INFO] Message:
[INFO]     An error occured in task 'html'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.711 s
[INFO] Finished at: 2020-01-21T17:00:29-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:gulp (gulp build) on project UI: Failed to run task: 'gulp build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**Comment by Jaff** [comment]
Platform is Linux, Fedora 31.

**Comment by Jaff** [comment]
Suspect a cyclic dependency; see https://github.com/taptapship/wiredep/issues/187

**Comment by Jaff** [comment]
Looks OK on MacOS and Ubuntu 18.04, though

**Comment by RavinderSinghALJ** [comment]
@Jaff  We are seeing the same issue on Mac also. Did you find any resolution for the same?
