### ISSUE TITLE
Issue with Github collector.

### ISSUE THREAD

**Issue by mayukh87** [Hygieia/Hygieia#3244]
Hello,

I am using [GitHub collector](https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/scm/github.md) and getting the following error.

```
ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/xxx/xxxx
org.springframework.web.client.HttpClientErrorException: 403 rate limit exceeded
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.
RELEASE]
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector.jar!/:3.1.4-SNAPSHOT]
at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector.jar!/:3.1.4-SNAPSHOT]
at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:198) ~[github-scm-collector.jar!/:3.1.4-SNAPSHOT]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.5.jar!/:3.1.4-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.j
ar!/:4.2.5.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522) [na:1.8.0]
at java.util.concurrent.FutureTask.run(FutureTask.java:277) [na:1.8.0]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191) [na:1.8.0]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [na:1.8.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) [na:1.8.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:1.8.0]
at java.lang.Thread.run(Thread.java:820) [na:2.9 (01-08-2020)]
2020-04-20 10:21:28,076 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2020-04-20 10:21:28,076 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2020-04-20 10:21:28,076 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Pulls               0        0s
2020-04-20 10:21:28,076 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - New Issues              0        0s
2020-04-20 10:21:28,076 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s
```

I have also tried with different repos and different github account, but the result is same. Can anyone please help?

Regards,
Mayukh

**Comment by rvema** [comment]
which github collector are you using? hygieia-scm-github-collector or hygieia-scm-github-graphql-collector

**Comment by hi2ari** [comment]
> which github collector are you using? hygieia-scm-github-collector or hygieia-scm-github-graphql-collector

We are using the hygieia-scm-github-collector

**Comment by rvema** [comment]
@hi2ari can you use hygieia-scm-github-graphql-collector instead? This collector has the fix for handling ratelimits.

**Comment by mayukh87** [comment]
@rvema can you please tell if the setup process for **hygieia-scm-github-graphql-collector** is same as **hygieia-scm-github-collector**. I cannot find any documentation for **hygieia-scm-github-graphql-collector**.

I was following these steps 
[hygieia-scm-github-collector](https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/scm/github.md)

Will it be same for **hygieia-scm-github-graphql-collector** ?

**Comment by karlpanganiban** [comment]
@mayukh87 I have experienced this same issue, and did the same approach. Use the graphql instead.

Do the same steps. :)

**Comment by sreekanthreddypb** [comment]
@rvema  I am using the hygieia-scm-github-graphql-collector and still getting this error org.springframework.web.client.HttpClientErrorException: 403 rate limit exceeded

2021-07-06 14:44:16,521 [main] INFO  c.capitalone.dashboard.GraphQLGithub - Started GraphQLGithub in 9.071 seconds (JVM running for 9.967)
2021-07-06 14:45:00,004 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Getting Collector: GitHub
2021-07-06 14:45:00,017 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting Collector=GitHub
2021-07-06 14:45:00,046 [taskScheduler-1] INFO  c.c.d.collector.DefaultGitHubClient - Executing events API call for http://api.github.com/events
2021-07-06 14:45:00,383 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall http_method=GET http_url=http://api.github.com/events http_status=403 http_duration=337
2021-07-06 14:45:00,386 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 403 rate limit exceeded
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:108)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:709)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:662)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:622)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:540)
	at com.capitalone.dashboard.client.RestClient.makeRestCallGet(RestClient.java:161)
	at com.capitalone.dashboard.client.RestClient.makeRestCallGet(RestClient.java:207)
	at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCallGet(DefaultGitHubClient.java:1324)
	at com.capitalone.dashboard.collector.DefaultGitHubClient.getChangedRepos(DefaultGitHubClient.java:173)
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:197)
	at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:1)
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:69)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-07-06 14:46:12,707 [MaintenanceTimer-1-thread-1] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:152}] to localhost:27017 because it is past its maximum allowed idle time.
