### ISSUE TITLE
My Hygieia (deploy widget) doesn't display any data.

### ISSUE THREAD

**Issue by karlpanganiban** [Hygieia/Hygieia#3263]
HERE'S MY SETUP:

- hygieia jenkins plugin is already setup using this document: https://hygieia.github.io/Hygieia/hygieia-jenkins-plugin.html

- i am using this jenkins file

```
pipeline {

    agent {
        node {
            label 'hygieia-build-server-c7'
            customWorkspace '/home/centos/jenkins/github-graphql-workspace'
        }
    }

    stages {
        stage('Dev') {
            steps {
                sh "./scripts/build-github-collector-app.sh"     --> this script outputs .jar file in /target
                hygieiaArtifactPublishStep artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: ''
                hygieiaDeployPublishStep applicationName: 'hygieia', artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'Dev'
                hygieiaBuildPublishStep buildStatus: 'Success'
            }
        }
        stage('Qa') {
            steps {
                sh "./scripts/deploy-github-collector.sh"    --> just some random script
                hygieiaArtifactPublishStep artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: ''
                hygieiaDeployPublishStep applicationName: 'hygieia', artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'Dev'
                hygieiaBuildPublishStep buildStatus: 'Success'
            }
        }
        stage('Int') {
            steps {
            	sh "echo Int"
                hygieiaArtifactPublishStep artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: ''
                hygieiaDeployPublishStep applicationName: 'hygieia', artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'Dev'
                hygieiaBuildPublishStep buildStatus: 'Success'
            }
        }
        stage('Perf') {
            steps {
            	sh "echo Perf"
                hygieiaArtifactPublishStep artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: ''
                hygieiaDeployPublishStep applicationName: 'hygieia', artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'Dev'
                hygieiaBuildPublishStep buildStatus: 'Success'
            }
        }
        stage('Prod') {
            steps {
            	sh "echo Prod"
                hygieiaArtifactPublishStep artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: ''
                hygieiaDeployPublishStep applicationName: 'hygieia', artifactDirectory: '/target', artifactGroup: 'com.capitalone.dashboard', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'Dev'
                hygieiaBuildPublishStep buildStatus: 'Success'
            }
        }
    }
}
```

- here is the jenkins log showing data has been pushed to hygiea (api)
```
[Pipeline] hygieiaArtifactPublishStep (hide)
Publishing data for API http://x.x.x.x:8080/api
Hygieia: Published Build Data For Artifacts Publishing. Response Code: 201. Response Value= 5edee6bea7b11b0008f84ad2,5ede15a7857aba0008091440
Hygieia Build Artifact Publisher - Looking for file pattern '*.jar' in directory /target
[Pipeline] hygieiaDeployPublishStep
Publishing data for API http://x.x.x.x:8080/api
Hygieia: Published Build Data For Deployment Publishing. Response Code: 201. Response Value= 5edee6bea7b11b0008f84ad2,5ede15a7857aba0008091440
Hygieia Deployment Publisher - Looking for file pattern '*.jar' in directory /target
[Pipeline] hygieiaBuildPublishStep
Publishing data for API http://x.x.x.x:8080/api
Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 5edee6bea7b11b0008f84ad2,5ede15a7857aba0008091440
```

- here a sample logs in my hygieia api. shows it accepts the data.
```
2020-06-09 01:33:03,947 [http-nio-8080-exec-2] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=117, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-09 01:33:04,056 [http-nio-8080-exec-4] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=72, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-09 01:33:04,170 [http-nio-8080-exec-5] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=92, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
```

- But still, no data displaying in my deploy widget
![image](https://user-images.githubusercontent.com/14307099/84097064-0d850a00-aa36-11ea-9d1c-e67378a76e2f.png)

Can someone tell me what i'm missing here? Thanks in advance!

**Comment by karlpanganiban** [comment]
UPDATE:
- I am still using the same jenkinsfile
- However, i can see a new exception log in jenkins build. Looks like some error how I use hygieia commands in my jenkinsfile?
![image](https://user-images.githubusercontent.com/14307099/84222984-7d18f900-ab0b-11ea-8295-b4019ffd2e09.png)
- On the other hands, i still receive the same HTTP 201 response from api logs - which i guess is still fine?
```
2020-06-10 03:08:27,219 [http-nio-8080-exec-7] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=37, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:27,293 [http-nio-8080-exec-8] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=33, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:45,728 [http-nio-8080-exec-4] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=33, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:45,807 [http-nio-8080-exec-9] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=44, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:46,311 [http-nio-8080-exec-6] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=33, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:46,395 [http-nio-8080-exec-10] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=49, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:46,913 [http-nio-8080-exec-1] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=51, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:46,991 [http-nio-8080-exec-2] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=49, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:47,521 [http-nio-8080-exec-4] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=42, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:47,615 [http-nio-8080-exec-9] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=52, endPoint=/api/v2/build, reqMethod=POST, status=201, clientIp=x.x.x.x
2020-06-10 03:08:50,853 [http-nio-8080-exec-6] INFO  c.c.d.a.t.JwtAuthenticationFilter - requester=READ_ONLY, timeTaken=49, endPoint=/api/v3/build, reqMethod=POST, status=201, clientIp=x.x.x.x
```
- But still no luck, no data appears in my Deploy Widget

I hope someone can help find what part I am missing.

**Comment by rvema** [comment]
looking into this issue, check back in 2 days

**Comment by karlpanganiban** [comment]
@rvema thanks a lot!

- Btw, I found out that this ParseException log ONLY SHOWS if you CHECKED the "Publish all build data" in Global Hygieia Publisher settings
![image](https://user-images.githubusercontent.com/14307099/84226575-b6a23200-ab14-11ea-8037-0a0cbabf02fd.png)
![image](https://user-images.githubusercontent.com/14307099/84226851-798a6f80-ab15-11ea-9057-1f525e25576f.png)


- Here are some additional information about the ParseException error (got it from jenkins' System Log)
```
Jun 10, 2020 4:01:58 AM INFO hygieia.builder.CommitBuilder buildCommits
Adding commit:null:null:33dc83e2c54a36b45bb93d4a4bd65d6793fbdf22:put hygieia steps at the end stage only
Jun 10, 2020 4:05:23 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
hygieia-deploy-collector-github-graphql #45 completed: SUCCESS
Jun 10, 2020 4:16:44 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
hygieia-deploy-collector-github-graphql #46 completed: SUCCESS
Jun 10, 2020 4:18:16 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
hygieia-deploy-collector-github-graphql #47 completed: SUCCESS
Jun 10, 2020 4:18:16 AM WARNING jenkins.plugins.hygieia.DefaultHygieiaService getStageResponse
HygieiaService.getStageResponse(): Rest Call try # 1 failed due to ParseException: . Will retry after 1 Second.
Jun 10, 2020 4:18:17 AM WARNING jenkins.plugins.hygieia.DefaultHygieiaService getStageResponse
HygieiaService.getStageResponse(): Rest Call try # 2 failed due to ParseException: . Will retry after 1 Second.
Jun 10, 2020 4:18:18 AM WARNING jenkins.plugins.hygieia.DefaultHygieiaService getStageResponse
HygieiaService.getStageResponse(): Rest Call try # 3 failed due to ParseException: . Will retry after 1 Second.
Jun 10, 2020 4:18:19 AM INFO hygieia.utils.HygieiaUtils getBuildStages
Unexpected character (<) at position 0.
	at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
	at hygieia.utils.HygieiaUtils.getBuildStages(HygieiaUtils.java:449)
	at jenkins.plugins.hygieia.HygieiaGlobalListener.processStages(HygieiaGlobalListener.java:175)
	at jenkins.plugins.hygieia.HygieiaGlobalListener.publishBuildData(HygieiaGlobalListener.java:128)
	at jenkins.plugins.hygieia.HygieiaGlobalListener.onCompleted(HygieiaGlobalListener.java:96)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:599)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$800(WorkflowRun.java:137)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1026)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1463)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:488)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I hope this info can help. Let me know if you need more info from my setup. Thanks.

**Comment by rvema** [comment]
@Courtneyp123 can you check on this issue when you get some time?

**Comment by stevegal** [comment]
the publish all build data is causing your parse exception (so I'd turn it off for you build). The artefact path specified is absolute not relative, so, assuming your script outputs the jar file in `${workspace}/target` then you should specify your search directory as `./target`. Note the `hygieiaDeployPublishStep` needs to find an artefact if it is to publish the deployment to the hygieia api.

**Comment by karlpanganiban** [comment]
@stevegal thanks a lot! this issue is already addressed in our discussion on other same case https://github.com/Hygieia/hygieia-publisher-jenkins-plugin/issues/24
