### ISSUE TITLE
Jira collector fails while collecting all data

### ISSUE THREAD

**Issue by Sjnahak** [Hygieia/Hygieia#3301]
Hi ,

Jira collector was to to add all board 76(boards) but while collecting all deatils of board out of 76 boards it fails in between
```
2020-09-14 08:20:17,964 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collected 76 teams and 50 projects
2020-09-14 08:20:17,976 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 76 boards.
``` 
# Error Logs

```
2020-09-13 14:54:00,000 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Getting Collector: Jira
2020-09-13 14:54:00,108 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/api/2/issuetype status=200 duration=104
2020-09-13 14:54:00,110 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting Collector=Jira
2020-09-13 14:54:00,110 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-09-13 14:54:00,110 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - https://comapnyname.atlassian.net
2020-09-13 14:54:00,110 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-09-13 14:54:00,110 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2020-09-13 14:54:00,110 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 6. Collector is only collecting updated/new issues.
2020-09-13 14:54:00,123 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 76 boards.
2020-09-13 14:54:00,335 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/board/87/issue?jql=issueType in ('Story','Epic','Bug') and updatedDate>='2020/09/13 14:53'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_11000,customfield_10007,null,null&startAt=0 status=200 duration=212
2020-09-13 14:54:00,336 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2020-09-13T14:53:00.089 0        0s
2020-09-13 14:54:00,339 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 2 of 76 boards.
2020-09-13 14:54:00,526 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/board/59/issue?jql=issueType in ('Story','Epic','Bug') and updatedDate>='2020/09/13 14:53'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_11000,customfield_10007,null,null&startAt=0 status=200 duration=186
2020-09-13 14:54:00,527 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2020-09-13T14:53:00.318 0        0s
2020-09-13 14:54:00,530 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 3 of 76 boards.
2020-09-13 14:54:00,765 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/board/49/issue?jql=issueType in ('Story','Epic','Bug') and updatedDate>='2020/09/13 14:53'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_11000,customfield_10007,null,null&startAt=0 status=200 duration=235
2020-09-13 14:54:00,765 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Story Data Collected since 2020-09-13T14:53:00.493 0        0s
2020-09-13 14:54:00,769 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 4 of 76 boards.
2020-09-13 14:54:01,553 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/board/151/issue?jql=issueType in ('Story','Epic','Bug') and updatedDate>='2020/08/14 14:54'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_11000,customfield_10007,null,null&startAt=0 status=200 duration=784
2020-09-13 14:54:02,029 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/issue/113521 status=200 duration=471
2020-09-13 14:54:02,453 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/issue/113525 status=200 duration=424
2020-09-13 14:54:02,865 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/issue/119718 status=200 duration=412
2020-09-13 14:54:03,176 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://comapnyname.atlassian.net/rest/agile/1.0/issue/119731 status=200 duration=311
2020-09-13 14:54:03,177 [taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to java.lang.String
        at com.capitalone.dashboard.collector.SprintFormatter.parseSprint(SprintFormatter.java:36)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getSprint(DefaultJiraClient.java:608)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeature(DefaultJiraClient.java:530)
        at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:403)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:389)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:265)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$7(FeatureCollectorTask.java:279)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:276)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:162)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:50)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:69)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-09-13 14:54:03,177 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished running Collector=Jira timeTaken=3067 collectorItems=0
^C2020-09-13 14:54:11,855 [Thread-3] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@497470ed: startup date [Sun Sep 13 14:51:52 UTC 2020]; root of context hierarchy
2020-09-13 14:54:11,857 [Thread-3] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2020-09-13 14:54:11,867 [Thread-3] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
```
# application.properties file
```
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=XXXX
dbhost=127.0.0.1
dbport=27017
# Logging File location
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2019-03-01T00:00:00.000000
feature.masterStartDate=2019-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2019-03-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=https://comapanyname.atlassian.net
feature.jiraQueryEndpoint=/rest/api/2/
feature.jiraCredentials=encrtptedpassword
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Story,Epic,Bug
feature.jiraSprintDataFieldName=customfield_10007
#feature.jiraTeamFieldName=customfield_11000
#feature.jiraStoryPointsFieldName=customfield_
feature.jiraBoardAsTeam=true
feature.collectorItemOnlyUpdate=false
feature.jiraEpicIdFieldName=customfield_10009
feature.maxNumberOfFeaturesPerBoard=8000
feature.refreshTeamAndProjectHours=3
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doingStatuses[1]=IN QA
feature.doneStatuses[0]=Done
feature.jiraStoryIds[0]=10001
feature.jiraStoryIds[1]=10000
feature.jiraStoryIds[2]=1
feature.jiraStoryIds[3]=10415
feature.jiraStoryIds[4]=10414
```
is it due to cron set feature.cron=0 * * * * *  at every seconds or anything else?

**Comment by Sjnahak** [comment]
@rvema @Sbrenthughes  @tabladrum Any inputs here ?

**Comment by Sjnahak** [comment]
Now Collector run is successfull but no data in the UI
![image](https://user-images.githubusercontent.com/33506659/93569372-10858400-f9af-11ea-9022-29dc350f52b0.png)

![image](https://user-images.githubusercontent.com/33506659/93569440-272bdb00-f9af-11ea-81d0-9b38b4a3eabf.png)

**Comment by Sjnahak** [comment]
Any input here?

**Comment by HaasyaDhanvika** [comment]
The initial problem of failing in between data collection is due to huge amount of data present in 4th board, check what is that 4th board and remove user access to the board and restart the collector. It works for me.

The second problem collector run was successful and no data in UI, im also facing the same issue.
