### ISSUE TITLE
Jenkins collector Integration with Hygieia

### ISSUE THREAD

**Issue by satyanarayanaguptha** [Hygieia/Hygieia#3336]
i'm facing org.mongodb.driver.connection and client exception loading jobs (403 forbidden) while trying to install jenkins-collector jar to collect data from jenkins and post to Hygieia dashboard.
I could able to browse UI

Here is my application.properties config file  to jenkins-collector jar data:
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=dashboarduser
dbpassword=dbpassword
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
jenkins.cron=0 0/5 * * * *
jenkins.servers[0]=http://34.82.84.91:8088
jenkins.username[0]=jenkinsuser
jenkins.apiKeys[0]=119253237e063052404c2c637f20fcccc6
jenkins.saveLog=false

Please find the log 
16:15:15,958 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:15:15,959 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:15:15,960 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/devops/hygieia/hygieia-build-jenkins-collector/target/jenkins-build-collector.jar!/BOOT-INF/classes!/logback.xml]
16:15:15,985 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:15:15,985 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/devops/hygieia/hygieia-build-jenkins-collector/target/jenkins-build-collector.jar!/BOOT-INF/lib/core-3.10.0.jar!/logback.xml]
16:15:15,985 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/devops/hygieia/hygieia-build-jenkins-collector/target/jenkins-build-collector.jar!/BOOT-INF/classes!/logback.xml]
16:15:16,060 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@5cb0d902 - URL [jar:file:/home/devops/hygieia/hygieia-build-jenkins-collector/target/jenkins-build-collector.jar!/BOOT-INF/classes!/logback.xml] is not of type file
16:15:16,213 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:15:16,214 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:15:16,240 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:15:16,253 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:15:16,326 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:15:16,332 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
16:15:16,375 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1190900417 - No compression will be used
16:15:16,378 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1190900417 - Will use the pattern logs/buildcollector-%d{yyyy-MM-dd}.%i.log for the active file
16:15:16,391 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1698c449 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/buildcollector-%d{yyyy-MM-dd}.%i.log'.
16:15:16,391 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1698c449 - Roll-over at midnight.
16:15:16,397 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1698c449 - Setting initial period to Tue Jan 19 16:15:16 UTC 2021
16:15:16,398 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1698c449 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
16:15:16,398 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1698c449 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
16:15:16,403 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:15:16,405 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/buildcollector-2021-01-19.0.log
16:15:16,405 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
16:15:16,407 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:15:16,407 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
16:15:16,411 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:15:16,411 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:15:16,412 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5ef04b5 - Registering current configuration as safe fallback point

_   _             _      _             ______       _ _     _        _____       _ _           _
| | | |           (_)    (_)            | ___ \     (_) |   | |      /  __ \     | | |         | |
| |_| |_   _  __ _ _  ___ _  __ _ ______| |_/ /_   _ _| | __| |______| /  \/ ___ | | | ___  ___| |_ ___  _ __
|  _  | | | |/ _` | |/ _ \ |/ _` |______| ___ \ | | | | |/ _` |______| |    / _ \| | |/ _ \/ __| __/ _ \| '__|
| | | | |_| | (_| | |  __/ | (_| |      | |_/ / |_| | | | (_| |      | \__/\ (_) | | |  __/ (__| || (_) | |
\_| |_/\__, |\__, |_|\___|_|\__,_|      \____/ \__,_|_|_|\__,_|       \____/\___/|_|_|\___|\___|\__\___/|_|
        __/ | __/ |
       |___/ |___/

2021-01-19 16:15:17,995 [main] INFO  com.capitalone.dashboard.Application - Starting Application v3.2.0-SNAPSHOT on devops with PID 4018 (/home/devops/hygieia/hygieia-build-jenkins-collector/target/jenkins-build-collector.jar started by root in /home/devops/hygieia/hygieia-build-jenkins-collector/target)
2021-01-19 16:15:18,015 [main] INFO  com.capitalone.dashboard.Application - No active profile set, falling back to default profiles: default
2021-01-19 16:15:18,253 [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@123a439b: startup date [Tue Jan 19 16:15:18 UTC 2021]; root of context hierarchy
2021-01-19 16:15:19,443 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.4.2.Final
2021-01-19 16:15:22,732 [main] INFO  c.u.j.c.EnableEncryptablePropertiesBeanFactoryPostProcessor - Post-processing PropertySource instances
2021-01-19 16:15:22,838 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2021-01-19 16:15:22,839 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource servletConfigInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2021-01-19 16:15:22,839 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource servletContextInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2021-01-19 16:15:22,840 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2021-01-19 16:15:22,841 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2021-01-19 16:15:22,841 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2021-01-19 16:15:22,841 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource applicationConfig: [file:/home/devops/hygieia/hygieia-build-jenkins-collector/target/application.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2021-01-19 16:15:22,842 [main] INFO  c.u.j.EncryptablePropertySourceConverter - Converting PropertySource applicationConfig: [file:./application.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2021-01-19 16:15:23,094 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@6356695f' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-01-19 16:15:23,117 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-01-19 16:15:23,532 [main] INFO  c.u.j.r.DefaultLazyPropertyResolver - Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
2021-01-19 16:15:23,540 [main] INFO  c.u.j.d.DefaultLazyPropertyDetector - Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2021-01-19 16:15:23,941 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat initialized with port(s): 8081 (http)
2021-01-19 16:15:24,010 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8081"]
2021-01-19 16:15:24,095 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2021-01-19 16:15:24,096 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.57
2021-01-19 16:15:24,320 [localhost-startStop-1] INFO  o.a.c.c.C.[.[localhost].[/api] - Initializing Spring embedded WebApplicationContext
2021-01-19 16:15:24,320 [localhost-startStop-1] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 6068 ms
2021-01-19 16:15:25,112 [localhost-startStop-1] INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2021-01-19 16:15:25,583 [localhost-startStop-1] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2021-01-19 16:15:25,690 [localhost-startStop-1] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2021-01-19 16:15:25,811 [localhost-startStop-1] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', applicationName='null', compressors='[]', readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, fsync=null, journal=null, retryWrites=false, readConcern=com.mongodb.ReadConcern@0, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@b9c16817, serverSelector=null, clusterListeners=[], commandListeners=[], minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=30000, socketTimeout=900000, socketKeepAlive=true, sslEnabled=false, sslInvalidHostNamesAllowed=false, sslContext=null, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@69ba1b13, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@4c74a5c, socketFactory=null, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[]}, socketSettings=SocketSettings{connectTimeoutMS=30000, readTimeoutMS=900000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}}}
2021-01-19 16:15:26,196 [cluster-ClusterId{value='6007059d0274070fb20f073f', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:55}] to localhost:27017
2021-01-19 16:15:26,375 [cluster-ClusterId{value='6007059d0274070fb20f073f', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=176285370}
2021-01-19 16:15:27,029 [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'characterEncodingFilter' to: [/*]
2021-01-19 16:15:27,032 [localhost-startStop-1] INFO  o.s.b.w.s.DelegatingFilterProxyRegistrationBean - Mapping filter: 'springSecurityFilterChain' to: [/*]
2021-01-19 16:15:27,033 [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'apiTokenRequestFilter' to: [/*]
2021-01-19 16:15:27,035 [localhost-startStop-1] INFO  o.s.b.w.s.ServletRegistrationBean - Mapping servlet: 'dispatcherServlet' to [/]
2021-01-19 16:15:27,197 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
2021-01-19 16:15:29,294 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:56}] to localhost:27017
2021-01-19 16:15:30,691 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2021-01-19 16:15:30,695 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2021-01-19 16:15:30,697 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2021-01-19 16:15:30,715 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', applicationName='null', compressors='[]', readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, fsync=null, journal=null, retryWrites=false, readConcern=com.mongodb.ReadConcern@0, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@b9c16817, serverSelector=null, clusterListeners=[], commandListeners=[], minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=30000, socketTimeout=900000, socketKeepAlive=true, sslEnabled=false, sslInvalidHostNamesAllowed=false, sslContext=null, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@69ba1b13, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@4c74a5c, socketFactory=null, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[]}, socketSettings=SocketSettings{connectTimeoutMS=30000, readTimeoutMS=900000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}}}
2021-01-19 16:15:30,751 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2021-01-19 16:15:30,752 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2021-01-19 16:15:30,753 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2021-01-19 16:15:30,779 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', applicationName='null', compressors='[]', readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, fsync=null, journal=null, retryWrites=false, readConcern=com.mongodb.ReadConcern@0, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@b9c16817, serverSelector=null, clusterListeners=[], commandListeners=[], minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=30000, socketTimeout=900000, socketKeepAlive=true, sslEnabled=false, sslInvalidHostNamesAllowed=false, sslContext=null, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@69ba1b13, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@4c74a5c, socketFactory=null, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[]}, socketSettings=SocketSettings{connectTimeoutMS=30000, readTimeoutMS=900000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}}}
2021-01-19 16:15:30,814 [cluster-ClusterId{value='600705a20274070fb20f0740', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:57}] to localhost:27017
2021-01-19 16:15:30,816 [cluster-ClusterId{value='600705a20274070fb20f0740', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=802853}
2021-01-19 16:15:30,852 [cluster-ClusterId{value='600705a20274070fb20f0741', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:58}] to localhost:27017
2021-01-19 16:15:30,853 [cluster-ClusterId{value='600705a20274070fb20f0741', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=705564}
2021-01-19 16:15:31,904 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSetfalse
2021-01-19 16:15:31,907 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2021-01-19 16:15:31,909 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2021-01-19 16:15:31,916 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', applicationName='null', compressors='[]', readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, fsync=null, journal=null, retryWrites=false, readConcern=com.mongodb.ReadConcern@0, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@b9c16817, serverSelector=null, clusterListeners=[], commandListeners=[], minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=30000, socketTimeout=900000, socketKeepAlive=true, sslEnabled=false, sslInvalidHostNamesAllowed=false, sslContext=null, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@69ba1b13, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@4c74a5c, socketFactory=null, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[]}, socketSettings=SocketSettings{connectTimeoutMS=30000, readTimeoutMS=900000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}}}
2021-01-19 16:15:31,991 [cluster-ClusterId{value='600705a30274070fb20f0742', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:59}] to localhost:27017
2021-01-19 16:15:31,992 [cluster-ClusterId{value='600705a30274070fb20f0742', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=729763}
2021-01-19 16:15:33,990 [main] INFO  o.s.s.web.DefaultSecurityFilterChain - Creating filter chain: org.springframework.security.web.util.matcher.AnyRequestMatcher@1, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@723e88f9, org.springframework.security.web.context.SecurityContextPersistenceFilter@7bf3a5d8, org.springframework.security.web.header.HeaderWriterFilter@6f3187b0, org.springframework.security.web.authentication.logout.LogoutFilter@51a9ad5e, com.capitalone.dashboard.auth.apitoken.ApiTokenRequestFilter@1dd93a09, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@39b43d60, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@72ef8d15, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5f0fd5a0, org.springframework.security.web.session.SessionManagementFilter@48b67364, org.springframework.security.web.access.ExceptionTranslationFilter@3336e6b6, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@407a7f2a]
2021-01-19 16:15:34,140 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2021-01-19 16:15:34,142 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2021-01-19 16:15:34,226 [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2021-01-19 16:15:34,354 [main] INFO  o.s.w.s.m.m.a.RequestMappingHandlerAdapter - Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@123a439b: startup date [Tue Jan 19 16:15:18 UTC 2021]; root of context hierarchy
2021-01-19 16:15:35,236 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2021-01-19 16:15:35,259 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8081"]
2021-01-19 16:15:35,265 [main] INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
2021-01-19 16:15:35,292 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8081 (http)
2021-01-19 16:15:35,304 [main] INFO  com.capitalone.dashboard.Application - Started Application in 18.381 seconds (JVM running for 20.973)
2021-01-19 16:17:25,761 [MaintenanceTimer-1-thread-1] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:56}] to localhost:27017 because it is past its maximum allowed idle time.
2021-01-19 16:20:00,001 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Getting Collector: Hudson
2021-01-19 16:20:00,040 [taskScheduler-1] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:60}] to localhost:27017
2021-01-19 16:20:00,062 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting Collector=Hudson
2021-01-19 16:20:00,119 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2021-01-19 16:20:00,120 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://34.82.84.91:8088
2021-01-19 16:20:00,120 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2021-01-19 16:20:00,347 [taskScheduler-1] ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:108)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:709)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:662)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:637)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:558)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:657)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getJobsCount(DefaultHudsonClient.java:193)
        at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:113)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:126)
        at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:44)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:69)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-01-19 16:20:00,373 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://34.82.84.91:8088 0s
2021-01-19 16:20:00,373 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished running Collector=Hudson timeTaken=311 collectorItems=0

**Comment by rvema** [comment]
seems to be an issue with the api token generated in jenkins
