### ISSUE TITLE
not able to configure bitbucket collector for private repository. ERROR c.c.d.c.DefaultBitbucketCloudClient - 401 Unauthorized

### ISSUE THREAD

**Issue by venkateshreddy53** [hygieia/hygieia#3402]
2021-06-17 12:44:20,224 [main] INFO  com.capitalone.dashboard.Application - Started Application in 7.189 seconds (JVM running for 8.04)
2021-06-17 12:45:00,000 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2021-06-17 12:45:00,010 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2021-06-17 12:45:00,010 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting...
2021-06-17 12:45:00,010 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2021-06-17 12:45:00,147 [taskScheduler-1] ERROR c.c.d.c.DefaultBitbucketCloudClient - Cannot decrypt this message
Wrong key size
2021-06-17 12:45:00,768 [taskScheduler-1] ERROR c.c.d.c.DefaultBitbucketCloudClient - 401 Unauthorized:https://bitbucket.org/api/2.0/repositories/reddyvr5353/project-new/commits?sha=master&since=2021-06-03T12:45Z
2021-06-17 12:45:00,769 [taskScheduler-1] INFO  c.c.d.collector.GitCollectorTask - {password=kailash5353, personalAccessToken=, branch=master, userID=reddyvr5353@gmail.com, url=https://bitbucket.org/reddyvr5353/project-new}::master::get pulls
2021-06-17 12:45:00,773 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.RuntimeException: Unable to decrypt SCM credentials
        at com.capitalone.dashboard.collector.PullRequestCollector.getPullRequests(PullRequestCollector.java:72) ~[bitbucket-scm-collector.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.GitCollectorTask.collect(GitCollectorTask.java:196) ~[bitbucket-scm-collector.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.1.5.jar!/:3.1.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]
Caused by: com.capitalone.dashboard.util.EncryptionException: Cannot decrypt this message
Wrong key size
        at com.capitalone.dashboard.util.Encryption.decryptString(Encryption.java:118) ~[core-3.1.5.jar!/:3.1.5]
        at com.capitalone.dashboard.collector.PullRequestCollector.getPullRequests(PullRequestCollector.java:70) ~[bitbucket-scm-collector.jar!/:3.1.2-SNAPSHOT]
        ... 11 common frames omitted

**Comment by AndriiKhodyriev** [comment]
You can show the configuration file?
 (first replace the accesses with invalid ones, but in the correct transformation)

**Comment by venkateshreddy53** [comment]
Below is the bitbucket.properties file.


dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017

server.contextPath=/api

server.port=8090

logging.file=./logs/bitbucket.log

git.cron=0 0/5 * * * *

git.host=api.bitbucket.org/

git.username=rvr5353

git.password=rvr5353

git.api=/api/2.0/repositories/

git.commitThresholdDays=15

git.pageSize=25

git.product=cloud

github.key=z58MZRr1E1dSJXcBqNw51w==
key=z58MZRr1E1dSJXcBqNw51w==

**Comment by venkateshreddy53** [comment]
can somebody please help ?
