### ISSUE TITLE
Issue With Jira Collector

### ISSUE THREAD

**Issue by sreekanthreddypb** [hygieia/hygieia#3409]
@rvema I am getting 401 unauthorized error for jira feature collector 

2021-07-06 15:00:00,016 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Getting Collector: Jira
2021-07-06 15:00:00,038 [taskScheduler-1] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:28, serverValue:171}] to localhost:27017
2021-07-06 15:00:00,071 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://rapids4321.atlassian.net/rest/api/2/issuetype status=401 duration=30
2021-07-06 15:00:00,071 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:108)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:709)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:662)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:622)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:540)
	at com.capitalone.dashboard.client.RestClient.makeRestCallGet(RestClient.java:158)
	at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:828)
	at com.capitalone.dashboard.collector.DefaultJiraClient.getJiraIssueTypeIds(DefaultJiraClient.java:299)
	at com.capitalone.dashboard.collector.FeatureCollectorTask.getCollector(FeatureCollectorTask.java:98)
	at com.capitalone.dashboard.collector.FeatureCollectorTask.getCollector(FeatureCollectorTask.java:1)
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:56)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-07-06 15:01:44,963 [MaintenanceTimer-1-thread-1] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:28, serverValue:171}] to localhost:27017 because it is past its maximum allowed idle time.

**Comment by sreekanthreddypb** [comment]
My application.properties

dbname=dashboarddb2
dbhost=localhost
dbusername=dashboarduser
dbpassword=dbpassword
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.port=8172

logging.file=./logs/jira.log
feature.pageSize=1000

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2021-03-01T00:00:00.000000
feature.masterStartDate=2021-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2021-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 */5 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
feature.jiraBaseUrl=https://rapids4321.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=cmFwaWRzZHhwY3VzdG9tZXJAZ21haWwuY29tOnJhcGlkc191c2VyQDEyMw==
# Trending Query:  Number of days in a sprint (not-required)
feature.sprintDays=60

# Trending Query:  Length of sprint week (not-required)
feature.sprintEndPrior=7

#Scheduled Job prior minutes to recover data created during execution time (usually, 2 minutes is enough)
feature.scheduledPriorMin=2

# OAuth is not fully implemented; please blank-out the OAuth values:

#feature.jiraOauthAuthtoken=
#feature.jiraOauthRefreshtoken=
#feature.jiraOauthRedirecturi=
#feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10000

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10003

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=1000

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=false

#Defines the number of hours between each board/team and project data refresh
feature.refreshTeamAndProjectHours=3

**Comment by sreekanthreddypb** [comment]
I am using this collectors in aws instance is any proxy setting needed
